import {mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {resolve} from "node:path";
import {compileSparseCM12GenerationTransfer,type SparseCM12GenerationGeometry} from "../../lib/methods/adaptive-volume/sparse-cm12-generation-transfer";
import type {SparseAtlasCompositeGrid} from "../../lib/methods/adaptive-volume/sparse-atlas-composite-projection";
type Box={id:number;lower:[number,number,number];widths:[number,number,number];span:number};
const parent:Box={id:0,lower:[0,0,0],widths:[2,2,2],span:2};
const children:Box[]=[];for(let z=0;z<2;z++)for(let y=0;y<2;y++)for(let x=0;x<2;x++)children.push({id:children.length,lower:[x,y,z],widths:[1,1,1],span:1});
function source(cells:Box[]):SparseCM12GenerationGeometry{return{dimensions:[2,2,2],cells,faces:[]}}
function target(cells:Box[]):SparseAtlasCompositeGrid{return {atlas:{dimensions:[2,2,2],brickFineResolution:2,directory:new Map([[0,{spanBricks:1}]])},cells:cells.map(c=>({id:c.id,centerFine:c.lower.map((v,a)=>v+c.widths[a]!/2),widthsFine:c.widths,brickKey:0,brickResolution:2/c.span})),gradientRows:[]} as unknown as SparseAtlasCompositeGrid}
const encode=(p:ReturnType<typeof compileSparseCM12GenerationTransfer>)=>({cellOffsets:Array.from(p.cellOffsets),cellSources:Array.from(p.cellSources),cellVolumes:Array.from(p.cellVolumes),faceOffsets:Array.from(p.faceOffsets),faceSources:Array.from(p.faceSources),faceAreas:Array.from(p.faceAreas)});
const cases=[{id:"split-eight",source:source([parent]),target:children,newAir:[],expected:encode(compileSparseCM12GenerationTransfer(source([parent]),target(children)))},{id:"merge-eight",source:source(children),target:[parent],newAir:[],expected:encode(compileSparseCM12GenerationTransfer(source(children),target([parent])))},{id:"explicit-new-air",source:source([{id:0,lower:[0,0,0],widths:[1,2,2],span:2}]),target:[parent],newAir:[{minimumFine:[0,0,0],maximumExclusiveFine:[2,2,2]}],expected:encode(compileSparseCM12GenerationTransfer(source([{id:0,lower:[0,0,0],widths:[1,2,2],span:2}]),target([parent]),[{minimumFine:[0,0,0],maximumExclusiveFine:[2,2,2]}]))}];
const artifact=JSON.stringify({schemaVersion:1,source:"lib/methods/adaptive-volume/sparse-cm12-generation-transfer.ts#compileSparseCM12GenerationTransfer",cases},null,2)+"\n",output=resolve(import.meta.dirname,"../../rust/core/testdata/transfer3d-golden.json");if(process.argv.includes("--check")){if(readFileSync(output,"utf8")!==artifact)throw new Error(`${output} is stale`)}else{mkdirSync(resolve(output,".."),{recursive:true});writeFileSync(output,artifact);console.log(output)}
