import type { RefinementRegionRecord, RegionSpace } from "./definition";
import { regionSnapStep_cells, snapRegionBox } from "./policy";
import type { RefinementRegionRule } from "../../core/refinement-regions";

/**
 * A region list as one query value, in **percentages of the lattice**.
 *
 * Here rather than in either host because the encoding is the one part of a
 * region that was never host-specific and was nevertheless written twice: the
 * studio spelled it out in `lib/core/url-state.ts`'s neighbourhood against
 * metres and a `Vec3`, and the 2-D lab had no address at all — which is the
 * same duplication story the record itself had, one step later. What is host
 * specific is only *what a percentage is measured against*, and that is
 * `RegionSpace.lattice`.
 *
 * Percentages and not cells, for the reason the tool exists: a region asks
 * "what does it cost to stop resolving *that part* of the domain", and that
 * question travels — the back third of a tank is the back third of any tank. A
 * percentage is also the form that survives the world-scale controls, which
 * move every extent and the cell size together and would otherwise strand every
 * box.
 *
 * The cell bounds are NOT percentages. They are counts of finest cells and mean
 * the same thing on any lattice; scaling either with the container would
 * silently change the experiment.
 *
 * Format, chosen so the value survives `URLSearchParams` unescaped (the
 * urlencoded serializer keeps alphanumerics and `*-._`, and turns the obvious
 * `,` into `%2C`):
 *
 *     regions=<min…>_<max…>_<minCells>[_<maxCells>][_<rule>]*<next>
 *
 * One field per axis for each corner, so a record is `2·axes + 1` fields with
 * two optional tails: 7, 8 or 9 in the studio and 5, 6 or 7 in the lab. The
 * optional largest cell follows the smallest one; the rule is omitted while it
 * is the only one. The reader also accepts the form without the largest cell
 * and the form whose last field is a rule, which is what makes every link
 * written before the ceiling existed still open.
 */

const REGIONS_FIELD_SEPARATOR = "_";
const REGIONS_RECORD_SEPARATOR = "*";
const DEFAULT_REGION_RULE: RefinementRegionRule = "minimum-cell-size";

export const REGIONS_QUERY_KEY = "regions";

/** Trim a percentage to the precision a sub-millimetre box actually needs. */
function percentText(value: number): string {
  return String(Number(value.toFixed(4)));
}

/** Round a requested cell-size bound down onto this host's dyadic ladder. */
function clampCellSize(
  cellSizes: readonly number[],
  fallback: number,
  requested: number,
): number {
  if (!Number.isFinite(requested)) return fallback;
  let chosen = cellSizes[0] ?? fallback;
  for (const size of cellSizes) if (size <= requested + 1e-9) chosen = size;
  return chosen;
}

export function regionsToQuery<Doc>(
  space: Pick<RegionSpace<Doc, unknown>, "axes" | "lattice" | "list">,
  doc: Doc,
): string {
  const { dimensions } = space.lattice(doc);
  const percent = (cells: readonly number[]) => Array.from({ length: space.axes },
    (_unused, axis) => {
      const extent = dimensions[axis] ?? 0;
      return percentText(extent > 0 ? (100 * (cells[axis] ?? 0)) / extent : 0);
    });
  return space.list(doc)
    .map((record) => [
      ...percent(record.min_cells),
      ...percent(record.max_cells),
      String(record.minimumCellSize_cells),
      ...(record.maximumCellSize_cells === undefined ? []
        : [String(record.maximumCellSize_cells)]),
      ...(record.rule === DEFAULT_REGION_RULE ? [] : [record.rule]),
    ].join(REGIONS_FIELD_SEPARATOR))
    .join(REGIONS_RECORD_SEPARATOR);
}

/**
 * Read regions back against *this* document's lattice.
 *
 * Re-snapped onto each region's own step rather than trusted: the percentages
 * land wherever the arithmetic puts them, and a box a fraction of a cell off the
 * lattice loses a shell of cells to partial containment — the floor would
 * quietly stop being the floor. On the document the link was written from this
 * is the identity; on any other it is what makes the box mean the same
 * instruction there.
 *
 * Ids are regenerated by position rather than carried. They exist to address a
 * region while editing it, and spending URL characters on `region-1` to
 * reconstruct `region-1` is a cost with no reader.
 *
 * Malformed records are dropped individually. A link is external input, and one
 * bad record must not cost the reader the rest of the boxes.
 */
export function regionsFromQuery<Doc>(
  space: Pick<RegionSpace<Doc, unknown>,
    "axes" | "lattice" | "capacity" | "brick_cells" | "cellSizes" | "defaultCellSize_cells">,
  doc: Doc,
  raw: string,
): RefinementRegionRecord[] {
  const lattice = space.lattice(doc);
  const clamp = (requested: number) =>
    clampCellSize(space.cellSizes, space.defaultCellSize_cells, requested);
  const corners = 2 * space.axes;
  const records: RefinementRegionRecord[] = [];
  for (const encoded of raw.split(REGIONS_RECORD_SEPARATOR)) {
    if (records.length >= space.capacity) break;
    const fields = encoded.split(REGIONS_FIELD_SEPARATOR);
    if (fields.length < corners + 1 || fields.length > corners + 3) continue;
    const numbers = fields.slice(0, corners + 1).map(Number);
    if (!numbers.every(Number.isFinite)) continue;
    const ceilingField = fields[corners + 1];
    const ceilingNumber = ceilingField === undefined || ceilingField === ""
      ? undefined : Number(ceilingField);
    const hasCeiling = ceilingNumber !== undefined && Number.isFinite(ceilingNumber);
    const rule = hasCeiling ? (fields[corners + 2] ?? DEFAULT_REGION_RULE)
      : (ceilingField ?? DEFAULT_REGION_RULE);
    if (rule !== DEFAULT_REGION_RULE) continue;
    if (fields.length === corners + 3 && !hasCeiling) continue;
    const cellsAt = (offset: number) => Array.from({ length: space.axes }, (_unused, axis) =>
      (Math.max(0, Math.min(100, numbers[offset + axis]!)) / 100)
      * (lattice.dimensions[axis] ?? 0));
    const floor = clamp(numbers[corners]!);
    const ceiling = hasCeiling ? Math.max(floor, clamp(ceilingNumber)) : undefined;
    const box = snapRegionBox(cellsAt(0), cellsAt(space.axes),
      regionSnapStep_cells({ minimumCellSize_cells: floor }, space.brick_cells), lattice);
    // A record that snapped to nothing on any axis describes no cells at all,
    // which is a box the reader cannot see and the solver cannot bind.
    if (!box.min.every((low, axis) => (box.max[axis] ?? low) > low)) continue;
    records.push({
      id: `region-${records.length + 1}`,
      rule: DEFAULT_REGION_RULE,
      minimumCellSize_cells: floor,
      ...(ceiling === undefined ? {} : { maximumCellSize_cells: ceiling }),
      min_cells: box.min,
      max_cells: box.max,
    });
  }
  return records;
}
