/** Minimal production polygoniser for globally indexed fine level-set bricks. */
export const globalFinePolygoniseShader = /* wgsl */ `
struct U{viewport:vec4f,cameraPosition:vec4f,cameraTarget:vec4f,container:vec4f,options:vec4f,gridInfo:vec4f,debug:vec4f}
struct V{position:vec4f,normal:vec4f} struct A{vertexCount:atomic<u32>,instanceCount:u32,firstVertex:u32,firstInstance:u32,activeCubeCount:atomic<u32>,vertexAllocator:atomic<u32>}
struct P{sample:vec4u,bricks:vec4u,table:vec4u,settings:vec4f,cell:vec4f,sizing:vec4f,physical:vec4f}
@group(0)@binding(0)var<uniform>u:U;@group(0)@binding(1)var<storage,read_write>out:array<V>;@group(0)@binding(2)var<storage,read_write>args:A;@group(0)@binding(3)var<storage,read_write>cubes:array<vec2u>;@group(0)@binding(4)var<storage,read>cubeValues:array<vec4f>;@group(0)@binding(5)var<uniform>p:P;@group(0)@binding(7)var<storage,read>hash:array<u32>;@group(0)@binding(8)var coarseTexture:texture_3d<f32>;@group(0)@binding(9)var<storage,read>phi:array<f32>;@group(0)@binding(11)var<storage,read>flags:array<u32>;@group(0)@binding(12)var<storage,read>metadata:array<u32>;
const X=0xffffffffu;
fn lookup(key:u32)->u32{let start=((key^(key>>16u))*0x9e3779b1u)&(p.table.x-1u);for(var n=0u;n<32u;n+=1u){if(n>=p.table.y){break;}let s=(start+n)&(p.table.x-1u);let k=hash[s*2u];if(k==key){let id=hash[s*2u+1u];if(id<p.table.z&&metadata[id*10u+1u]==key&&metadata[id*10u+2u]==p.table.w){return id;}return X;}if(k==X){return X;}}return X;}
fn coarse(q:vec3i)->f32{let f=max(1.0,p.cell.x);let x=clamp((vec3f(q)+.5)/f-.5,vec3f(0),u.gridInfo.xyz-1);let a=vec3i(floor(x));let b=min(a+1,vec3i(u.gridInfo.xyz)-1);let t=fract(x);let c0=mix(mix(textureLoad(coarseTexture,a,0).x,textureLoad(coarseTexture,vec3i(b.x,a.y,a.z),0).x,t.x),mix(textureLoad(coarseTexture,vec3i(a.x,b.y,a.z),0).x,textureLoad(coarseTexture,vec3i(b.x,b.y,a.z),0).x,t.x),t.y);let c1=mix(mix(textureLoad(coarseTexture,vec3i(a.x,a.y,b.z),0).x,textureLoad(coarseTexture,vec3i(b.x,a.y,b.z),0).x,t.x),mix(textureLoad(coarseTexture,vec3i(a.x,b.y,b.z),0).x,textureLoad(coarseTexture,b,0).x,t.x),t.y);return mix(c0,c1,t.z);}
fn sample(q:vec3i)->f32{if(any(q<vec3i(0))||any(q>=vec3i(p.sample.xyz))){return 3.402823e38;}let z=vec3u(q);let r=max(1u,p.sample.w);let b=z/r;let l=z-b*r;let key=b.x+p.bricks.x*(b.y+p.bricks.y*b.z);let id=lookup(key);if(id==X){return 3.402823e38;}let i=id*p.bricks.w+l.x+r*(l.y+r*l.z);if(i>=arrayLength(&phi)||(flags[i]&1u)==0u){return 3.402823e38;}return phi[i];}
fn field(q:vec3i)->f32{let d=vec3i(p.sample.xyz);if(q.x<=0||q.z<=0||q.x>=d.x+1||q.z>=d.z+1||q.y>=d.y+1){return 0.0;}let band=4.0*u.container.y/max(1.0,f32(p.sample.y));return clamp(.5-sample(vec3i(q.x-1,max(0,q.y-1),q.z-1))/band,0,1);}
const O=array<vec3i,8>(vec3i(0,0,0),vec3i(1,0,0),vec3i(1,1,0),vec3i(0,1,0),vec3i(0,0,1),vec3i(1,0,1),vec3i(1,1,1),vec3i(0,1,1));const T=array<vec4i,6>(vec4i(0,1,2,6),vec4i(0,2,3,6),vec4i(0,3,7,6),vec4i(0,7,4,6),vec4i(0,4,5,6),vec4i(0,5,1,6));
fn load(b:vec3i)->array<f32,8>{var v=array<f32,8>();for(var i=0;i<8;i+=1){v[i]=field(b+O[i]);}return v;}fn tc(v:array<f32,4>)->u32{var n=0u;for(var i=0;i<4;i+=1){if(v[i]>=.5){n+=1u;}}if(n==0u||n==4u){return 0u;}return select(1u,2u,n==2u);}fn count(v:ptr<function,array<f32,8>>)->u32{var n=0u;for(var i=0;i<6;i+=1){let t=T[i];n+=tc(array<f32,4>((*v)[t.x],(*v)[t.y],(*v)[t.z],(*v)[t.w]));}return n;}
fn world(q:vec3f)->vec3f{let x=clamp((q-.5)/vec3f(p.sample.xyz),vec3f(0),vec3f(1));return vec3f(-.5*u.container.x,0,-.5*u.container.z)+x*u.container.xyz;}fn norm(q:vec3f,b:vec3f,v:ptr<function,array<f32,8>>)->vec3f{let f=clamp(q-b,vec3f(0),vec3f(1));let dx=mix(mix((*v)[1]-(*v)[0],(*v)[2]-(*v)[3],f.y),mix((*v)[5]-(*v)[4],(*v)[6]-(*v)[7],f.y),f.z);let dy=mix(mix((*v)[3]-(*v)[0],(*v)[2]-(*v)[1],f.x),mix((*v)[7]-(*v)[4],(*v)[6]-(*v)[5],f.x),f.z);let z0=mix(mix((*v)[0],(*v)[1],f.x),mix((*v)[3],(*v)[2],f.x),f.y);let z1=mix(mix((*v)[4],(*v)[5],f.x),mix((*v)[7],(*v)[6],f.x),f.y);let d=vec3f(p.sample.xyz);let g=vec3f(dx*d.x/u.container.x,dy*d.y/u.container.y,(z1-z0)*d.z/u.container.z);if(length(g)>1e-5){return-normalize(g);}return vec3f(0,1,0);}fn crossv(a:vec3f,b:vec3f,va:f32,vb:f32,base:vec3f,v:ptr<function,array<f32,8>>)->V{var t=.5;if(abs(vb-va)>1e-6){t=clamp((.5-va)/(vb-va),.02,.98);}let q=mix(a,b,t);return V(vec4f(world(q),1),vec4f(norm(q,base,v),0));}
var<private>s:u32;var<private>end:u32;fn tri(a:V,b:V,c:V){let i=s;s+=3u;if(i+3u>end){return;}out[i]=a;if(dot(cross(b.position.xyz-a.position.xyz,c.position.xyz-a.position.xyz),a.normal.xyz+b.normal.xyz+c.normal.xyz)>=0){out[i+1u]=b;out[i+2u]=c;}else{out[i+1u]=c;out[i+2u]=b;}}
fn tet(q:array<vec3f,4>,v:array<f32,4>,base:vec3f,cube:ptr<function,array<f32,8>>){var ins=array<i32,4>();var outs=array<i32,4>();var ni=0;var no=0;for(var i=0;i<4;i+=1){if(v[i]>=.5){ins[ni]=i;ni+=1;}else{outs[no]=i;no+=1;}}if(ni==0||ni==4){return;}if(ni==1){let a=ins[0];tri(crossv(q[a],q[outs[0]],v[a],v[outs[0]],base,cube),crossv(q[a],q[outs[1]],v[a],v[outs[1]],base,cube),crossv(q[a],q[outs[2]],v[a],v[outs[2]],base,cube));}else if(ni==3){let a=outs[0];tri(crossv(q[a],q[ins[0]],v[a],v[ins[0]],base,cube),crossv(q[a],q[ins[2]],v[a],v[ins[2]],base,cube),crossv(q[a],q[ins[1]],v[a],v[ins[1]],base,cube));}else{let a=ins[0];let b=ins[1];let x=outs[0];let y=outs[1];let ax=crossv(q[a],q[x],v[a],v[x],base,cube);let ay=crossv(q[a],q[y],v[a],v[y],base,cube);let bx=crossv(q[b],q[x],v[b],v[x],base,cube);let by=crossv(q[b],q[y],v[b],v[y],base,cube);tri(ax,bx,by);tri(ax,by,ay);}}
fn cv(i:u32,c:u32)->f32{return cubeValues[i*2u+c/4u][c%4u];}
fn cp(base:vec3f,c:u32)->vec3f{return base+vec3f(select(0.0,1.0,c==1u||c==2u||c==5u||c==6u),select(0.0,1.0,c==2u||c==3u||c==6u||c==7u),select(0.0,1.0,c>=4u));}
fn edge(i:u32,base:vec3f,a:u32,b:u32)->vec3f{let va=cv(i,a);let vb=cv(i,b);return mix(cp(base,a),cp(base,b),clamp((.5-va)/(vb-va),.02,.98));}
fn writeTri(a:vec3f,b:vec3f,c:vec3f,n:vec3f){let first=atomicAdd(&args.vertexAllocator,3u);if(first+3u>arrayLength(&out)){return;}atomicAdd(&args.vertexCount,3u);let va=V(vec4f(world(a),1),vec4f(n,0));let vb=V(vec4f(world(b),1),vec4f(n,0));let vc=V(vec4f(world(c),1),vec4f(n,0));out[first]=va;if(dot(cross(vb.position.xyz-va.position.xyz,vc.position.xyz-va.position.xyz),n)>=0){out[first+1u]=vb;out[first+2u]=vc;}else{out[first+1u]=vc;out[first+2u]=vb;}}
fn tetCase(i:u32,base:vec3f,a:u32,b:u32,c:u32,d:u32,n:vec3f){let mask=select(0u,1u,cv(i,a)>=.5)|select(0u,2u,cv(i,b)>=.5)|select(0u,4u,cv(i,c)>=.5)|select(0u,8u,cv(i,d)>=.5);switch mask{
 case 1u,14u:{writeTri(edge(i,base,a,b),edge(i,base,a,c),edge(i,base,a,d),n);}case 2u,13u:{writeTri(edge(i,base,b,a),edge(i,base,b,d),edge(i,base,b,c),n);}case 4u,11u:{writeTri(edge(i,base,c,a),edge(i,base,c,b),edge(i,base,c,d),n);}case 8u,7u:{writeTri(edge(i,base,d,a),edge(i,base,d,c),edge(i,base,d,b),n);}
 case 3u,12u:{let ac=edge(i,base,a,c);let ad=edge(i,base,a,d);let bc=edge(i,base,b,c);let bd=edge(i,base,b,d);writeTri(ac,bc,bd,n);writeTri(ac,bd,ad,n);}case 5u,10u:{let ab=edge(i,base,a,b);let ad=edge(i,base,a,d);let cb=edge(i,base,c,b);let cd=edge(i,base,c,d);writeTri(ab,cb,cd,n);writeTri(ab,cd,ad,n);}case 6u,9u:{let ba=edge(i,base,b,a);let bd=edge(i,base,b,d);let ca=edge(i,base,c,a);let cd=edge(i,base,c,d);writeTri(ba,ca,cd,n);writeTri(ba,cd,bd,n);}default:{}}
}
fn emit(i:u32){let c=cubes[i];let base=vec3f(f32(c.x&0xffffu),f32(c.y&0xffffu),f32(c.x>>16u));let gx=.25*((cv(i,1u)+cv(i,2u)+cv(i,5u)+cv(i,6u))-(cv(i,0u)+cv(i,3u)+cv(i,4u)+cv(i,7u)));let gy=.25*((cv(i,2u)+cv(i,3u)+cv(i,6u)+cv(i,7u))-(cv(i,0u)+cv(i,1u)+cv(i,4u)+cv(i,5u)));let gz=.25*((cv(i,4u)+cv(i,5u)+cv(i,6u)+cv(i,7u))-(cv(i,0u)+cv(i,1u)+cv(i,2u)+cv(i,3u)));let dims=vec3f(p.sample.xyz);let g=vec3f(gx*dims.x/u.container.x,gy*dims.y/u.container.y,gz*dims.z/u.container.z);let n=select(vec3f(0,1,0),-normalize(g),length(g)>1e-5);tetCase(i,base,0u,1u,2u,6u,n);tetCase(i,base,0u,2u,3u,6u,n);tetCase(i,base,0u,3u,7u,6u,n);tetCase(i,base,0u,7u,4u,6u,n);tetCase(i,base,0u,4u,5u,6u,n);tetCase(i,base,0u,5u,1u,6u,n);}
override tetrahedronIndex=0u;
fn emitOneTet(i:u32){let c=cubes[i];let base=vec3f(f32(c.x&0xffffu),f32(c.y&0xffffu),f32(c.x>>16u));let gx=.25*((cv(i,1u)+cv(i,2u)+cv(i,5u)+cv(i,6u))-(cv(i,0u)+cv(i,3u)+cv(i,4u)+cv(i,7u)));let gy=.25*((cv(i,2u)+cv(i,3u)+cv(i,6u)+cv(i,7u))-(cv(i,0u)+cv(i,1u)+cv(i,4u)+cv(i,5u)));let gz=.25*((cv(i,4u)+cv(i,5u)+cv(i,6u)+cv(i,7u))-(cv(i,0u)+cv(i,1u)+cv(i,2u)+cv(i,3u)));let dims=vec3f(p.sample.xyz);let g=vec3f(gx*dims.x/u.container.x,gy*dims.y/u.container.y,gz*dims.z/u.container.z);let n=select(vec3f(0,1,0),-normalize(g),length(g)>1e-5);var a=0u;var b=1u;var z=2u;var d=6u;if(tetrahedronIndex==1u){b=2u;z=3u;}else if(tetrahedronIndex==2u){b=3u;z=7u;}else if(tetrahedronIndex==3u){b=7u;z=4u;}else if(tetrahedronIndex==4u){b=4u;z=5u;}else if(tetrahedronIndex==5u){b=5u;z=1u;}tetCase(i,base,a,b,z,d,n);}
@compute @workgroup_size(64)fn polygoniseGlobalFineMain(@builtin(global_invocation_id)g:vec3u){let n=min(atomicLoad(&args.activeCubeCount),arrayLength(&cubes));if(g.x<n){emitOneTet(g.x);}}
`;

export const globalFineCasePolygoniseShader = /* wgsl */ `
struct V{position:vec4f,normal:vec4f} struct A{vertexCount:atomic<u32>,instanceCount:u32,firstVertex:u32,firstInstance:u32,activeCubeCount:atomic<u32>,vertexAllocator:atomic<u32>}
@group(0)@binding(0)var<storage,read_write>out:array<V>;@group(0)@binding(1)var<storage,read_write>args:A;@group(0)@binding(2)var<storage,read_write>cubeValues:array<vec4f>;
@compute @workgroup_size(1)fn polygoniseGlobalFineMain(@builtin(global_invocation_id)g:vec3u){if(g.x==0u){let x=cubeValues[0].x;atomicAdd(&args.vertexCount,3u);out[0]=V(vec4f(x,0,0,1),vec4f(0,1,0,0));out[1]=V(vec4f(x+.1,0,0,1),vec4f(0,1,0,0));out[2]=V(vec4f(x,0,.1,1),vec4f(0,1,0,0));}}
`;
