/** Clean-room compact adaptive nodal-velocity reconstruction and extension. */
export const octreeLosassoAdaptiveVelocityWGSL = /* wgsl */ `
const AV_INVALID:u32=0xffffffffu;
const AV_SEEDED:u32=1u;
const AV_VALID_COMPONENTS:u32=7u;
const AV_REFRESH:u32=255u;
const AV_ERROR_GENERATION:u32=1u;
const AV_ERROR_GRAPH:u32=2u;
const AV_ERROR_PHI:u32=4u;
const AV_ERROR_FACE:u32=8u;
const AV_ERROR_CAPACITY:u32=16u;
const AV_ERROR_COVERAGE:u32=32u;
const AV_ERROR_CONSTRAINT:u32=64u;
const AV_ERROR_NONFINITE:u32=128u;
const AV_ERROR_UNRESOLVED:u32=256u;
const AV_ERROR_COMMIT:u32=512u;
const AV_DIAGNOSTIC_HEADER:u32=13u;
const AV_DIAGNOSTIC_RECORD_WORDS:u32=24u;
const AV_DIAGNOSTIC_RECORDS:u32=64u;
const AV_DIAGNOSTIC_BANK_WORDS:u32=1549u;

// Graph control ABI: generation,node count,leaf count,valid,error bits.
// A compiled face stencil is one fixed 32-byte record per node/component.  A
// component samples exactly four tangential quadrants, hence at most four
// unique faces.  metaSlots.x packs count, validity, covered finest-face
// units and coarsest span; the other words contain four slots and four u16
// area weights.  The topology-only builder may search the face directory;
// recurring reconstruction only loads this dense record and four face values.
struct AVParams{capacity:u32,bankOffset:u32,receiptBase:u32,waves:u32,reach:f32,phiStride:u32,phiOffset:u32,pad0:u32,dimensions:vec3u,maximumSpan:u32,faceCapacity:u32,directoryCapacity:u32,pad1:vec2u}
struct AVFaceStencil{metaSlots:vec4u,slotWeights:vec4u}
@group(0)@binding(0)var<uniform> avp:AVParams;

fn avFinite(v:f32)->bool{return v==v&&abs(v)<=3.402823e38;}
fn avLive(generation:u32,published:u32,errors:u32,count:u32)->u32{return select(0u,min(count,avp.capacity),generation!=0u&&published==generation&&errors==0u);}
fn avComponent(v:vec4u,c:u32)->f32{return bitcast<f32>(v[c]);}
fn avSetComponent(v:vec4u,c:u32,x:f32)->vec4u{var r=v;r[c]=bitcast<u32>(x);return r;}


// Candidate-only topology compiler. Searches and variable loops belong here,
// before the graph/face tuple is accepted; no recurring physics entry point
// binds the face geometry or its hash directory.
@group(0)@binding(91)var<storage,read>stencilGraph:array<u32>;
@group(0)@binding(92)var<storage,read>stencilNodes:array<vec4u>;
@group(0)@binding(93)var<storage,read>stencilFaceControl:array<u32>;
@group(0)@binding(94)var<storage,read>stencilFaceGeometry:array<vec4u>;
@group(0)@binding(95)var<storage,read>stencilFaceDirectory:array<vec2u>;
@group(0)@binding(96)var<storage,read_write>stencilRecords:array<AVFaceStencil>;
@group(0)@binding(97)var<storage,read_write>stencilControl:array<atomic<u32>>;
fn avStencilHash(packed:u32,q:vec3u)->u32{var h=(packed+1u)*0x9e3779b1u;h=(h^q.x)*0x85ebca6bu;h=(h^q.y)*0xc2b2ae35u;return(h^q.z)*0x27d4eb2du;}
fn avStencilExactFace(axis:u32,logSpan:u32,q:vec3u)->u32{if(arrayLength(&stencilFaceControl)<7u){return AV_INVALID;}let capacity=stencilFaceControl[6u];if(capacity==0u||(capacity&(capacity-1u))!=0u||capacity>avp.directoryCapacity||capacity>arrayLength(&stencilFaceDirectory)){return AV_INVALID;}let packed=axis|(logSpan<<2u);let hash=avStencilHash(packed,q);let mask=capacity-1u;
  for(var probe=0u;probe<32u;probe+=1u){let d=stencilFaceDirectory[(hash+probe)&mask];if(d.x==0u){return AV_INVALID;}let face=d.x-1u;if(d.y==hash&&face<min(avp.faceCapacity,stencilFaceControl[2u])&&face<arrayLength(&stencilFaceGeometry)&&all(stencilFaceGeometry[face]==vec4u(packed,q))){return face;}}return AV_INVALID;}
fn avStencilContainingFace(axis:u32,q:vec3u)->vec2u{var span=1u;var logSpan=0u;loop{var origin=q;for(var c=0u;c<3u;c+=1u){if(c!=axis){origin[c]=(origin[c]/span)*span;}}let face=avStencilExactFace(axis,logSpan,origin);if(face!=AV_INVALID){return vec2u(face,span);}if(span>avp.maximumSpan/2u){break;}span*=2u;logSpan+=1u;}return vec2u(AV_INVALID,0u);}
@compute @workgroup_size(1)fn prepareAdaptiveVelocityStencils(){
  for(var i=0u;i<8u;i+=1u){atomicStore(&stencilControl[i],0u);}var errors=0u;
  let epoch=select(0u,stencilGraph[0u],arrayLength(&stencilGraph)>=7u);let nodes=select(0u,min(stencilGraph[2u],avp.capacity),arrayLength(&stencilGraph)>=7u);
  if(epoch==0u||stencilGraph[3u]!=epoch||stencilGraph[4u]!=0u||stencilGraph[2u]>avp.capacity){errors|=AV_ERROR_GRAPH;}
  if(arrayLength(&stencilFaceControl)<7u||stencilFaceControl[0u]!=epoch||stencilFaceControl[3u]!=1u||stencilFaceControl[4u]!=0u){errors|=AV_ERROR_FACE;}
  if(arrayLength(&stencilFaceControl)>=7u){let directory=stencilFaceControl[6u];if(directory==0u||(directory&(directory-1u))!=0u||directory>avp.directoryCapacity||directory>arrayLength(&stencilFaceDirectory)||directory<2u*stencilFaceControl[2u]){errors|=AV_ERROR_CAPACITY;}}
  if(nodes>arrayLength(&stencilRecords)/3u){errors|=AV_ERROR_CAPACITY;}
  atomicStore(&stencilControl[0u],select(0u,epoch,errors==0u));atomicStore(&stencilControl[1u],select(0u,nodes,errors==0u));atomicStore(&stencilControl[2u],select(0u,stencilFaceControl[2u],errors==0u));atomicStore(&stencilControl[4u],errors);
}
fn avAddStencilFace(face:u32,area:u32,slots:ptr<function,array<u32,4>>,weights:ptr<function,array<u32,4>>,count:ptr<function,u32>,covered:ptr<function,u32>)->bool{
  if(face==AV_INVALID){return true;}var found=AV_INVALID;for(var i=0u;i<(*count);i+=1u){if((*slots)[i]==face){found=i;break;}}
  if(found==AV_INVALID){if((*count)>=4u){return false;}found=(*count);(*slots)[found]=face;(*count)+=1u;}(*weights)[found]+=area;(*covered)+=area;return (*weights)[found]<=0xffffu;
}
fn avPackStencil(count:u32,covered:u32,coarse:u32,valid:bool,slots:array<u32,4>,weights:array<u32,4>)->AVFaceStencil{
  // Current LoSASSO leaf sizes are <=32, hence even four coincident maximum-
  // span quadrant weights fit in u16 (4*32^2=4096).  Fail closed above if a
  // future topology violates that packet contract.
  let packedMeta=(count&7u)|(select(0u,1u,valid)<<3u)|((covered&0x1fffu)<<4u)|((coarse&0x3fu)<<17u);
  return AVFaceStencil(vec4u(packedMeta,slots[0],slots[1],slots[2]),
    vec4u(slots[3],(weights[0]&0xffffu)|(weights[1]<<16u),
      (weights[2]&0xffffu)|(weights[3]<<16u),0u));
}
@compute @workgroup_size(64)fn compileAdaptiveVelocityStencils(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){
  let node=id.x+id.y*n.x*64u;let live=avLive(stencilGraph[0u],stencilGraph[3u],stencilGraph[4u],stencilGraph[2u]);if(node>=live||atomicLoad(&stencilControl[4u])!=0u){return;}let constrained=node>=arrayLength(&stencilNodes)||stencilNodes[node].w!=AV_INVALID;let item=stencilNodes[node].x;let nd=avp.dimensions+vec3u(1u);let q=vec3u(item%nd.x,(item/nd.x)%nd.y,item/(nd.x*nd.y));
  // A component value at a graph node is restricted from the one MAC face
  // incident on each tangential quadrant. Weighting that face by span^2 is
  // exactly the finest-face-area average. Expanding every quadrant to the
  // largest incident span instead samples faces which do not touch this node;
  // the resulting non-local stencil changes when distant cells refine and was
  // the source of the first graded dam candidate's capacity rejection.
  for(var component=0u;component<3u;component+=1u){var slots:array<u32,4>;var weights:array<u32,4>;for(var i=0u;i<4u;i+=1u){slots[i]=AV_INVALID;weights[i]=0u;}var count=0u;var covered=0u;var coarse=1u;var valid=true;
    if(!constrained){let a=(component+1u)%3u;let b=(component+2u)%3u;
      for(var quadrant=0u;quadrant<4u;quadrant+=1u){var sample=q;sample[a]=select(select(0u,q[a]-1u,q[a]>0u),min(q[a],avp.dimensions[a]-1u),(quadrant&1u)!=0u);sample[b]=select(select(0u,q[b]-1u,q[b]>0u),min(q[b],avp.dimensions[b]-1u),(quadrant&2u)!=0u);let face=avStencilContainingFace(component,sample);if(face.x!=AV_INVALID){coarse=max(coarse,face.y);valid=avAddStencilFace(face.x,face.y*face.y,&slots,&weights,&count,&covered)&&valid;}}}
    valid=valid&&covered<=0x1fffu&&coarse<=0x3fu;if(!valid){atomicOr(&stencilControl[4u],AV_ERROR_CAPACITY);}atomicAdd(&stencilControl[5u],covered);atomicMax(&stencilControl[6u],count);stencilRecords[3u*node+component]=avPackStencil(count,covered,coarse,valid,slots,weights);
  }atomicAdd(&stencilControl[7u],1u);
}
@compute @workgroup_size(1)fn finishAdaptiveVelocityStencils(){let epoch=atomicLoad(&stencilControl[0u]);let complete=epoch!=0u&&atomicLoad(&stencilControl[4u])==0u&&atomicLoad(&stencilControl[7u])==atomicLoad(&stencilControl[1u]);atomicStore(&stencilControl[3u],select(0u,epoch,complete));}

// Topology publication is compiled directly into the inactive dense bank. No
// recurring raw graph buffer is copied into this arena.
@group(0)@binding(101)var<storage,read>topologyGraph:array<u32>;
@group(0)@binding(102)var<storage,read>topologyNodes:array<vec4u>;
@group(0)@binding(103)var<storage,read>topologyConstraints:array<u32>;
@group(0)@binding(104)var<storage,read>topologyAdjacency:array<u32>;
@group(0)@binding(105)var<storage,read>topologyLeaves:array<u32>;
@group(0)@binding(106)var<storage,read>topologyIncidentLeaves:array<u32>;
@group(0)@binding(107)var<storage,read>topologyStencils:array<AVFaceStencil>;
@group(0)@binding(108)var<storage,read_write>topologyArena:array<atomic<u32>>;
@group(0)@binding(109)var<storage,read>topologyAcceptedGraph:array<u32>;
fn avTopologyBankBase(bank:u32)->u32{return 16u+bank*atomicLoad(&topologyArena[1u]);}
fn avTopologyStore(at:u32,value:u32){atomicStore(&topologyArena[at],value);}
fn avTopologyLoad(at:u32)->u32{return atomicLoad(&topologyArena[at]);}
@group(0)@binding(110)var<storage,read>topologyStencilControl:array<u32>;
fn avTopologyCandidateBase()->u32{return avTopologyBankBase(1u-(atomicLoad(&topologyArena[2u])&1u));}
fn avTopologyError(bits:u32){atomicOr(&topologyArena[avTopologyCandidateBase()+6u],bits);}
var<workgroup> avPacketPrefix:array<u32,256>;
var<workgroup> avSpillPrefix:array<u32,256>;
@compute @workgroup_size(1)fn prepareAdaptiveVelocityTopology(){
  let base=avTopologyCandidateBase();let epoch=select(0u,topologyGraph[0u],arrayLength(&topologyGraph)>=7u);let nodes=select(0u,min(topologyGraph[2u],avp.capacity),arrayLength(&topologyGraph)>=7u);let leaves=select(0u,topologyGraph[1u],arrayLength(&topologyGraph)>=7u);var errors=0u;if(epoch==0u||topologyGraph[3u]!=epoch||topologyGraph[4u]!=0u||nodes>arrayLength(&topologyNodes)||12u*nodes>arrayLength(&topologyConstraints)||12u*nodes>arrayLength(&topologyAdjacency)||8u*nodes>arrayLength(&topologyIncidentLeaves)||16u*leaves>arrayLength(&topologyLeaves)||3u*nodes>arrayLength(&topologyStencils)){errors|=AV_ERROR_GRAPH;}avTopologyStore(base,epoch);avTopologyStore(base+1u,nodes);avTopologyStore(base+2u,0u);avTopologyStore(base+3u,0u);avTopologyStore(base+4u,leaves);avTopologyStore(base+5u,0u);avTopologyStore(base+6u,errors);}
@compute @workgroup_size(256)fn classifyAdaptiveVelocityTopologyBlocks(@builtin(workgroup_id)group:vec3u,@builtin(num_workgroups)n:vec3u,@builtin(local_invocation_id)local:vec3u){let base=avTopologyCandidateBase();let nodes=avTopologyLoad(base+1u);let block=group.x+group.y*n.x;let node=256u*block+local.x;let constrained=node<nodes&&topologyConstraints[12u*node+1u]!=0u;avPacketPrefix[local.x]=select(0u,1u,node<nodes&&!constrained);avSpillPrefix[local.x]=select(0u,1u,constrained);workgroupBarrier();for(var offset=1u;offset<256u;offset*=2u){var packetAdd=0u;var spillAdd=0u;if(local.x>=offset){packetAdd=avPacketPrefix[local.x-offset];spillAdd=avSpillPrefix[local.x-offset];}workgroupBarrier();avPacketPrefix[local.x]+=packetAdd;avSpillPrefix[local.x]+=spillAdd;workgroupBarrier();}if(local.x==255u&&block<avTopologyLoad(base+19u)){avTopologyStore(base+avTopologyLoad(base+15u)+block,avPacketPrefix[255u]);avTopologyStore(base+avTopologyLoad(base+16u)+block,avSpillPrefix[255u]);}}
@compute @workgroup_size(1)fn scanAdaptiveVelocityTopologyBlocks(){let base=avTopologyCandidateBase();let blocks=(avTopologyLoad(base+1u)+255u)/256u;var packets=0u;var spills=0u;for(var block=0u;block<blocks;block+=1u){avTopologyStore(base+avTopologyLoad(base+17u)+block,packets);avTopologyStore(base+avTopologyLoad(base+18u)+block,spills);packets+=avTopologyLoad(base+avTopologyLoad(base+15u)+block);spills+=avTopologyLoad(base+avTopologyLoad(base+16u)+block);}avTopologyStore(base+2u,packets);avTopologyStore(base+3u,spills);}
@compute @workgroup_size(256)fn indexAdaptiveVelocityTopology(@builtin(workgroup_id)group:vec3u,@builtin(num_workgroups)n:vec3u,@builtin(local_invocation_id)local:vec3u){let base=avTopologyCandidateBase();let nodes=avTopologyLoad(base+1u);let block=group.x+group.y*n.x;let node=256u*block+local.x;let constrained=node<nodes&&topologyConstraints[12u*node+1u]!=0u;avPacketPrefix[local.x]=select(0u,1u,node<nodes&&!constrained);avSpillPrefix[local.x]=select(0u,1u,constrained);workgroupBarrier();for(var step=1u;step<256u;step*=2u){var packetAdd=0u;var spillAdd=0u;if(local.x>=step){packetAdd=avPacketPrefix[local.x-step];spillAdd=avSpillPrefix[local.x-step];}workgroupBarrier();avPacketPrefix[local.x]+=packetAdd;avSpillPrefix[local.x]+=spillAdd;workgroupBarrier();}if(node<nodes){let offset=select(avTopologyLoad(base+avTopologyLoad(base+17u)+block),avTopologyLoad(base+avTopologyLoad(base+18u)+block),constrained);let rank=select(avPacketPrefix[local.x],avSpillPrefix[local.x],constrained)-1u;avTopologyStore(base+avTopologyLoad(base+7u)+node,(offset+rank)|select(0u,0x80000000u,constrained));}}
// Losasso section 6 extrapolates over nodal octree adjacency. Keep these six
// identities in graph-slot space: phi is graph-slot indexed and a hanging
// neighbour must be resolved through its constraint map exactly once. Packet
// ids are only the compact execution identity of independent destination nodes.
@compute @workgroup_size(64)fn emitAdaptiveVelocityTopology(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let node=id.x+id.y*n.x*64u;let base=avTopologyCandidateBase();let nodes=avTopologyLoad(base+1u);if(node>=nodes){return;}let map=base+avTopologyLoad(base+7u);let mapped=avTopologyLoad(map+node);if((mapped&0x80000000u)==0u){let out=base+avTopologyLoad(base+8u)+avTopologyLoad(base+13u)*mapped;avTopologyStore(out,node);avTopologyStore(out+1u,topologyNodes[node].x);for(var c=0u;c<3u;c+=1u){let s=topologyStencils[3u*node+c];let at=out+2u+8u*c;avTopologyStore(at,s.metaSlots.x);avTopologyStore(at+1u,s.metaSlots.y);avTopologyStore(at+2u,s.metaSlots.z);avTopologyStore(at+3u,s.metaSlots.w);avTopologyStore(at+4u,s.slotWeights.x);avTopologyStore(at+5u,s.slotWeights.y);avTopologyStore(at+6u,s.slotWeights.z);avTopologyStore(at+7u,s.slotWeights.w);}for(var i=0u;i<6u;i+=1u){let neighbor=topologyAdjacency[12u*node+i];var direct=AV_INVALID;if(neighbor!=AV_INVALID){if(neighbor<nodes){direct=neighbor;}else{avTopologyError(AV_ERROR_GRAPH);}}avTopologyStore(out+26u+i,direct);avTopologyStore(out+32u+i,topologyAdjacency[12u*node+6u+i]);}return;}let out=base+avTopologyLoad(base+9u)+avTopologyLoad(base+14u)*(mapped&0x7fffffffu);let count=topologyConstraints[12u*node+1u];avTopologyStore(out,node);avTopologyStore(out+1u,count);avTopologyStore(out+2u,topologyConstraints[12u*node+2u]);if(count!=2u&&count!=4u){avTopologyError(AV_ERROR_CONSTRAINT);}for(var i=0u;i<4u;i+=1u){let master=topologyConstraints[12u*node+4u+i];var masterPacket=AV_INVALID;if(master<nodes){masterPacket=avTopologyLoad(map+master);}if(i<count&&(master>=nodes||(masterPacket&0x80000000u)!=0u)){avTopologyError(AV_ERROR_CONSTRAINT);}avTopologyStore(out+3u+i,masterPacket);avTopologyStore(out+7u+i,topologyConstraints[12u*node+8u+i]);}}
@compute @workgroup_size(64)fn emitAdaptiveVelocityTopologyLeaves(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let leaf=id.x+id.y*n.x*64u;let base=avTopologyCandidateBase();if(leaf>=avTopologyLoad(base+4u)){return;}for(var i=0u;i<16u;i+=1u){avTopologyStore(base+avTopologyLoad(base+10u)+16u*leaf+i,topologyLeaves[16u*leaf+i]);}}
@compute @workgroup_size(64)fn emitAdaptiveVelocityTopologyIncidents(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let node=id.x+id.y*n.x*64u;let base=avTopologyCandidateBase();if(node>=avTopologyLoad(base+1u)){return;}for(var i=0u;i<8u;i+=1u){avTopologyStore(base+avTopologyLoad(base+11u)+8u*node+i,topologyIncidentLeaves[8u*node+i]);}}
@compute @workgroup_size(64)fn resolveAdaptiveVelocityRetained(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let base=avTopologyCandidateBase();let packet=id.x+id.y*n.x*64u;let packetCount=avTopologyLoad(base+2u);if(packet>=packetCount){return;}let packets=base+avTopologyLoad(base+8u);let packetWords=avTopologyLoad(base+13u);let item=avTopologyLoad(packets+packetWords*packet+1u);let activeBank=atomicLoad(&topologyArena[2u])&1u;let acceptedBase=avTopologyBankBase(activeBank);let acceptedValid=avTopologyLoad(acceptedBase)!=0u&&avTopologyLoad(acceptedBase+5u)==avTopologyLoad(acceptedBase)&&avTopologyLoad(acceptedBase+6u)==0u;let acceptedPackets=acceptedBase+avTopologyLoad(acceptedBase+8u);let acceptedCount=avTopologyLoad(acceptedBase+2u);let acceptedWords=avTopologyLoad(acceptedBase+13u);var found=AV_INVALID;if(acceptedValid){var low=0u;var high=acceptedCount;while(low<high){let middle=low+(high-low)/2u;let key=avTopologyLoad(acceptedPackets+acceptedWords*middle+1u);if(key<item){low=middle+1u;}else{high=middle;}}if(low<acceptedCount&&avTopologyLoad(acceptedPackets+acceptedWords*low+1u)==item){found=low;}}avTopologyStore(base+avTopologyLoad(base+12u)+packet,found);}
@compute @workgroup_size(1)fn finishAdaptiveVelocityTopology(){let base=avTopologyCandidateBase();let epoch=avTopologyLoad(base);if(arrayLength(&topologyStencilControl)<8u||topologyStencilControl[0u]!=epoch||topologyStencilControl[3u]!=epoch||topologyStencilControl[4u]!=0u){avTopologyError(AV_ERROR_FACE);}let complete=epoch!=0u&&avTopologyLoad(base+6u)==0u;avTopologyStore(base+5u,select(0u,epoch,complete));}
@compute @workgroup_size(1)fn commitAdaptiveVelocityTopology(){let activeBank=atomicLoad(&topologyArena[2u])&1u;let candidate=1u-activeBank;let base=avTopologyBankBase(candidate);let epoch=avTopologyLoad(base);let ready=epoch!=0u&&avTopologyLoad(base+5u)==epoch&&avTopologyLoad(base+6u)==0u&&arrayLength(&topologyAcceptedGraph)>=7u&&topologyAcceptedGraph[0u]==epoch&&topologyAcceptedGraph[3u]==epoch&&topologyAcceptedGraph[4u]==0u&&topologyAcceptedGraph[2u]==avTopologyLoad(base+1u);if(ready){atomicStore(&topologyArena[2u],candidate);}}

// The recurring execution ABI is deliberately three storage arenas. Topology
// is immutable for a graph epoch; readiness, epoch stamps and every indirect
// frontier packet live in one mutable arena; receipts and failure diagnostics
// live in one control arena. Dynamic face/phi/velocity fields are the only
// additional bindings.
const AV_TOPOLOGY_MAGIC:u32=0x56544f50u;
const AV_CONTROL_DIAGNOSTIC_BASE:u32=52u;
@group(0)@binding(1)var<storage,read>velocityTopologyArena:array<u32>;
@group(0)@binding(2)var<storage,read_write>velocityMutableArena:array<atomic<u32>>;
@group(0)@binding(3)var<storage,read_write>velocityControlArena:array<atomic<u32>>;
@group(0)@binding(4)var<storage,read>velocityAux0:array<u32>;
@group(0)@binding(5)var<storage,read>velocityAux1:array<u32>;
@group(0)@binding(6)var<storage,read_write>velocityField:array<vec4u>;
@group(0)@binding(7)var<storage,read_write>velocityDynamic:array<atomic<u32>>;
@group(0)@binding(8)var<storage,read>velocityStatus:array<u32>;

fn avReceiptBase(bank:u32)->u32{return select(avp.receiptBase,avp.waves,bank==1u);}
fn avBankActive(bank:u32)->bool{return(avp.bankOffset&(1u<<bank))!=0u;}
fn avCandidateField()->bool{return(avp.pad1.x&1u)!=0u;}
fn avCausalEndWave()->u32{return(avp.pad1.x>>16u)&0xffu;}
fn avTerminalWave()->u32{return(avp.pad1.x>>8u)&0xffu;}
fn avReady(packed:u32,component:u32)->u32{return(packed>>(8u*component))&0xffu;}
fn avSetReady(packed:u32,component:u32,wave:u32)->u32{let shift=8u*component;return(packed&~(0xffu<<shift))|((wave&0xffu)<<shift);}
fn avReadyMask(packed:u32)->u32{return select(0u,1u,avReady(packed,0u)!=0u)|select(0u,2u,avReady(packed,1u)!=0u)|select(0u,4u,avReady(packed,2u)!=0u);}
fn avPending(packed:u32)->bool{for(var component=0u;component<3u;component+=1u){let state=avReady(packed,component);if(state==0u||state==AV_REFRESH){return true;}}return false;}
fn avMissingPair(ready:vec2u)->bool{return(avBankActive(0u)&&avPending(ready.x))||(avBankActive(1u)&&avPending(ready.y));}
fn avTopoBase()->u32{let activeBank=velocityTopologyArena[2u]&1u;let bank=select(activeBank,1u-activeBank,avCandidateField());return 16u+bank*velocityTopologyArena[1u];}
fn avExplicitTopoBase(bank:u32)->u32{return 16u+bank*velocityTopologyArena[1u];}
fn avHeader(word:u32)->u32{return velocityTopologyArena[avTopoBase()+word];}
fn avTopoRegion(word:u32)->u32{return avTopoBase()+avHeader(word);}
fn avTopologyValid()->bool{return arrayLength(&velocityTopologyArena)>=16u&&velocityTopologyArena[0u]==AV_TOPOLOGY_MAGIC&&avHeader(0u)!=0u&&avHeader(5u)==avHeader(0u)&&avHeader(6u)==0u;}
fn avLiveTopology()->u32{return select(0u,min(avHeader(2u),avp.capacity),avTopologyValid());}
fn avTopoMap(node:u32)->u32{return velocityTopologyArena[avTopoRegion(7u)+node];}
fn avPacket(packet:u32,word:u32)->u32{return velocityTopologyArena[avTopoRegion(8u)+packet*avHeader(13u)+word];}
fn avSpill(spill:u32,word:u32)->u32{return velocityTopologyArena[avTopoRegion(9u)+spill*avHeader(14u)+word];}
fn avGraphSlot(packet:u32)->u32{return avPacket(packet,0u);}
fn avReadyAt(node:u32)->vec2u{let base=atomicLoad(&velocityMutableArena[1u])+2u*node;return vec2u(atomicLoad(&velocityMutableArena[base]),atomicLoad(&velocityMutableArena[base+1u]));}
fn avStoreReady(node:u32,value:vec2u){let base=atomicLoad(&velocityMutableArena[1u])+2u*node;atomicStore(&velocityMutableArena[base],value.x);atomicStore(&velocityMutableArena[base+1u],value.y);}
fn avControlError(bank:u32,bits:u32){atomicOr(&velocityControlArena[avReceiptBase(bank)+2u],bits);}
fn avSliceBase(slice:u32)->u32{return atomicLoad(&velocityMutableArena[3u])+slice*atomicLoad(&velocityMutableArena[4u]);}
fn avFrontierAppend(node:u32,item:u32,slice:u32){let stamp=atomicLoad(&velocityMutableArena[2u])+node;if(node>=avp.capacity||stamp>=arrayLength(&velocityMutableArena)){return;}let base=avSliceBase(slice);if(base+2u>arrayLength(&velocityMutableArena)){return;}let token=atomicLoad(&velocityMutableArena[base+1u]);let wave=(item>>24u)&0x7fu;let mark=(token<<8u)|wave;if(atomicExchange(&velocityMutableArena[stamp],mark)==mark){return;}let rank=atomicAdd(&velocityMutableArena[base],1u);if(rank>=avp.capacity||base+2u+rank>=arrayLength(&velocityMutableArena)){for(var bank=0u;bank<2u;bank+=1u){if(avBankActive(bank)){avControlError(bank,AV_ERROR_CAPACITY);}}return;}atomicStore(&velocityMutableArena[base+2u+rank],item);}

@compute @workgroup_size(1)fn prepareAdaptiveVelocity(){
  let token=atomicAdd(&velocityMutableArena[0u],1u)+1u;let slices=atomicLoad(&velocityMutableArena[5u]);for(var slice=0u;slice<slices;slice+=1u){let h=avSliceBase(slice);atomicStore(&velocityMutableArena[h],0u);atomicStore(&velocityMutableArena[h+1u],token);}
  let topologyGeneration=select(0u,avHeader(0u),avTopologyValid());let fieldGeneration=select(0u,velocityAux0[5u],arrayLength(&velocityAux0)>=7u);let acceptedValid=arrayLength(&velocityAux1)>=7u&&velocityAux1[0u]!=0u&&velocityAux1[3u]==velocityAux1[0u]&&velocityAux1[4u]==0u&&velocityAux1[5u]!=0u&&velocityAux1[6u]==velocityAux1[5u];let mode=avp.pad0&3u;let candidateCold=mode==1u&&!acceptedValid;let readyRetain=mode==2u&&fieldGeneration!=0u&&velocityAux0[6u]!=0u;let readyCold=mode==2u&&topologyGeneration==fieldGeneration&&velocityAux0[6u]==0u;let cold=candidateCold||readyCold;var errors=0u;
  if(!avTopologyValid()||arrayLength(&velocityAux0)<7u||velocityAux0[0u]!=topologyGeneration||velocityAux0[3u]!=topologyGeneration||velocityAux0[4u]!=0u||velocityAux0[2u]!=avHeader(1u)){errors|=AV_ERROR_GRAPH;}if(fieldGeneration==0u){errors|=AV_ERROR_PHI;}
  for(var bank=0u;bank<2u;bank+=1u){if(!avBankActive(bank)){continue;}let base=avReceiptBase(bank);for(var i=0u;i<12u;i+=1u){atomicStore(&velocityControlArena[base+i],0u);}let diagnosticBase=AV_CONTROL_DIAGNOSTIC_BASE+(base/12u)*AV_DIAGNOSTIC_BANK_WORDS;for(var i=0u;i<AV_DIAGNOSTIC_HEADER;i+=1u){atomicStore(&velocityControlArena[diagnosticBase+i],0u);}atomicStore(&velocityControlArena[diagnosticBase+10u],AV_INVALID);atomicStore(&velocityControlArena[base],fieldGeneration);atomicStore(&velocityControlArena[base+1u],bitcast<u32>(avp.reach));atomicStore(&velocityControlArena[base+11u],select(select(0u,2u,readyRetain),1u,cold));atomicStore(&velocityControlArena[base+2u],errors);}
}

const AV_EXACT_LIMBS:u32=36u;
fn avFloorDiv256(value:i32)->vec2i{let carry=value>>8;return vec2i(carry,value-carry*256);}
fn avExactAdd(limbs:ptr<function,array<i32,36>>,value:f32){let bits=bitcast<u32>(value);let magnitude=bits&0x7fffffffu;if(magnitude==0u){return;}let exponent=(magnitude>>23u)&0xffu;let fraction=magnitude&0x7fffffu;let significand=select(fraction,0x800000u|fraction,exponent!=0u);let shift=select(3u,exponent+2u,exponent!=0u);let first=shift>>3u;let shifted=significand<<(shift&7u);let sign=select(1,-1,(bits&0x80000000u)!=0u);for(var digit=0u;digit<4u;digit+=1u){let limb=first+digit;let byte=i32((shifted>>(digit*8u))&0xffu);if(byte!=0&&limb<AV_EXACT_LIMBS){(*limbs)[limb]+=sign*byte;}}}
fn avExactValue(input:ptr<function,array<i32,36>>)->f32{for(var limb=0u;limb+1u<AV_EXACT_LIMBS;limb+=1u){let q=avFloorDiv256((*input)[limb]);(*input)[limb]=q.y;(*input)[limb+1u]+=q.x;}let negative=(*input)[AV_EXACT_LIMBS-1u]<0;if(negative){for(var limb=0u;limb<AV_EXACT_LIMBS;limb+=1u){(*input)[limb]=-(*input)[limb];}for(var limb=0u;limb+1u<AV_EXACT_LIMBS;limb+=1u){let q=avFloorDiv256((*input)[limb]);(*input)[limb]=q.y;(*input)[limb+1u]+=q.x;}}var magnitude=0.;for(var limb=0u;limb<AV_EXACT_LIMBS;limb+=1u){magnitude+=ldexp(f32((*input)[limb]),-152+i32(8u*limb));}return select(magnitude,-magnitude,negative);}
fn avFaceBits(slot:u32,bank:u32)->u32{return select(velocityAux0[slot],velocityAux1[slot],bank==1u);}
fn avMigrationKnown(slot:u32)->bool{return slot<arrayLength(&velocityStatus)&&velocityStatus[slot]!=0u;}
fn avAccumulateFace(slot:u32,weight:u32,bank:u32,known:bool,sum:ptr<function,array<i32,36>>,covered:ptr<function,u32>,valid:ptr<function,bool>){if(weight==0u||!known){return;}let length=select(arrayLength(&velocityAux0),arrayLength(&velocityAux1),bank==1u);if(slot==AV_INVALID||slot>=length){avControlError(bank,AV_ERROR_FACE);(*valid)=false;return;}let value=bitcast<f32>(avFaceBits(slot,bank));let term=f32(weight)*value;if(!avFinite(value)||!avFinite(term)){avControlError(bank,AV_ERROR_NONFINITE);(*valid)=false;return;}avExactAdd(sum,term);(*covered)+=weight;}
fn avFinishStencil(node:u32,component:u32,bank:u32,candidate:bool)->vec2f{let at=2u+8u*component;let packedMeta=avPacket(node,at);let count=packedMeta&7u;let stencilValid=((packedMeta>>3u)&1u)!=0u;let expected=(packedMeta>>4u)&0x1fffu;if(!stencilValid||count>4u){avControlError(bank,AV_ERROR_FACE);return vec2f(0.);}var sum:array<i32,36>;var covered=0u;var valid=true;let p01=avPacket(node,at+5u);let p23=avPacket(node,at+6u);let s0=avPacket(node,at+1u);let s1=avPacket(node,at+2u);let s2=avPacket(node,at+3u);let s3=avPacket(node,at+4u);
  avAccumulateFace(s0,p01&0xffffu,bank,!candidate||avMigrationKnown(s0),&sum,&covered,&valid);avAccumulateFace(s1,p01>>16u,bank,!candidate||avMigrationKnown(s1),&sum,&covered,&valid);avAccumulateFace(s2,p23&0xffffu,bank,!candidate||avMigrationKnown(s2),&sum,&covered,&valid);avAccumulateFace(s3,p23>>16u,bank,!candidate||avMigrationKnown(s3),&sum,&covered,&valid);
  if(!valid||covered==0u){return vec2f(0.);}if(covered>expected){avControlError(bank,AV_ERROR_FACE);return vec2f(0.);}let complete=covered==expected;if(!complete){atomicAdd(&velocityControlArena[avReceiptBase(bank)+9u],1u);}let value=avExactValue(&sum)/f32(covered);if(!avFinite(value)){avControlError(bank,AV_ERROR_NONFINITE);return vec2f(0.);}atomicAdd(&velocityControlArena[avReceiptBase(bank)+8u],count);return vec2f(value,select(2.,1.,complete));}
fn avFinishAcceptedStencil(node:u32,component:u32,bank:u32)->vec2f{let at=2u+8u*component;let packedMeta=avPacket(node,at);let count=packedMeta&7u;let stencilValid=((packedMeta>>3u)&1u)!=0u;let expected=(packedMeta>>4u)&0x1fffu;if(!stencilValid||count>4u){avControlError(bank,AV_ERROR_FACE);return vec2f(0.);}var sum:array<i32,36>;var covered=0u;var valid=true;let p01=avPacket(node,at+5u);let p23=avPacket(node,at+6u);avAccumulateFace(avPacket(node,at+1u),p01&0xffffu,bank,true,&sum,&covered,&valid);avAccumulateFace(avPacket(node,at+2u),p01>>16u,bank,true,&sum,&covered,&valid);avAccumulateFace(avPacket(node,at+3u),p23&0xffffu,bank,true,&sum,&covered,&valid);avAccumulateFace(avPacket(node,at+4u),p23>>16u,bank,true,&sum,&covered,&valid);if(!valid||covered==0u){return vec2f(0.);}if(covered>expected){avControlError(bank,AV_ERROR_FACE);return vec2f(0.);}let complete=covered==expected;if(!complete){atomicAdd(&velocityControlArena[avReceiptBase(bank)+9u],1u);}let value=avExactValue(&sum)/f32(covered);if(!avFinite(value)){avControlError(bank,AV_ERROR_NONFINITE);return vec2f(0.);}atomicAdd(&velocityControlArena[avReceiptBase(bank)+8u],count);return vec2f(value,select(2.,1.,complete));}
// A normal field rebuild may retain deep-air readiness, but the paper's
// outward velocity extrapolation must be refreshed on the air side of the
// moving interface. Otherwise a fixed full-fine graph permanently preserves
// the cold zero field exactly where the next characteristic needs velocity.
fn avRefreshAdvancingAirNode(graphNode:u32)->bool{let phiAt=avp.phiStride*graphNode+avp.phiOffset;if(phiAt>=arrayLength(&velocityDynamic)){return false;}let phi=bitcast<f32>(atomicLoad(&velocityDynamic[phiAt]));let accurateReach=min(avp.reach,bitcast<f32>(avp.pad1.y));return avFinite(phi)&&phi>0.&&phi<=accurateReach;}
fn avPriorReady(mask:u32,refresh:bool)->u32{var ready=0u;for(var component=0u;component<3u;component+=1u){if((mask&(1u<<component))!=0u){ready=avSetReady(ready,component,select(1u,AV_REFRESH,refresh));}}return ready;}
fn avReconstruct(node:u32,candidate:bool){let live=avLiveTopology();if(node>=live){return;}let graphNode=avGraphSlot(node);var pair=vec2u(0u);for(var bank=0u;bank<2u;bank+=1u){if(!avBankActive(bank)){continue;}let base=avReceiptBase(bank);let mode=atomicLoad(&velocityControlArena[base+11u]);var value=velocityField[2u*graphNode+bank];var ready=0u;if(mode==1u){ready=0x00010101u;value=vec4u(0u);}else if(mode==2u){ready=select(0u,1u,(value.w&1u)!=0u)|select(0u,0x100u,(value.w&2u)!=0u)|select(0u,0x10000u,(value.w&4u)!=0u);}else{if(avp.pad0==0u){ready=select(0u,1u,(value.w&1u)!=0u)|select(0u,0x100u,(value.w&2u)!=0u)|select(0u,0x10000u,(value.w&4u)!=0u);}atomicAdd(&velocityControlArena[base+10u],1u);for(var component=0u;component<3u;component+=1u){let sample=avFinishStencil(node,component,bank,candidate);if(sample.y!=0.){value=avSetComponent(value,component,sample.x);}if(sample.y==1.){ready=avSetReady(ready,component,1u);}else{atomicAdd(&velocityControlArena[base+4u],1u);}}}value.w=avReadyMask(ready);velocityField[2u*graphNode+bank]=value;if(bank==0u){pair.x=ready;}else{pair.y=ready;}if(value.w!=0u){atomicAdd(&velocityControlArena[base+3u],1u);}}avStoreReady(node,pair);if(avMissingPair(pair)){let phiAt=avp.phiStride*graphNode+avp.phiOffset;if(phiAt<arrayLength(&velocityDynamic)){let phi=bitcast<f32>(atomicLoad(&velocityDynamic[phiAt]));if(avFinite(phi)&&abs(phi)<=min(avp.reach,bitcast<f32>(avp.pad1.y))){avFrontierAppend(node,node|(1u<<24u),0u);}}}}
fn avReconstructAccepted(node:u32){let live=avLiveTopology();if(node>=live){return;}let graphNode=avGraphSlot(node);var pair=vec2u(0u);for(var bank=0u;bank<2u;bank+=1u){if(!avBankActive(bank)){continue;}let base=avReceiptBase(bank);let mode=atomicLoad(&velocityControlArena[base+11u]);var value=velocityField[2u*graphNode+bank];var ready=0u;if(mode==1u){ready=0x00010101u;value=vec4u(0u);}else if(mode==2u){ready=select(0u,1u,(value.w&1u)!=0u)|select(0u,0x100u,(value.w&2u)!=0u)|select(0u,0x10000u,(value.w&4u)!=0u);}else{if(avp.pad0==0u){ready=avPriorReady(value.w,avRefreshAdvancingAirNode(graphNode));}atomicAdd(&velocityControlArena[base+10u],1u);for(var component=0u;component<3u;component+=1u){let sample=avFinishAcceptedStencil(node,component,bank);if(sample.y!=0.){value=avSetComponent(value,component,sample.x);}if(sample.y==1.){ready=avSetReady(ready,component,1u);}else{atomicAdd(&velocityControlArena[base+4u],1u);}}}value.w=avReadyMask(ready);velocityField[2u*graphNode+bank]=value;if(bank==0u){pair.x=ready;}else{pair.y=ready;}if(value.w!=0u){atomicAdd(&velocityControlArena[base+3u],1u);}}avStoreReady(node,pair);if(avMissingPair(pair)){let phiAt=avp.phiStride*graphNode+avp.phiOffset;if(phiAt<arrayLength(&velocityDynamic)){let phi=bitcast<f32>(atomicLoad(&velocityDynamic[phiAt]));if(avFinite(phi)&&abs(phi)<=min(avp.reach,bitcast<f32>(avp.pad1.y))){avFrontierAppend(node,node|(1u<<24u),0u);}}}}
@compute @workgroup_size(64)fn reconstructAcceptedAdaptiveVelocity(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){avReconstructAccepted(id.x+id.y*n.x*64u);}
@compute @workgroup_size(64)fn reconstructCandidateAdaptiveVelocity(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){avReconstruct(id.x+id.y*n.x*64u,true);}

@compute @workgroup_size(64)fn handoffAdaptiveVelocity(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let node=id.x+id.y*n.x*64u;if(node>=avLiveTopology()){return;}let activeBank=velocityTopologyArena[2u]&1u;let acceptedBase=avExplicitTopoBase(activeBank);let candidateBase=avExplicitTopoBase(1u-activeBank);let retainedRegion=candidateBase+velocityTopologyArena[candidateBase+12u];let acceptedPacket=velocityTopologyArena[retainedRegion+node];if(acceptedPacket==AV_INVALID){return;}let acceptedPackets=acceptedBase+velocityTopologyArena[acceptedBase+8u];let acceptedWords=velocityTopologyArena[acceptedBase+13u];let sourceNode=velocityTopologyArena[acceptedPackets+acceptedWords*acceptedPacket];let outputNode=avGraphSlot(node);var pair=avReadyAt(node);for(var bank=0u;bank<2u;bank+=1u){if(!avBankActive(bank)){continue;}let sourceAt=4u*(2u*sourceNode+bank);if(sourceAt+3u>=arrayLength(&velocityAux0)){continue;}let source=vec4u(velocityAux0[sourceAt],velocityAux0[sourceAt+1u],velocityAux0[sourceAt+2u],velocityAux0[sourceAt+3u]);var output=velocityField[2u*outputNode+bank];var ready=select(pair.x,pair.y,bank==1u);for(var component=0u;component<3u;component+=1u){let bit=1u<<component;if((source.w&bit)!=0u&&avFinite(avComponent(source,component))){output=avSetComponent(output,component,avComponent(source,component));ready=avSetReady(ready,component,1u);}}output.w=avReadyMask(ready);velocityField[2u*outputNode+bank]=output;if(bank==0u){pair.x=ready;}else{pair.y=ready;}}avStoreReady(node,pair);}

fn avCanonicalSum(values:ptr<function,array<f32,6>>,count:u32)->f32{for(var i=1u;i<count;i+=1u){let value=(*values)[i];let magnitude=abs(value);var j=i;while(j>0u&&abs((*values)[j-1u])>magnitude){(*values)[j]=(*values)[j-1u];j-=1u;}(*values)[j]=value;}var sum=0.;for(var i=0u;i<count;i+=1u){sum+=(*values)[i];}return sum;}
fn avAdjacency(slot:u32,index:u32)->u32{return avPacket(slot,26u+index);}
fn avSeedError(){for(var bank=0u;bank<2u;bank+=1u){if(avBankActive(bank)){avControlError(bank,AV_ERROR_CONSTRAINT);}}}
fn avSeedAppendPacket(packet:u32){if(packet<avLiveTopology()&&avMissingPair(avReadyAt(packet))){avFrontierAppend(packet,packet|0x80000000u|(avCausalEndWave()<<24u),avCausalEndWave());}}
fn avSeedAppendMapped(mapped:u32){if(mapped==AV_INVALID){return;}if((mapped&0x80000000u)==0u){avSeedAppendPacket(mapped);return;}let spill=mapped&0x7fffffffu;if(spill>=avHeader(3u)){avSeedError();return;}let count=avSpill(spill,1u);if(count!=2u&&count!=4u){avSeedError();return;}for(var i=0u;i<count;i+=1u){avSeedAppendPacket(avSpill(spill,3u+i));}}
fn avSeedAppendGraph(slot:u32){if(slot<avHeader(1u)){avSeedAppendMapped(avTopoMap(slot));}}
fn avSeedAppendMaster(packet:u32){if(packet>=avLiveTopology()){return;}avSeedAppendPacket(packet);for(var d=0u;d<6u;d+=1u){avSeedAppendGraph(avAdjacency(packet,d));}}
fn avSeedAppendIndependent(slot:u32){if(slot>=avHeader(1u)){return;}let mapped=avTopoMap(slot);if((mapped&0x80000000u)==0u){avSeedAppendMaster(mapped);return;}let spill=mapped&0x7fffffffu;let count=avSpill(spill,1u);if(count!=2u&&count!=4u){avSeedError();return;}for(var i=0u;i<count;i+=1u){avSeedAppendMaster(avSpill(spill,3u+i));}}
fn avSeedLeaf(leaf:u32){if(leaf>=avHeader(4u)){return;}let at=avTopoRegion(10u)+16u*leaf;if((velocityTopologyArena[at+4u]&1u)==0u){return;}for(var i=0u;i<8u;i+=1u){avSeedAppendIndependent(velocityTopologyArena[at+8u+i]);}}
@compute @workgroup_size(64)fn seedAdaptiveVelocityFrontier(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let node=id.x+id.y*n.x*64u;if(node>=avHeader(1u)||node>=arrayLength(&velocityAux0)||velocityAux0[node]==0u){return;}avSeedAppendIndependent(node);let incident=avTopoRegion(11u)+8u*node;for(var i=0u;i<8u;i+=1u){avSeedLeaf(velocityTopologyArena[incident+i]);}}

fn avFrontierDonor(slot:u32,component:u32,bank:u32,wave:u32,live:u32)->vec2f{if(slot>=avHeader(1u)){return vec2f(0.);}let mapped=avTopoMap(slot);if((mapped&0x80000000u)==0u){if(mapped>=live){return vec2f(0.);}let packed=select(avReadyAt(mapped).x,avReadyAt(mapped).y,bank==1u);let ready=avReady(packed,component);if(ready==0u||ready==AV_REFRESH||ready>wave){return vec2f(0.);}let value=avComponent(velocityField[2u*avGraphSlot(mapped)+bank],component);return vec2f(value,select(0.,1.,avFinite(value)));}let spill=mapped&0x7fffffffu;let count=avSpill(spill,1u);let denominator=avSpill(spill,2u);if((count!=2u&&count!=4u)||denominator==0u){avControlError(bank,AV_ERROR_CONSTRAINT);return vec2f(0.);}var terms:array<f32,6>;var weights:array<f32,6>;var valid=true;for(var i=0u;i<count;i+=1u){let master=avSpill(spill,3u+i);if(master>=live){valid=false;continue;}let packed=select(avReadyAt(master).x,avReadyAt(master).y,bank==1u);let weight=f32(avSpill(spill,7u+i))/f32(denominator);weights[i]=weight;terms[i]=weight*avComponent(velocityField[2u*avGraphSlot(master)+bank],component);let state=avReady(packed,component);valid=valid&&state!=0u&&state!=AV_REFRESH&&state<=wave;}let value=avCanonicalSum(&terms,count);let denominatorSum=avCanonicalSum(&weights,count);return vec2f(value,select(0.,1.,valid&&avFinite(value)&&abs(denominatorSum-1.)<=.00001));}
fn avSolveFrontier(node:u32,wave:u32,harmonic:bool,live:u32){var pair=avReadyAt(node);let graphNode=avGraphSlot(node);let phiAt=avp.phiStride*graphNode+avp.phiOffset;if(phiAt>=arrayLength(&velocityDynamic)){return;}let nodePhi=bitcast<f32>(atomicLoad(&velocityDynamic[phiAt]));if(!avFinite(nodePhi)){for(var bank=0u;bank<2u;bank+=1u){if(avBankActive(bank)){avControlError(bank,AV_ERROR_NONFINITE);}}return;}if(!harmonic&&abs(nodePhi)>min(avp.reach,bitcast<f32>(avp.pad1.y))){return;}for(var bank=0u;bank<2u;bank+=1u){if(!avBankActive(bank)){continue;}var packed=select(pair.x,pair.y,bank==1u);var value=velocityField[2u*graphNode+bank];for(var component=0u;component<3u;component+=1u){let ownState=avReady(packed,component);if(ownState!=0u&&ownState!=AV_REFRESH){continue;}var terms:array<f32,6>;var weights:array<f32,6>;var count=0u;for(var direction=0u;direction<6u;direction+=1u){let donor=avAdjacency(node,direction);if(donor==AV_INVALID||donor>=avHeader(1u)){continue;}let distance=bitcast<f32>(avAdjacency(node,direction+6u));let donorPhiAt=avp.phiStride*donor+avp.phiOffset;if(distance<=0.||!avFinite(distance)||donorPhiAt>=arrayLength(&velocityDynamic)){continue;}let donorPhi=bitcast<f32>(atomicLoad(&velocityDynamic[donorPhiAt]));if(!harmonic&&(!avFinite(donorPhi)||abs(donorPhi)>abs(nodePhi))){continue;}let sample=avFrontierDonor(donor,component,bank,wave,live);if(sample.y==0.){continue;}let weight=1./distance;terms[count]=weight*sample.x;weights[count]=weight;count+=1u;}if(count>0u){let numerator=avCanonicalSum(&terms,count);let denominator=avCanonicalSum(&weights,count);if(denominator>0.&&avFinite(numerator)&&avFinite(denominator)){value=avSetComponent(value,component,numerator/denominator);packed=avSetReady(packed,component,wave+1u);}}}value.w=avReadyMask(packed);velocityField[2u*graphNode+bank]=value;if(bank==0u){pair.x=packed;}else{pair.y=packed;}}avStoreReady(node,pair);}
fn avFrontierAppendNode(slot:u32,item:u32,slice:u32,live:u32){if(slot>=avHeader(1u)){return;}let mapped=avTopoMap(slot);if((mapped&0x80000000u)==0u){if(mapped<live){avFrontierAppend(mapped,item|mapped,slice);}return;}let spill=mapped&0x7fffffffu;let count=avSpill(spill,1u);if(count==2u||count==4u){for(var i=0u;i<count;i+=1u){let master=avSpill(spill,3u+i);if(master<live){avFrontierAppend(master,item|master,slice);}}}}
fn avPropagateFrontierWork(work:u32,input:u32,live:u32){let item=atomicLoad(&velocityMutableArena[input+2u+work]);let node=item&0x00ffffffu;if(node>=live){return;}let wave=(item>>24u)&0x7fu;let harmonic=(item&0x80000000u)!=0u;avSolveFrontier(node,wave,harmonic,live);if(!avMissingPair(avReadyAt(node))){return;}let next=(item&0x80000000u)|((wave+1u)<<24u);let outputSlice=select(wave,wave+1u,harmonic);avFrontierAppend(node,next|node,outputSlice);if(harmonic){for(var d=0u;d<6u;d+=1u){let neighbor=avAdjacency(node,d);if(neighbor!=AV_INVALID){avFrontierAppendNode(neighbor,next,outputSlice,live);}}}}
@compute @workgroup_size(64)fn propagateAdaptiveVelocityFrontier(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let lane=id.x+id.y*n.x*64u;let workers=max(1u,n.x*n.y*64u);let input=avSliceBase(avp.pad0>>8u);let count=min(atomicLoad(&velocityMutableArena[input]),avp.capacity);let live=avLiveTopology();for(var work=lane;work<count;work+=workers){avPropagateFrontierWork(work,input,live);}}

@compute @workgroup_size(64)fn constrainAdaptiveVelocity(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let graphNode=id.x+id.y*n.x*64u;if(graphNode>=avHeader(1u)){return;}let mapped=avTopoMap(graphNode);if((mapped&0x80000000u)==0u){return;}let spill=mapped&0x7fffffffu;let count=avSpill(spill,1u);let denominator=avSpill(spill,2u);let live=avLiveTopology();for(var bank=0u;bank<2u;bank+=1u){if(!avBankActive(bank)){continue;}if((count!=2u&&count!=4u)||denominator==0u){avControlError(bank,AV_ERROR_CONSTRAINT);continue;}var value=vec4u(0u);var mask=0u;for(var component=0u;component<3u;component+=1u){var terms:array<f32,6>;var valid=true;for(var i=0u;i<count;i+=1u){let master=avSpill(spill,3u+i);if(master>=live){valid=false;continue;}let packed=select(avReadyAt(master).x,avReadyAt(master).y,bank==1u);let weight=f32(avSpill(spill,7u+i))/f32(denominator);terms[i]=weight*avComponent(velocityField[2u*avGraphSlot(master)+bank],component);let state=avReady(packed,component);valid=valid&&state!=0u&&state!=AV_REFRESH;}let sum=avCanonicalSum(&terms,count);if(valid&&avFinite(sum)){value=avSetComponent(value,component,sum);mask|=1u<<component;}}value.w=mask;velocityField[2u*graphNode+bank]=value;if(mask==7u){atomicAdd(&velocityControlArena[avReceiptBase(bank)+6u],1u);}}}

@compute @workgroup_size(64)fn finalizeAdaptiveVelocity(@builtin(global_invocation_id)id:vec3u,@builtin(num_workgroups)n:vec3u){let node=id.x+id.y*n.x*64u;let live=avLiveTopology();if(node>=live){return;}let graphNode=avGraphSlot(node);let terminalHeader=avSliceBase(avTerminalWave());let token=atomicLoad(&velocityMutableArena[terminalHeader+1u]);let mark=(token<<8u)|avTerminalWave();let stamp=atomicLoad(&velocityMutableArena[2u])+node;let unresolved=atomicLoad(&velocityMutableArena[stamp])==mark;for(var bank=0u;bank<2u;bank+=1u){if(!avBankActive(bank)){continue;}let packed=select(avReadyAt(node).x,avReadyAt(node).y,bank==1u);let mask=avReadyMask(packed);var value=velocityField[2u*graphNode+bank];value.w=mask;velocityField[2u*graphNode+bank]=value;let old=atomicLoad(&velocityDynamic[graphNode]);let shift=4u*bank;atomicStore(&velocityDynamic[graphNode],(old&~(7u<<shift))|(mask<<shift));if(mask==7u){atomicAdd(&velocityControlArena[avReceiptBase(bank)+6u],1u);}else if(unresolved){let base=avReceiptBase(bank);atomicAdd(&velocityControlArena[base+5u],1u);atomicOr(&velocityControlArena[base+2u],AV_ERROR_UNRESOLVED);let diagnosticBase=AV_CONTROL_DIAGNOSTIC_BASE+(base/12u)*AV_DIAGNOSTIC_BANK_WORDS;atomicAdd(&velocityControlArena[diagnosticBase],1u);}}}

@group(0)@binding(51)var<storage,read_write>finishGraph:array<atomic<u32>>;
@group(0)@binding(52)var<storage,read_write>finishLeafLocator:array<atomic<u32>>;
@compute @workgroup_size(1)fn finishAdaptiveVelocity(){let generation=atomicLoad(&finishGraph[5u]);for(var bank=0u;bank<2u;bank+=1u){if(avBankActive(bank)){let base=avReceiptBase(bank);atomicStore(&velocityControlArena[base+7u],select(0u,1u,atomicLoad(&velocityControlArena[base+2u])==0u));}}let a=avp.receiptBase;let p=avp.waves;let both=generation!=0u&&atomicLoad(&velocityControlArena[a])==generation&&atomicLoad(&velocityControlArena[p])==generation&&atomicLoad(&velocityControlArena[a+7u])==1u&&atomicLoad(&velocityControlArena[p+7u])==1u;let published=select(0u,generation,both);atomicStore(&finishGraph[6u],published);atomicStore(&finishLeafLocator[13u],published);atomicStore(&finishLeafLocator[14u],published);}
`;

/**
 * Four-binding containing-leaf sampler for LosassoSurfaceGraphBankSource.
 * It deliberately uses the caller's dynamics parameters for dimensions,
 * domain origin and finest physical cell widths.
 */
export function octreeLosassoAdaptiveVelocitySamplerWGSL(bindings: {
  readonly leaves: number; readonly ownerArena: number; readonly leafLocator: number;
  readonly velocityArena: number;
} = { leaves: 12, ownerArena: 13, leafLocator: 14, velocityArena: 15 }): string {
  return /* wgsl */ `
const ADAPTIVE_VELOCITY_INVALID=0xffffffffu;
struct AdaptiveVelocitySample{value:vec3f,lower:vec3f,upper:vec3f,valid:bool}
@group(0)@binding(${bindings.leaves})var<storage,read>adaptiveVelocityLeaves:array<vec4u>;
@group(0)@binding(${bindings.ownerArena})var<storage,read>adaptiveVelocityOwnerArena:array<u32>;
@group(0)@binding(${bindings.leafLocator})var<storage,read>adaptiveVelocityLeafLocator:array<u32>;
@group(0)@binding(${bindings.velocityArena})var<storage,read>adaptiveVelocityArena:array<vec4u>;
// Fixed two-level lookup: the owner authority supplies a direct logical-brick
// directory, and the graph transaction supplies one leaf slot per resident
// physical-page cell. No recurring search or topology-dependent loop exists.
fn adaptiveVelocityAuthorityValid(dims:vec3u)->bool{if(arrayLength(&adaptiveVelocityLeafLocator)<16u||arrayLength(&adaptiveVelocityOwnerArena)<11u){return false;}let epoch=adaptiveVelocityLeafLocator[1u];let pages=adaptiveVelocityLeafLocator[2u];let support=adaptiveVelocityLeafLocator[3u];let leaves=adaptiveVelocityLeafLocator[4u];let nodes=adaptiveVelocityLeafLocator[5u];let capacity=adaptiveVelocityLeafLocator[8u];let logicalCount=adaptiveVelocityLeafLocator[9u];let payload=adaptiveVelocityLeafLocator[11u];let table=adaptiveVelocityLeafLocator[15u];let brickDims=(dims+vec3u(7u))/8u;return adaptiveVelocityLeafLocator[0u]==0x4c4f4341u&&epoch!=0u&&adaptiveVelocityLeafLocator[6u]==epoch&&adaptiveVelocityLeafLocator[7u]==0u&&pages<=capacity&&support==pages*512u&&leaves!=0u&&4u*leaves<=arrayLength(&adaptiveVelocityLeaves)&&nodes!=0u&&2u*nodes<=arrayLength(&adaptiveVelocityArena)&&logicalCount==brickDims.x*brickDims.y*brickDims.z&&payload>=16u&&payload+capacity*512u<=arrayLength(&adaptiveVelocityLeafLocator)&&adaptiveVelocityLeafLocator[13u]!=0u&&adaptiveVelocityLeafLocator[14u]==adaptiveVelocityLeafLocator[13u]&&table<=1u;}
fn adaptiveLocatedCell(cell:vec3u,dims:vec3u)->u32{let leaves=adaptiveVelocityLeafLocator[4u];let capacity=adaptiveVelocityLeafLocator[8u];let logicalCount=adaptiveVelocityLeafLocator[9u];let directoryA=adaptiveVelocityLeafLocator[10u];let payload=adaptiveVelocityLeafLocator[11u];let table=adaptiveVelocityLeafLocator[15u];let brickDims=(dims+vec3u(7u))/8u;let brick=cell/8u;let logical=brick.x+brickDims.x*(brick.y+brickDims.y*brick.z);if(logical>=logicalCount){return ADAPTIVE_VELOCITY_INVALID;}let directory=directoryA+table*logicalCount+logical;if(directory>=arrayLength(&adaptiveVelocityOwnerArena)){return ADAPTIVE_VELOCITY_INVALID;}let page=adaptiveVelocityOwnerArena[directory];if(page==0u||page==ADAPTIVE_VELOCITY_INVALID||page>capacity){return ADAPTIVE_VELOCITY_INVALID;}let local=(cell.x&7u)+8u*(cell.y&7u)+64u*(cell.z&7u);let at=payload+(page-1u)*512u+local;if(at>=arrayLength(&adaptiveVelocityLeafLocator)){return ADAPTIVE_VELOCITY_INVALID;}let slot=adaptiveVelocityLeafLocator[at];if(slot>=leaves){return ADAPTIVE_VELOCITY_INVALID;}let record=4u*slot;if(record+3u>=arrayLength(&adaptiveVelocityLeaves)){return ADAPTIVE_VELOCITY_INVALID;}let header=adaptiveVelocityLeaves[record];let info=adaptiveVelocityLeaves[record+1u];if((info.x&1u)==0u||info.y!=slot||header.w==0u||any(cell<header.xyz)||any(cell>=header.xyz+vec3u(header.w))){return ADAPTIVE_VELOCITY_INVALID;}return slot;}
fn adaptiveSampleProduct3(value:vec3f)->f32{let lowPair=min(value.x,value.y);let highPair=max(value.x,value.y);let low=min(lowPair,value.z);let high=max(highPair,value.z);let middle=max(lowPair,min(highPair,value.z));return(low*middle)*high;}
fn adaptiveSampleFloorDiv256(value:i32)->vec2i{let carry=value>>8;return vec2i(carry,value-carry*256);}
fn adaptiveSampleExactAdd(limbs:ptr<function,array<i32,36>>,value:f32){let bits=bitcast<u32>(value);let magnitude=bits&0x7fffffffu;if(magnitude==0u){return;}let exponent=(magnitude>>23u)&0xffu;let fraction=magnitude&0x7fffffu;let significand=select(fraction,0x800000u|fraction,exponent!=0u);let shift=select(3u,exponent+2u,exponent!=0u);let first=shift>>3u;let shifted=significand<<(shift&7u);let sign=select(1,-1,(bits&0x80000000u)!=0u);for(var digit=0u;digit<4u;digit+=1u){let limb=first+digit;let byte=i32((shifted>>(digit*8u))&0xffu);if(byte!=0&&limb<36u){(*limbs)[limb]+=sign*byte;}}}
fn adaptiveSampleExactValue(input:ptr<function,array<i32,36>>)->f32{for(var limb=0u;limb+1u<36u;limb+=1u){let n=adaptiveSampleFloorDiv256((*input)[limb]);(*input)[limb]=n.y;(*input)[limb+1u]+=n.x;}let negative=(*input)[35u]<0;if(negative){for(var limb=0u;limb<36u;limb+=1u){(*input)[limb]=-(*input)[limb];}for(var limb=0u;limb+1u<36u;limb+=1u){let n=adaptiveSampleFloorDiv256((*input)[limb]);(*input)[limb]=n.y;(*input)[limb+1u]+=n.x;}}var magnitude=0.;for(var limb=0u;limb<36u;limb+=1u){magnitude+=ldexp(f32((*input)[limb]),-152+i32(8u*limb));}return select(magnitude,-magnitude,negative);}
fn adaptiveAccumulateSample(slot:u32,weight:f32,fieldBank:u32,nodeCapacity:u32,x:ptr<function,array<i32,36>>,y:ptr<function,array<i32,36>>,z:ptr<function,array<i32,36>>,lower:ptr<function,vec3f>,upper:ptr<function,vec3f>,valid:ptr<function,bool>){if(weight==0.){return;}let record=2u*slot+fieldBank;if(slot>=nodeCapacity||fieldBank>1u||record>=arrayLength(&adaptiveVelocityArena)){(*valid)=false;return;}let packed=adaptiveVelocityArena[record];let value=vec3f(bitcast<f32>(packed.x),bitcast<f32>(packed.y),bitcast<f32>(packed.z));if((packed.w&7u)!=7u||any(value!=value)){(*valid)=false;return;}adaptiveSampleExactAdd(x,weight*value.x);adaptiveSampleExactAdd(y,weight*value.y);adaptiveSampleExactAdd(z,weight*value.z);(*lower)=min((*lower),value);(*upper)=max((*upper),value);}
fn adaptiveSampleLeaf(grid:vec3f,leaf:u32,fieldBank:u32)->AdaptiveVelocitySample{let at=4u*leaf;let header=adaptiveVelocityLeaves[at];let fraction=clamp((grid-vec3f(header.xyz))/f32(header.w),vec3f(0.),vec3f(1.));let lo=vec3f(1.)-fraction;let nodeCapacity=adaptiveVelocityLeafLocator[5u];let slots0=adaptiveVelocityLeaves[at+2u];let slots1=adaptiveVelocityLeaves[at+3u];var x:array<i32,36>;var y:array<i32,36>;var z:array<i32,36>;var lower=vec3f(3.402823e38);var upper=vec3f(-3.402823e38);var valid=true;
  adaptiveAccumulateSample(slots0.x,adaptiveSampleProduct3(vec3f(lo.x,lo.y,lo.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);adaptiveAccumulateSample(slots0.y,adaptiveSampleProduct3(vec3f(fraction.x,lo.y,lo.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);adaptiveAccumulateSample(slots0.z,adaptiveSampleProduct3(vec3f(lo.x,fraction.y,lo.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);adaptiveAccumulateSample(slots0.w,adaptiveSampleProduct3(vec3f(fraction.x,fraction.y,lo.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);adaptiveAccumulateSample(slots1.x,adaptiveSampleProduct3(vec3f(lo.x,lo.y,fraction.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);adaptiveAccumulateSample(slots1.y,adaptiveSampleProduct3(vec3f(fraction.x,lo.y,fraction.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);adaptiveAccumulateSample(slots1.z,adaptiveSampleProduct3(vec3f(lo.x,fraction.y,fraction.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);adaptiveAccumulateSample(slots1.w,adaptiveSampleProduct3(vec3f(fraction.x,fraction.y,fraction.z)),fieldBank,nodeCapacity,&x,&y,&z,&lower,&upper,&valid);
  if(!valid){return AdaptiveVelocitySample(vec3f(0.),vec3f(0.),vec3f(0.),false);}return AdaptiveVelocitySample(vec3f(adaptiveSampleExactValue(&x),adaptiveSampleExactValue(&y),adaptiveSampleExactValue(&z)),lower,upper,true);}
fn sampleAdaptiveVelocityGrid(gridValue:vec3f,fieldBank:u32)->AdaptiveVelocitySample{let dims=params.dimensionsMaximumLeaf.xyz;let grid=clamp(gridValue,vec3f(0.),vec3f(dims));if(!adaptiveVelocityAuthorityValid(dims)){return AdaptiveVelocitySample(vec3f(0.),vec3f(0.),vec3f(0.),false);}let base=vec3u(min(floor(grid),vec3f(dims)-vec3f(1.)));let leaf=adaptiveLocatedCell(base,dims);if(leaf==ADAPTIVE_VELOCITY_INVALID){return AdaptiveVelocitySample(vec3f(0.),vec3f(0.),vec3f(0.),false);}return adaptiveSampleLeaf(grid,leaf,fieldBank);}
fn sampleAdaptiveVelocity(position:vec3f,fieldBank:u32)->AdaptiveVelocitySample{return sampleAdaptiveVelocityGrid((position-params.domainOriginDt.xyz)/params.cellWidthDensity.xyz,fieldBank);}
`;
}
