/**
 * Compact surface-mass authority for the adaptive Losasso graph.
 *
 * `surfaceMass` is an integral (m^3 for an unobstructed leaf), not physical
 * density.  The corresponding Chentanez--Mueller surface density is
 * rho=surfaceMass/leafVolume. The physical surface-density and conservative
 * sharpening threshold is exactly .5. A one-way nodal compatibility cache
 * uses that same topology-invariant threshold; its measured volume is
 * diagnostic only. Every transport record belongs to exactly one donor. The
 * eight tensor weights are normalized, then strict-2:1 face/edge/corner flux
 * is split over twenty equal-area records with all indivisible fixed-point
 * remainder retained by the donor, so every sparse column sums exactly to one.
 */
export const octreeLosassoAdaptiveMassWGSL = /* wgsl */ `
const MAGIC:u32=0x414d4153u;const INVALID:u32=0xffffffffu;
const SURFACE_RHO_ISO:f32=.5;const SHARPEN_RHO_THRESHOLD:f32=.5;
const ERR_GRAPH:u32=1u;const ERR_FINITE:u32=2u;const ERR_TRANSFER:u32=4u;const ERR_CAPACITY:u32=8u;const ERR_OVERFLOW:u32=16u;
struct Params{dimsMax:vec4u,originCell:vec4f,limits:vec4u,numerics:vec4f,policy:vec4u}
struct Leaf{originSpan:vec4u,info:vec4u,corners0:vec4u,corners1:vec4u}
struct Directory{cell:u32,size:u32,slot:u32,flags:u32}
struct Constraint{header:vec4u,masters:vec4u,numerators:vec4u}
struct Transfer{donor:u32,recipient:u32,weightBits:u32,flags:u32}
@group(0)@binding(0)var<uniform>p:Params;
@group(0)@binding(1)var<storage,read_write>graph:array<u32>;
@group(0)@binding(2)var<storage,read>leaves:array<Leaf>;
@group(0)@binding(3)var<storage,read>directory:array<Directory>;
@group(0)@binding(4)var<storage,read>nodes:array<vec4u>;
@group(0)@binding(5)var<storage,read>constraints:array<Constraint>;
@group(0)@binding(6)var<storage,read>incidentLeaves:array<u32>;
@group(0)@binding(7)var<storage,read>rowToLeaf:array<u32>;
@group(0)@binding(8)var<storage,read_write>phi:array<vec2f>;
@group(0)@binding(9)var<storage,read>velocity:array<vec4f>;
@group(0)@binding(10)var<storage,read_write>mass:array<f32>;
@group(0)@binding(11)var<storage,read_write>compression:array<f32>;
@group(0)@binding(12)var<storage,read>sourceGraph:array<u32>;
@group(0)@binding(13)var<storage,read>sourceLeaves:array<Leaf>;
@group(0)@binding(14)var<storage,read>sourceMass:array<f32>;
@group(0)@binding(15)var<storage,read>sourceCompression:array<f32>;
@group(0)@binding(16)var<storage,read_write>nextMass:array<atomic<u32>>;
@group(0)@binding(17)var<storage,read_write>nextCompressionMass:array<atomic<u32>>;
@group(0)@binding(18)var<storage,read_write>transfers:array<Transfer>;
@group(0)@binding(19)var<storage,read_write>control:array<atomic<u32>>;
@group(0)@binding(20)var<storage,read_write>receipts:array<atomic<u32>>;
@group(0)@binding(21)var<storage,read_write>leafRhoPhi:array<vec4f>;
@group(0)@binding(22)var<storage,read_write>rowRho:array<vec4f>;
@group(0)@binding(23)var<storage,read_write>rowPhi:array<vec4u>;
// [rho=.5, rho=.5, rho=.5, target units, measured units, measurement count,
//  error bits, published rho=.5]. Volume units are 1/65536 finest cell.
@group(0)@binding(24)var<storage,read_write>reconstruction:array<atomic<u32>>;
fn finite(v:f32)->bool{return v==v&&abs(v)<3.402823e38;}
fn leafCount()->u32{return min(min(graph[1],p.limits.x),arrayLength(&leaves));}
fn sourceLeafCount()->u32{return min(sourceGraph[1],min(arrayLength(&sourceLeaves),arrayLength(&sourceMass)));}
fn nodeCount()->u32{return min(graph[2],min(p.limits.y,arrayLength(&phi)));}
fn rowCount()->u32{return min(graph[28],min(p.limits.z,arrayLength(&rowToLeaf)));}
fn corner(r:Leaf,c:u32)->u32{if(c<4u){return r.corners0[c];}return r.corners1[c-4u];}
fn volume(r:Leaf)->f32{let w=f32(r.originSpan.w)*p.originCell.w;return w*w*w;}
fn rhoOf(i:u32)->f32{if(i>=leafCount()){return 0.;}return mass[i]/max(volume(leaves[i]),1e-30);}
fn massToUnits(value:f32)->u32{let raw=value*p.numerics.w;if(!finite(raw)||raw<0.){atomicOr(&control[12],ERR_FINITE);return 0u;}if(raw>4294967040.){atomicOr(&control[12],ERR_OVERFLOW);return 0u;}return u32(floor(raw+.5));}
fn unitsToMass(value:u32)->f32{return f32(value)*p.numerics.z;}
fn ordered8(input:array<f32,8>)->f32{var v=input;for(var i=0u;i<8u;i+=1u){for(var j=i+1u;j<8u;j+=1u){if(v[j]<v[i]||(v[j]==v[i]&&bitcast<u32>(v[j])<bitcast<u32>(v[i]))){let t=v[i];v[i]=v[j];v[j]=t;}}}return ((v[0]+v[1])+(v[2]+v[3]))+((v[4]+v[5])+(v[6]+v[7]));}
fn ordered27(input:array<f32,27>)->f32{var v=input;for(var i=0u;i<27u;i+=1u){for(var j=i+1u;j<27u;j+=1u){if(v[j]<v[i]||(v[j]==v[i]&&bitcast<u32>(v[j])<bitcast<u32>(v[i]))){let t=v[i];v[i]=v[j];v[j]=t;}}}var sum=0.;for(var i=0u;i<27u;i+=1u){sum+=v[i];}return sum;}
fn trilerp(v:array<f32,8>,t:vec3f)->f32{var q:array<f32,8>;for(var c=0u;c<8u;c+=1u){q[c]=v[c]*select(1.-t.x,t.x,(c&1u)!=0u)*select(1.-t.y,t.y,(c&2u)!=0u)*select(1.-t.z,t.z,(c&4u)!=0u);}return ordered8(q);}
fn symmetricProduct3(a:f32,b:f32,c:f32)->f32{var v=vec3f(a,b,c);if(v.y<v.x){let q=v.x;v.x=v.y;v.y=q;}if(v.z<v.y){let q=v.y;v.y=v.z;v.z=q;}if(v.y<v.x){let q=v.x;v.x=v.y;v.y=q;}return (v.x*v.y)*v.z;}
fn transferWeight(t:vec3f,c:u32)->f32{let raw=symmetricProduct3(select(1.-t.x,t.x,(c&1u)!=0u),select(1.-t.y,t.y,(c&2u)!=0u),select(1.-t.z,t.z,(c&4u)!=0u));return round(raw*16777216.)/16777216.;}
fn cellKey(q:vec3u)->u32{return q.x+p.dimsMax.x*(q.y+p.dimsMax.y*q.z);}
fn lowerBound(key:u32)->u32{var lo=0u;var hi=leafCount();loop{if(lo>=hi){break;}let m=lo+(hi-lo)/2u;if(directory[m].cell<key){lo=m+1u;}else{hi=m;}}return lo;}
fn locate(cell:vec3u)->u32{var span=1u;loop{if(span>p.dimsMax.w){break;}let origin=(cell/span)*span;let at=lowerBound(cellKey(origin));if(at<leafCount()){let d=directory[at];if(d.cell==cellKey(origin)&&d.size==span&&d.slot<leafCount()&&(d.flags&1u)!=0u){return d.slot;}}if(span>p.dimsMax.w/2u){break;}span*=2u;}return INVALID;}
fn velocityAtGrid(q:vec3f)->vec4f{let upper=max(vec3f(p.dimsMax.xyz)-vec3f(1e-4),vec3f(0));let bounded=clamp(q,vec3f(0),upper);let owner=locate(min(vec3u(floor(bounded)),p.dimsMax.xyz-vec3u(1u)));if(owner==INVALID||owner>=leafCount()){return vec4f(0);}let r=leaves[owner];let t=clamp((bounded-vec3f(r.originSpan.xyz))/f32(r.originSpan.w),vec3f(0),vec3f(1));var x:array<f32,8>;var y:array<f32,8>;var z:array<f32,8>;for(var c=0u;c<8u;c+=1u){let n=corner(r,c);if(n>=nodeCount()||2u*n+p.policy.y>=arrayLength(&velocity)){return vec4f(0);}let value=velocity[2u*n+p.policy.y].xyz;let w=select(1.-t.x,t.x,(c&1u)!=0u)*select(1.-t.y,t.y,(c&2u)!=0u)*select(1.-t.z,t.z,(c&4u)!=0u); x[c]=value.x*w;y[c]=value.y*w;z[c]=value.z*w;}return vec4f(ordered8(x),ordered8(y),ordered8(z),1.);}
fn transportVelocity(r:Leaf)->vec3f{let centre=vec3f(r.originSpan.xyz)+vec3f(.5*f32(r.originSpan.w));let first=velocityAtGrid(centre);if(first.w==0.){atomicOr(&control[12],ERR_GRAPH);return vec3f(0);}let midpoint=centre+.5*(p.numerics.x/p.originCell.w)*first.xyz;let middle=velocityAtGrid(midpoint);return select(first.xyz,middle.xyz,middle.w!=0.);}
// Pick one cell to represent a crossed adaptive face/edge/corner.  An even-span
// leaf has no unique centre cell, so prefer the velocity direction and then
// the cell toward the domain centre.  Those choices transform with the donor
// under axis rotations/reflections except for the unavoidable exact-centre tie.
fn representativeCell(r:Leaf,displacement:vec3f)->vec3u{let span=r.originSpan.w;var cell=r.originSpan.xyz+vec3u((span-1u)/2u);if((span&1u)==0u){for(var axis=0u;axis<3u;axis+=1u){let twiceCentre=2u*r.originSpan[axis]+span;let upper=displacement[axis]>0.||(displacement[axis]==0.&&twiceCentre<p.dimsMax[axis]);if(upper){cell[axis]+=1u;}}}return cell;}
fn crossedAxes(c:u32)->u32{return (c&1u)+((c>>1u)&1u)+((c>>2u)&1u);}
fn patchCount(c:u32)->u32{return 1u<<(3u-crossedAxes(c));}
fn transferSlotBase(c:u32)->u32{var base=1u;for(var prior=1u;prior<c;prior+=1u){base+=patchCount(prior);}return base;}
fn tensorPatchCell(r:Leaf,displacement:vec3f,c:u32,patchIndex:u32)->vec4u{var cell=r.originSpan.xyz;var tangent=0u;var enabled=true;for(var axis=0u;axis<3u;axis+=1u){if((c&(1u<<axis))!=0u){if(displacement[axis]>0.){let face=r.originSpan[axis]+r.originSpan.w;if(face>=p.dimsMax[axis]){enabled=false;}else{cell[axis]=face;}}else{let face=r.originSpan[axis];if(face==0u){enabled=false;}else{cell[axis]=face-1u;}}}else{let side=(patchIndex>>tangent)&1u;let offset=min(r.originSpan.w-1u,((2u*side+1u)*r.originSpan.w)/4u);cell[axis]+=offset;tangent+=1u;}}return vec4u(cell,select(0u,1u,enabled));}
fn currentPhi(n:u32)->f32{return phi[n][min(p.policy.x,1u)];}
@compute @workgroup_size(1)fn prepareBootstrap(){for(var i=0u;i<32u;i+=1u){atomicStore(&control[i],0u);atomicStore(&receipts[i],0u);}atomicStore(&control[0],MAGIC);}
@compute @workgroup_size(64)fn bootstrapMassFromPhi(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;if(i>=leafCount()){return;}let r=leaves[i];var values:array<f32,8>;for(var c=0u;c<8u;c+=1u){let n=corner(r,c);if(n>=nodeCount()){atomicOr(&control[12],ERR_GRAPH);return;}values[c]=currentPhi(n);}var samples:array<f32,27>;let width=max(.25*f32(r.originSpan.w)*p.originCell.w,1e-8);for(var z=0u;z<3u;z+=1u){for(var y=0u;y<3u;y+=1u){for(var x=0u;x<3u;x+=1u){let value=trilerp(values,(vec3f(f32(x),f32(y),f32(z))+vec3f(.5))/3.);samples[x+3u*(y+3u*z)]=clamp(.5-value/(2.*width),0.,1.);}}}let rho=ordered27(samples)/27.;mass[i]=unitsToMass(massToUnits(rho*volume(r)));compression[i]=1.;}
@compute @workgroup_size(1)fn finishBootstrap(){var total=0.;for(var i=0u;i<leafCount();i+=1u){let m=mass[i];if(!finite(m)||m<0.){atomicOr(&control[12],ERR_FINITE);}total+=m;}atomicStore(&control[1],graph[0]);atomicStore(&control[2],graph[5]);atomicStore(&control[3],leafCount());atomicStore(&control[7],select(1u,0u,atomicLoad(&control[12])!=0u));atomicStore(&receipts[0],bitcast<u32>(total));atomicStore(&receipts[12],atomicLoad(&control[12]));}
@compute @workgroup_size(64)fn clearTransport(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;if(i>=leafCount()){return;}atomicStore(&nextMass[i],0u);atomicStore(&nextCompressionMass[i],0u);}
@compute @workgroup_size(1)fn prepareTransport(){atomicStore(&control[1],graph[0]);atomicStore(&control[3],leafCount());atomicStore(&control[4],0u);atomicStore(&control[5],0u);atomicStore(&control[6],0u);atomicStore(&control[12],0u);for(var i=1u;i<12u;i+=1u){atomicStore(&receipts[i],0u);}var total=0.;for(var i=0u;i<leafCount();i+=1u){let m=mass[i];if(!finite(m)||m<0.){atomicOr(&control[12],ERR_FINITE);}total+=m;}atomicStore(&receipts[0],bitcast<u32>(total));}
@compute @workgroup_size(64)fn buildTransfers(@builtin(global_invocation_id)gid:vec3u){let donor=gid.x;if(donor>=leafCount()){return;}let first=20u*donor;if(first+19u>=min(p.limits.w,arrayLength(&transfers))){atomicOr(&control[12],ERR_CAPACITY);return;}for(var slot=0u;slot<20u;slot+=1u){transfers[first+slot]=Transfer(donor,donor,0u,0u);}atomicMax(&control[5],first+20u);let m=mass[donor];if(!finite(m)||m<0.){atomicOr(&control[12],ERR_FINITE);return;}if(m<=p.numerics.y){return;}let units=massToUnits(m);if(units==0u){return;}let r=leaves[donor];let span=f32(r.originSpan.w);let displacement=transportVelocity(r)*(p.numerics.x/(span*p.originCell.w));var crossing=clamp(abs(displacement),vec3f(0.),vec3f(1.));for(var axis=0u;axis<3u;axis+=1u){let outwardLow=displacement[axis]<0.&&r.originSpan[axis]==0u;let outwardHigh=displacement[axis]>0.&&r.originSpan[axis]+r.originSpan.w>=p.dimsMax[axis];if(outwardLow||outwardHigh){crossing[axis]=0.;}}crossing=round(crossing*65536.)/65536.;var weights:array<f32,8>;for(var c=0u;c<8u;c+=1u){weights[c]=transferWeight(crossing,c);}let sum=ordered8(weights);if(!finite(sum)||sum<=0.){atomicOr(&control[12],ERR_TRANSFER);return;}var retained=u32(floor((weights[0]/sum)*f32(units)));var allocated=retained;for(var c=1u;c<8u;c+=1u){let subsetUnits=u32(floor((weights[c]/sum)*f32(units)));allocated+=subsetUnits;let patches=patchCount(c);let quotient=subsetUnits/patches;retained+=subsetUnits-quotient*patches;let base=transferSlotBase(c);for(var patchIndex=0u;patchIndex<patches;patchIndex+=1u){let sample=tensorPatchCell(r,displacement,c,patchIndex);var recipient=donor;if(sample.w!=0u&&quotient>0u){recipient=locate(sample.xyz);if(recipient==INVALID){recipient=donor;atomicAdd(&control[6],1u);}}transfers[first+base+patchIndex]=Transfer(donor,recipient,quotient,select(0u,1u,quotient>0u));}}if(allocated>units){atomicOr(&control[12],ERR_TRANSFER);return;}retained+=units-allocated;transfers[first]=Transfer(donor,donor,retained,1u);atomicAdd(&control[4],1u);atomicStore(&receipts[4],0u);}
@compute @workgroup_size(64)fn scatterTransfers(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;let count=atomicLoad(&control[5]);if(i>=count||atomicLoad(&control[12])!=0u){return;}let transfer=transfers[i];if((transfer.flags&1u)==0u){return;}if(transfer.donor>=leafCount()||transfer.recipient>=leafCount()){atomicOr(&control[12],ERR_TRANSFER);return;}let old=atomicAdd(&nextMass[transfer.recipient],transfer.weightBits);if(old>0xffffffffu-transfer.weightBits){atomicOr(&control[12],ERR_OVERFLOW);}}
@compute @workgroup_size(64)fn validateTransportLeaves(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;if(i>=leafCount()){return;}let units=atomicLoad(&nextMass[i]);if(unitsToMass(units)<0.){atomicOr(&control[12],ERR_FINITE);}}
fn stagedRho(i:u32)->f32{if(i>=leafCount()){return 0.;}return unitsToMass(atomicLoad(&nextMass[i]))/max(volume(leaves[i]),1e-30);}
fn faceNeighbor(r:Leaf,face:u32)->u32{let axis=face>>1u;let positive=(face&1u)!=0u;let span=r.originSpan.w;var cell=r.originSpan.xyz+vec3u((span-1u)/2u);if(positive){let q=r.originSpan[axis]+span;if(q>=p.dimsMax[axis]){return INVALID;}cell[axis]=q;}else{let q=r.originSpan[axis];if(q==0u){return INVALID;}cell[axis]=q-1u;}let neighbor=locate(cell);if(neighbor==INVALID||neighbor>=leafCount()||leaves[neighbor].originSpan.w!=r.originSpan.w){return INVALID;}return neighbor;}
@compute @workgroup_size(64)fn clearSharpen(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;if(i>=leafCount()){return;}atomicStore(&nextCompressionMass[i],0u);}
// Equations 11--15 need the one-sided gradient that points from an air-side
// donor toward increasing rho. Face 2a is the negative-axis neighbour and
// face 2a+1 the positive-axis neighbour, hence positive(deltaPositive) and
// negative(deltaNegative) are the two higher-density directions. Selecting
// the opposite signs anti-sharpens while still looking exactly conservative.
@compute @workgroup_size(64)fn buildSharpenTransfers(@builtin(global_invocation_id)gid:vec3u){let donor=gid.x;if(donor>=leafCount()){return;}let first=20u*donor;if(first+19u>=min(p.limits.w,arrayLength(&transfers))){atomicOr(&control[12],ERR_CAPACITY);return;}for(var slot=0u;slot<20u;slot+=1u){transfers[first+slot]=Transfer(donor,donor,0u,0u);}if(atomicLoad(&control[12])!=0u){return;}let units=atomicLoad(&nextMass[donor]);if(units==0u){return;}let donorRho=stagedRho(donor);if(!finite(donorRho)){atomicOr(&control[12],ERR_FINITE);return;}if(donorRho<=0.||donorRho>=SHARPEN_RHO_THRESHOLD){transfers[first]=Transfer(donor,donor,units,1u);return;}let r=leaves[donor];var candidates:array<u32,6>;var candidateRho:array<f32,6>;var maximum=donorRho;var maximumDifference=0.;for(var face=0u;face<6u;face+=1u){let recipient=faceNeighbor(r,face);candidates[face]=recipient;if(recipient==INVALID||recipient==donor){candidateRho[face]=donorRho;continue;}let value=stagedRho(recipient);if(!finite(value)){atomicOr(&control[12],ERR_FINITE);return;}candidateRho[face]=value;maximum=max(maximum,value);maximumDifference=max(maximumDifference,abs(value-donorRho));}if(maximum<=donorRho){transfers[first]=Transfer(donor,donor,units,1u);return;}var maxima:array<u32,6>;var count=0u;for(var face=0u;face<6u;face+=1u){let recipient=candidates[face];if(recipient==INVALID||recipient==donor||candidateRho[face]!=maximum){continue;}var duplicate=false;for(var previous=0u;previous<count;previous+=1u){duplicate=duplicate||maxima[previous]==recipient;}if(!duplicate){maxima[count]=recipient;count+=1u;}}if(count==0u){transfers[first]=Transfer(donor,donor,units,1u);return;}var negativeGradient:array<f32,3>;for(var axis=0u;axis<3u;axis+=1u){let deltaPositive=candidateRho[2u*axis]-donorRho;let deltaNegative=donorRho-candidateRho[2u*axis+1u];negativeGradient[axis]=max(max(deltaPositive,0.),abs(min(deltaNegative,0.)));}let limiter=1.-min(1.,maximumDifference/.4);let gradient=sqrt(negativeGradient[0]*negativeGradient[0]+negativeGradient[1]*negativeGradient[1]+negativeGradient[2]*negativeGradient[2]);let fictitiousCourant=min(1.,3.*p.numerics.x/max(f32(r.originSpan.w)*p.originCell.w,1e-20));let w=abs((donorRho-SHARPEN_RHO_THRESHOLD)*(donorRho-SHARPEN_RHO_THRESHOLD)*(donorRho-SHARPEN_RHO_THRESHOLD));var deltaRho=w*limiter*gradient*fictitiousCourant;if(donorRho<1e-5){deltaRho=donorRho;}let requested=min(units,massToUnits(min(donorRho,deltaRho)*volume(r)));let quotient=requested/count;let distributed=quotient*count;transfers[first]=Transfer(donor,donor,units-distributed,1u);for(var recipientIndex=0u;recipientIndex<count;recipientIndex+=1u){transfers[first+1u+recipientIndex]=Transfer(donor,maxima[recipientIndex],quotient,select(0u,1u,quotient>0u));}}
@compute @workgroup_size(64)fn scatterSharpenTransfers(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;let count=atomicLoad(&control[5]);if(i>=count||atomicLoad(&control[12])!=0u){return;}let transfer=transfers[i];if((transfer.flags&1u)==0u){return;}if(transfer.donor>=leafCount()||transfer.recipient>=leafCount()){atomicOr(&control[12],ERR_TRANSFER);return;}let old=atomicAdd(&nextCompressionMass[transfer.recipient],transfer.weightBits);if(old>0xffffffffu-transfer.weightBits){atomicOr(&control[12],ERR_OVERFLOW);}}
@compute @workgroup_size(64)fn validateSharpenLeaves(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;if(i>=leafCount()){return;}let units=atomicLoad(&nextCompressionMass[i]);if(!finite(unitsToMass(units))){atomicOr(&control[12],ERR_FINITE);}}
@compute @workgroup_size(64)fn finishTransportLeaves(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;if(i>=leafCount()||atomicLoad(&control[12])!=0u){return;}mass[i]=unitsToMass(atomicLoad(&nextCompressionMass[i]));compression[i]=1.;}
@compute @workgroup_size(1)fn finishTransport(){var total=0.;for(var i=0u;i<leafCount();i+=1u){total+=mass[i];}let before=bitcast<f32>(atomicLoad(&receipts[0]));atomicStore(&receipts[1],bitcast<u32>(total));atomicStore(&receipts[2],bitcast<u32>(total-before));atomicStore(&receipts[5],atomicLoad(&control[4]));atomicStore(&receipts[6],atomicLoad(&control[5]));atomicStore(&receipts[7],atomicLoad(&control[6]));atomicStore(&receipts[12],atomicLoad(&control[12]));atomicStore(&receipts[0],bitcast<u32>(total));if(atomicLoad(&control[12])==0u){atomicAdd(&control[2],1u);atomicStore(&control[7],1u);}else{atomicStore(&control[7],0u);}}
fn overlapCells(a:Leaf,b:Leaf)->u32{let lo=max(a.originSpan.xyz,b.originSpan.xyz);let hi=min(a.originSpan.xyz+vec3u(a.originSpan.w),b.originSpan.xyz+vec3u(b.originSpan.w));if(any(hi<=lo)){return 0u;}let d=hi-lo;return d.x*d.y*d.z;}
fn leafCells(r:Leaf)->u32{let span=r.originSpan.w;return span*span*span;}
@compute @workgroup_size(1)fn prepareHandoff(){atomicStore(&control[12],0u);for(var i=8u;i<12u;i+=1u){atomicStore(&receipts[i],0u);}}
// Gather into global fixed-point units. Each destination depends only on its
// overlap multiset, so rotations/reflections with identical source mass remain
// bit-identical. The per-overlap nearest-integer rule may leave a tiny global
// drift when one source is split; finishHandoff reports that drift in units.
@compute @workgroup_size(64)fn handoffMass(@builtin(global_invocation_id)gid:vec3u){let dst=gid.x;if(dst>=leafCount()){return;}var targetUnits=0u;for(var src=0u;src<sourceLeafCount();src+=1u){let cells=overlapCells(leaves[dst],sourceLeaves[src]);if(cells==0u){continue;}let sourceCells=leafCells(sourceLeaves[src]);if(sourceCells==0u){atomicOr(&control[12],ERR_GRAPH);continue;}let sourceUnits=massToUnits(sourceMass[src]);let quotient=sourceUnits/sourceCells;let remainder=sourceUnits%sourceCells;let fractionalNumerator=remainder*cells+sourceCells/2u;let contribution=quotient*cells+fractionalNumerator/sourceCells;if(targetUnits>0xffffffffu-contribution){atomicOr(&control[12],ERR_OVERFLOW);targetUnits=0xffffffffu;}else{targetUnits+=contribution;}}atomicStore(&nextMass[dst],targetUnits);}
@compute @workgroup_size(64)fn finishHandoffLeaves(@builtin(global_invocation_id)gid:vec3u){let dst=gid.x;if(dst>=leafCount()){return;}mass[dst]=unitsToMass(atomicLoad(&nextMass[dst]));compression[dst]=1.;}
@compute @workgroup_size(1)fn finishHandoff(){var sourceUnits=0u;var targetUnits=0u;for(var i=0u;i<sourceLeafCount();i+=1u){let units=massToUnits(sourceMass[i]);if(sourceUnits>0xffffffffu-units){atomicOr(&control[12],ERR_OVERFLOW);}else{sourceUnits+=units;}}let targetLeaves=leafCount();if(graph[0]==0u||graph[3]!=graph[0]||graph[4]!=0u||graph[1]!=targetLeaves||(sourceUnits>0u&&targetLeaves==0u)){atomicOr(&control[12],ERR_GRAPH);}for(var i=0u;i<targetLeaves;i+=1u){let units=atomicLoad(&nextMass[i]);if(targetUnits>0xffffffffu-units){atomicOr(&control[12],ERR_OVERFLOW);}else{targetUnits+=units;}}let a=unitsToMass(sourceUnits);let b=unitsToMass(targetUnits);var drift=0.;if(targetUnits>=sourceUnits){drift=unitsToMass(targetUnits-sourceUnits);}else{drift=-unitsToMass(sourceUnits-targetUnits);}atomicStore(&receipts[8],bitcast<u32>(a));atomicStore(&receipts[9],bitcast<u32>(b));atomicStore(&receipts[10],bitcast<u32>(drift));atomicStore(&receipts[11],targetLeaves);atomicStore(&receipts[12],atomicLoad(&control[12]));atomicStore(&control[1],graph[0]);atomicStore(&control[2],graph[5]);atomicStore(&control[3],targetLeaves);atomicStore(&control[7],select(1u,0u,atomicLoad(&control[12])!=0u));if(atomicLoad(&control[12])==0u&&sourceGraph[13]!=0u){graph[13]=sourceGraph[13];}}
@compute @workgroup_size(64)fn deriveLeafRhoPhi(@builtin(global_invocation_id)gid:vec3u){let i=gid.x;if(i>=leafCount()){return;}let r=leaves[i];let rho=rhoOf(i);let h=f32(r.originSpan.w)*p.originCell.w;leafRhoPhi[i]=vec4f(rho,(.5-rho)*h,mass[i],compression[i]);}
// The reconstructed compatibility cache uses the physical rho=.5 contour.
// A global fitted threshold is not an invariant of the represented density:
// merely repartitioning identical mass can change its nodal quadrature and
// move the entire surface. Conserved sharpening keeps density concentrated;
// reconstruction therefore measures volume but never feeds it back globally.
@compute @workgroup_size(1)fn prepareReconstruction(){var goalUnits=0u;var error=0u;for(var i=0u;i<leafCount();i+=1u){let units=massToUnits(mass[i]);if(goalUnits>0xffffffffu-units){error|=ERR_OVERFLOW;}else{goalUnits+=units;}}atomicStore(&control[13],INVALID);atomicStore(&reconstruction[0],bitcast<u32>(SURFACE_RHO_ISO));atomicStore(&reconstruction[1],bitcast<u32>(SURFACE_RHO_ISO));atomicStore(&reconstruction[2],bitcast<u32>(SURFACE_RHO_ISO));atomicStore(&reconstruction[3],goalUnits);atomicStore(&reconstruction[4],0u);atomicStore(&reconstruction[5],0u);atomicStore(&reconstruction[6],error);atomicStore(&reconstruction[7],bitcast<u32>(SURFACE_RHO_ISO));if(error!=0u){atomicOr(&control[12],error);}}
@compute @workgroup_size(1)fn clearReconstructionMeasure(){atomicStore(&reconstruction[4],0u);}
@compute @workgroup_size(64)fn deriveNodalPseudoPhi(@builtin(global_invocation_id)gid:vec3u){let n=gid.x;if(n>=nodeCount()||constraints[n].header.y!=0u){return;}var rhoTerms:array<f32,8>;var weights:array<f32,8>;for(var octant=0u;octant<8u;octant+=1u){let at=8u*n+octant;if(at>=arrayLength(&incidentLeaves)){atomicOr(&control[12],ERR_GRAPH);return;}let leaf=incidentLeaves[at];if(leaf==INVALID){continue;}if(leaf>=leafCount()){atomicOr(&control[12],ERR_GRAPH);continue;}rhoTerms[octant]=rhoOf(leaf);weights[octant]=1.;}let weight=ordered8(weights);let rho=select(0.,ordered8(rhoTerms)/max(weight,1e-20),weight>0.);let threshold=bitcast<f32>(atomicLoad(&reconstruction[2]));let localH=p.originCell.w;let value=clamp((threshold-rho)*localH,-2.*localH,2.*localH);if(p.policy.z>=2u){phi[n]=vec2f(value);}else{phi[n][p.policy.z]=value;}}
// A topology handoff already populated phi by exact node retention or
// trilinear sampling of the accepted graph.  Reconstructing from one mass
// scalar per new leaf can discard sub-cell interface position, especially
// across a changing hanging-node constraint set.  Validate the independent
// rho=.5 sign against that topology-invariant cache as a diagnostic. A nodal
// subcell interface and an average over incident leaf densities are different
// representations, so their signs may legitimately disagree after a 2:1
// topology change. Preserve that evidence in the receipt without rejecting an
// otherwise finite, conservative handoff or overwriting the retained geometry.
@compute @workgroup_size(64)fn validateNodalPseudoPhi(@builtin(global_invocation_id)gid:vec3u){let n=gid.x;if(n>=nodeCount()||constraints[n].header.y!=0u){return;}var rhoTerms:array<f32,8>;var weights:array<f32,8>;for(var octant=0u;octant<8u;octant+=1u){let at=8u*n+octant;if(at>=arrayLength(&incidentLeaves)){atomicOr(&control[12],ERR_GRAPH);return;}let leaf=incidentLeaves[at];if(leaf==INVALID){continue;}if(leaf>=leafCount()){atomicOr(&control[12],ERR_GRAPH);continue;}rhoTerms[octant]=rhoOf(leaf);weights[octant]=1.;}let weight=ordered8(weights);let rho=select(0.,ordered8(rhoTerms)/max(weight,1e-20),weight>0.);let expected=clamp((SURFACE_RHO_ISO-rho)*p.originCell.w,-2.*p.originCell.w,2.*p.originCell.w);let retained=phi[n].x;if(!finite(retained)){atomicOr(&control[12],ERR_FINITE);return;}if((expected<0.)!=(retained<0.)){atomicAdd(&reconstruction[5],1u);atomicMin(&control[13],nodes[n].x);}}
@compute @workgroup_size(64)fn projectNodalPseudoPhi(@builtin(global_invocation_id)gid:vec3u){let n=gid.x;if(n>=nodeCount()){return;}let c=constraints[n];let count=c.header.y;if(count==0u){return;}if((count!=2u&&count!=4u)||c.header.z==0u){atomicOr(&control[12],ERR_GRAPH);return;}var terms:array<f32,4>;for(var i=0u;i<count;i+=1u){let master=c.masters[i];if(master>=nodeCount()){atomicOr(&control[12],ERR_GRAPH);return;}terms[i]=f32(c.numerators[i])*phi[master][min(p.policy.z,1u)];}for(var i=0u;i<count;i+=1u){for(var j=i+1u;j<count;j+=1u){if(terms[j]<terms[i]||(terms[j]==terms[i]&&bitcast<u32>(terms[j])<bitcast<u32>(terms[i]))){let t=terms[i];terms[i]=terms[j];terms[j]=t;}}}let sum=select(terms[0]+terms[1],(terms[0]+terms[1])+(terms[2]+terms[3]),count==4u);let value=sum/f32(c.header.z);if(p.policy.z>=2u){phi[n]=vec2f(value);}else{phi[n][p.policy.z]=value;}}
// Diagnostic geometry follows the published zero-set exactly. The old smooth
// Heaviside used a width proportional to the pressure-leaf span while the
// density residual had finest-cell amplitude; pure coarse air therefore
// contributed as much as 25% liquid and produced a fictitious global volume.
// Mass is reported independently from the fixed-point density authority.
@compute @workgroup_size(64)fn measureReconstructionVolume(@builtin(global_invocation_id)gid:vec3u){let leaf=gid.x;if(leaf>=leafCount()){return;}let r=leaves[leaf];var values:array<f32,8>;let bank=min(p.policy.z,1u);for(var c=0u;c<8u;c+=1u){let n=corner(r,c);if(n>=nodeCount()){atomicOr(&control[12],ERR_GRAPH);atomicOr(&reconstruction[6],ERR_GRAPH);return;}values[c]=phi[n][bank];if(!finite(values[c])){atomicOr(&control[12],ERR_FINITE);atomicOr(&reconstruction[6],ERR_FINITE);return;}}var samples:array<f32,27>;for(var z=0u;z<3u;z+=1u){for(var y=0u;y<3u;y+=1u){for(var x=0u;x<3u;x+=1u){let value=trilerp(values,(vec3f(f32(x),f32(y),f32(z))+vec3f(.5))/3.);samples[x+3u*(y+3u*z)]=select(0.,1.,value<0.);}}}let fraction=ordered27(samples)/27.;let span=r.originSpan.w;let finestCells=span*span*span;let raw=round(clamp(fraction,0.,1.)*f32(finestCells*65536u));if(!finite(raw)||raw<0.||raw>4294967040.){atomicOr(&control[12],ERR_OVERFLOW);atomicOr(&reconstruction[6],ERR_OVERFLOW);return;}let units=u32(raw);let prior=atomicAdd(&reconstruction[4],units);if(prior>0xffffffffu-units){atomicOr(&control[12],ERR_OVERFLOW);atomicOr(&reconstruction[6],ERR_OVERFLOW);}}
@compute @workgroup_size(1)fn finishReconstructionIteration(){let mismatches=atomicLoad(&reconstruction[5]);let goalUnits=atomicLoad(&reconstruction[3]);let measured=atomicLoad(&reconstruction[4]);let threshold=SURFACE_RHO_ISO;let errors=atomicLoad(&reconstruction[6])|atomicLoad(&control[12]);atomicStore(&reconstruction[7],bitcast<u32>(threshold));atomicStore(&receipts[13],bitcast<u32>(threshold));atomicStore(&receipts[14],goalUnits);atomicStore(&receipts[15],measured);atomicStore(&receipts[16],mismatches);atomicStore(&receipts[17],atomicLoad(&control[13]));atomicStore(&receipts[12],errors);if(errors!=0u){atomicStore(&control[7],0u);return;}graph[13]=bitcast<u32>(threshold);}
@compute @workgroup_size(64)fn deriveRows(@builtin(global_invocation_id)gid:vec3u){let row=gid.x;if(row>=rowCount()){return;}let leaf=rowToLeaf[row];if(leaf>=leafCount()){atomicOr(&control[12],ERR_GRAPH);return;}let value=leafRhoPhi[leaf];let rho=value.x;rowRho[row]=vec4f(rho,mass[leaf],volume(leaves[leaf]),compression[leaf]);let flags=1u|select(0u,2u,rho>0.&&rho<1.);rowPhi[row]=vec4u(bitcast<u32>(value.y),bitcast<u32>(value.y),bitcast<u32>(value.y),flags);}
`;
