import { ALGORITHM_PARAMS } from "./features/algorithms/definition";
import type { MethodParamSpec } from "../../core/method-contract";

const runtimeUpdate = { update: "runtime" as const };

export const UNIFORM_GAMMA_DIFFUSION_DEFAULT_ITERATIONS = 1;
export const UNIFORM_GAMMA_DIFFUSION_MAX_ITERATIONS = 7;

export const UNIFORM_PARAMS: MethodParamSpec[] = [
  ...ALGORITHM_PARAMS,
  {
    ...runtimeUpdate, kind: "number", key: "pressureResidualTolerance",
    label: "Pressure residual tolerance", default: 10, tier: "fine",
    min: 0, max: 100, step: 0.0001, digits: 4, unit: "s⁻¹",
    hint: "Stop after a complete Full-Cycle or V-Cycle when the projected residual infinity norm is at or below this tolerance. Zero disables tolerance-based early exit; divergent cycles still switch to safeguarded recovery.",
  },
  {
    ...runtimeUpdate, kind: "select", key: "pressureCycleBudget",
    label: "Pressure cycle budget", default: "lagged", tier: "fine",
    options: [{ value: "lagged", label: "Lagged" }, { value: "fixed", label: "Fixed" }],
    hint: "Lagged encodes only as many multigrid cycles as the latest diagnostics sample says the solve needed, so the unused tail costs neither its GPU launch floor nor its CPU encode. Fixed always encodes the configured schedule and lets the GPU residual gate skip the remainder, which is the pre-P1 command stream.",
  },
  {
    ...runtimeUpdate, kind: "number", key: "pressureBudgetHeadroom",
    label: "Budget headroom", default: 1, tier: "fine",
    min: 0, max: 4, step: 1, digits: 0, unit: "cycles",
    hint: "Cycles the lagged budget encodes above the last observed demand. A step that used every encoded cycle without meeting tolerance doubles its budget instead, so an impact frame recovers the full schedule in one or two steps.",
  },
  {
    ...runtimeUpdate, kind: "number", key: "extensionFrontSweeps",
    label: "Extension front sweeps", default: 16, tier: "fine",
    min: 1, max: 16, step: 1, digits: 0, unit: "sweeps",
    hint: "Sec. 3.3 FIM sweep budget for the two-cell accurate band. Each sweep is an update and a dispatch-gate pass whether or not work remains; sixteen covers the band's full dependency diameter. Fewer sweeps resolve an unconverged front and leave unreached band faces to the hierarchy fill.",
  },
  {
    ...runtimeUpdate,
    kind: "number",
    key: "gammaDiffusionIterations",
    label: "Gamma iterations",
    default: UNIFORM_GAMMA_DIFFUSION_DEFAULT_ITERATIONS,
    tier: "fine",
    unit: "iterations",
    min: 1,
    max: UNIFORM_GAMMA_DIFFUSION_MAX_ITERATIONS,
    step: 1,
    digits: 0,
    hint: "Each paper iteration is three snapshot axis passes. One is the reference default; additional repetitions deliberately apply more diffusion.",
  },
  {
    ...runtimeUpdate,
    kind: "number",
    key: "sharpeningStrength",
    label: "Sharpening strength",
    default: 1,
    tier: "fine",
    unit: "×",
    min: 0.25,
    max: 2,
    step: 0.05,
    digits: 2,
    hint: "Scales the paper's 3dt pseudo-time dose used by the local density correction.",
  },
  {
    ...runtimeUpdate,
    kind: "number",
    key: "sharpeningDistance",
    label: "Mass-return distance",
    default: 2.1,
    tier: "fine",
    unit: "cells",
    min: 0.1,
    max: 3.1,
    step: 0.1,
    digits: 1,
    hint: "Maximum Algorithm 2 gradient-trace distance D. The paper uses 1.1 to 3.1 cells; below 1.1 mass stays where it was removed, which reads as weaker surface tension.",
  },
  {
    kind: "number",
    key: "pressureFullCycles",
    label: "Pressure Full-Cycles",
    default: 3,
    tier: "fine",
    unit: "cycles",
    min: 0,
    max: 5,
    step: 1,
    digits: 0,
    hint: "CM11a Full-Cycles seed corrections from the coarsest grid upward. The paper schedule uses three. This prebuilt dispatch schedule resets the solver when changed.",
  },
  {
    kind: "number",
    key: "pressureVCycles",
    label: "Pressure V-Cycles",
    default: 4,
    tier: "fine",
    unit: "cycles",
    min: 0,
    max: 8,
    step: 1,
    digits: 0,
    hint: "Refinement V-Cycles after the Full-Cycles. The paper schedule uses four. This prebuilt dispatch schedule resets the solver when changed.",
  },
  {
    kind: "number",
    key: "pressureSweeps",
    label: "Pressure pre/post sweeps",
    default: 6,
    tier: "fine",
    unit: "sweeps",
    min: 1,
    max: 8,
    step: 1,
    digits: 0,
    hint: "Projected red-black Gauss-Seidel sweeps on each side of a multigrid coarse correction. The paper used four; six keeps deeper 64×32×64 hierarchies converged. This prebuilt dispatch schedule resets the solver when changed.",
  },
];
