// Generated by tools/wasm/generate-uniform-geometric-contract.ts. Do not edit.
use crate::types::ValidationError;
use serde::{Deserialize, Serialize};

pub const UNIFORM_CM11A_COARSE_RESIDUAL_TOLERANCE: f32 = 0.0001_f32;
pub const UNIFORM_CM11A_COARSE_SWEEP_CAP: usize = 4096;
pub const UNIFORM_CM11A_DEFAULT_BUDGET_HEADROOM: usize = 1;
pub const UNIFORM_CM11A_FULL_CYCLES: usize = 3;
pub const UNIFORM_CM11A_MINIMUM_CYCLE_BUDGET: usize = 1;
pub const UNIFORM_CM11A_PHI_PRESERVATION_LEVELS: usize = 2;
pub const UNIFORM_CM11A_POST_SWEEPS: usize = 6;
pub const UNIFORM_CM11A_PRE_SWEEPS: usize = 6;
pub const UNIFORM_CM11A_RECOVERY_BATCHES: usize = 8;
pub const UNIFORM_CM11A_RECOVERY_REDUCTION: f32 = 0.1_f32;
pub const UNIFORM_CM11A_RECOVERY_SWEEPS: usize = 8;
pub const UNIFORM_CM11A_V_CYCLES: usize = 4;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct UniformGeometricOptions {
    #[serde(rename = "activeRegion")]
    pub active_region: String,
    #[serde(rename = "densitySharpening")]
    pub density_sharpening: String,
    #[serde(rename = "rigidCoupling")]
    pub rigid_coupling: String,
    #[serde(rename = "velocityTransport")]
    pub velocity_transport: String,
    #[serde(rename = "liquidOnlyVelocityAdvection")]
    pub liquid_only_velocity_advection: String,
    #[serde(rename = "timeStep")]
    pub time_step: String,
    #[serde(rename = "pressureResidualTolerance")]
    pub pressure_residual_tolerance: f32,
    #[serde(rename = "pressureCycleBudget")]
    pub pressure_cycle_budget: String,
    #[serde(rename = "pressureBudgetHeadroom")]
    pub pressure_budget_headroom: f32,
    #[serde(rename = "extensionFrontSweeps")]
    pub extension_front_sweeps: f32,
    #[serde(rename = "sharpeningStrength")]
    pub sharpening_strength: f32,
    #[serde(rename = "sharpeningDistance")]
    pub sharpening_distance: f32,
    #[serde(rename = "pressureFullCycles")]
    pub pressure_full_cycles: f32,
    #[serde(rename = "pressureVCycles")]
    pub pressure_v_cycles: f32,
    #[serde(rename = "pressureSweeps")]
    pub pressure_sweeps: f32,
    #[serde(rename = "pressureWindow")]
    pub pressure_window: String,
    #[serde(rename = "redistance")]
    pub redistance: String,
    #[serde(rename = "sharpeningWorkMap")]
    pub sharpening_work_map: String,
    #[serde(rename = "volumeDustThreshold")]
    pub volume_dust_threshold: f32,
    #[serde(rename = "twoLevelVelocity")]
    pub two_level_velocity: String,
    #[serde(rename = "twoLevelFineReach")]
    pub two_level_fine_reach: f32,
    #[serde(rename = "twoLevelExtension")]
    pub two_level_extension: String,
    #[serde(rename = "twoLevelShellReach")]
    pub two_level_shell_reach: f32,
    #[serde(rename = "twoLevelAdvection")]
    pub two_level_advection: String,
    #[serde(rename = "transportWorkMap")]
    pub transport_work_map: String,
    #[serde(rename = "transportReach")]
    pub transport_reach: f32,
    #[serde(rename = "volumePressureRows")]
    pub volume_pressure_rows: String,
    #[serde(rename = "volumeCompaction")]
    pub volume_compaction: String,
    #[serde(rename = "phiSeedFromVolume")]
    pub phi_seed_from_volume: String,
    #[serde(rename = "phiAgreement")]
    pub phi_agreement: String,
    #[serde(rename = "phiAgreementGain")]
    pub phi_agreement_gain: f32,
    #[serde(rename = "phiAgreementClamp")]
    pub phi_agreement_clamp: f32,
    #[serde(rename = "totalSurfaceVolume")]
    pub total_surface_volume: String,
}
impl Default for UniformGeometricOptions {
    fn default() -> Self {
        Self {
            active_region: "on".into(),
            density_sharpening: "on".into(),
            rigid_coupling: "on".into(),
            velocity_transport: "semi-lagrangian".into(),
            liquid_only_velocity_advection: "off".into(),
            time_step: "paper".into(),
            pressure_residual_tolerance: 10_f32,
            pressure_cycle_budget: "lagged".into(),
            pressure_budget_headroom: 1_f32,
            extension_front_sweeps: 2_f32,
            sharpening_strength: 1_f32,
            sharpening_distance: 2.1_f32,
            pressure_full_cycles: 3_f32,
            pressure_v_cycles: 4_f32,
            pressure_sweeps: 6_f32,
            pressure_window: "window".into(),
            redistance: "on".into(),
            sharpening_work_map: "on".into(),
            volume_dust_threshold: 0.000001_f32,
            two_level_velocity: "on".into(),
            two_level_fine_reach: 2_f32,
            two_level_extension: "tiles".into(),
            two_level_shell_reach: 1_f32,
            two_level_advection: "tiles".into(),
            transport_work_map: "tiles".into(),
            transport_reach: 1_f32,
            volume_pressure_rows: "off".into(),
            volume_compaction: "off".into(),
            phi_seed_from_volume: "off".into(),
            phi_agreement: "off".into(),
            phi_agreement_gain: 0.05_f32,
            phi_agreement_clamp: 0.02_f32,
            total_surface_volume: "on".into(),
        }
    }
}
impl UniformGeometricOptions {
    pub fn validate(&self) -> Result<(), ValidationError> {
        if !["on", "off"].contains(&self.active_region.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter activeRegion".into(),
            ));
        }
        if !["on", "off"].contains(&self.density_sharpening.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter densitySharpening".into(),
            ));
        }
        if !["on", "off"].contains(&self.rigid_coupling.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter rigidCoupling".into(),
            ));
        }
        if !["semi-lagrangian", "maccormack"].contains(&self.velocity_transport.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter velocityTransport".into(),
            ));
        }
        if !["off", "on"].contains(&self.liquid_only_velocity_advection.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter liquidOnlyVelocityAdvection".into(),
            ));
        }
        if !["paper", "scene"].contains(&self.time_step.as_str()) {
            return Err(ValidationError("Invalid uniform parameter timeStep".into()));
        }
        if !self.pressure_residual_tolerance.is_finite()
            || !((0_f32)..=(100_f32)).contains(&self.pressure_residual_tolerance)
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureResidualTolerance".into(),
            ));
        }
        if !["lagged", "fixed"].contains(&self.pressure_cycle_budget.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter pressureCycleBudget".into(),
            ));
        }
        if !self.pressure_budget_headroom.is_finite()
            || !((0_f32)..=(4_f32)).contains(&self.pressure_budget_headroom)
            || self.pressure_budget_headroom.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureBudgetHeadroom".into(),
            ));
        }
        if !self.extension_front_sweeps.is_finite()
            || !((1_f32)..=(16_f32)).contains(&self.extension_front_sweeps)
            || self.extension_front_sweeps.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter extensionFrontSweeps".into(),
            ));
        }
        if !self.sharpening_strength.is_finite()
            || !((0_f32)..=(1_f32)).contains(&self.sharpening_strength)
        {
            return Err(ValidationError(
                "Invalid uniform parameter sharpeningStrength".into(),
            ));
        }
        if !self.sharpening_distance.is_finite()
            || !((0.1_f32)..=(3.1_f32)).contains(&self.sharpening_distance)
        {
            return Err(ValidationError(
                "Invalid uniform parameter sharpeningDistance".into(),
            ));
        }
        if !self.pressure_full_cycles.is_finite()
            || !((0_f32)..=(5_f32)).contains(&self.pressure_full_cycles)
            || self.pressure_full_cycles.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureFullCycles".into(),
            ));
        }
        if !self.pressure_v_cycles.is_finite()
            || !((0_f32)..=(8_f32)).contains(&self.pressure_v_cycles)
            || self.pressure_v_cycles.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureVCycles".into(),
            ));
        }
        if !self.pressure_sweeps.is_finite()
            || !((1_f32)..=(8_f32)).contains(&self.pressure_sweeps)
            || self.pressure_sweeps.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureSweeps".into(),
            ));
        }
        if !["window", "domain"].contains(&self.pressure_window.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter pressureWindow".into(),
            ));
        }
        if !["on", "off"].contains(&self.redistance.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter redistance".into(),
            ));
        }
        if !["on", "off"].contains(&self.sharpening_work_map.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter sharpeningWorkMap".into(),
            ));
        }
        if !self.volume_dust_threshold.is_finite()
            || !((0_f32)..=(0.001_f32)).contains(&self.volume_dust_threshold)
        {
            return Err(ValidationError(
                "Invalid uniform parameter volumeDustThreshold".into(),
            ));
        }
        if !["on", "off"].contains(&self.two_level_velocity.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter twoLevelVelocity".into(),
            ));
        }
        if !self.two_level_fine_reach.is_finite()
            || !((0_f32)..=(8_f32)).contains(&self.two_level_fine_reach)
            || self.two_level_fine_reach.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter twoLevelFineReach".into(),
            ));
        }
        if !["tiles", "dense"].contains(&self.two_level_extension.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter twoLevelExtension".into(),
            ));
        }
        if !self.two_level_shell_reach.is_finite()
            || !((0_f32)..=(8_f32)).contains(&self.two_level_shell_reach)
            || self.two_level_shell_reach.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter twoLevelShellReach".into(),
            ));
        }
        if !["tiles", "dense"].contains(&self.two_level_advection.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter twoLevelAdvection".into(),
            ));
        }
        if !["tiles", "dense"].contains(&self.transport_work_map.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter transportWorkMap".into(),
            ));
        }
        if !self.transport_reach.is_finite()
            || !((0_f32)..=(8_f32)).contains(&self.transport_reach)
            || self.transport_reach.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter transportReach".into(),
            ));
        }
        if !["abandoned", "all", "off"].contains(&self.volume_pressure_rows.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter volumePressureRows".into(),
            ));
        }
        if !["on", "off"].contains(&self.volume_compaction.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter volumeCompaction".into(),
            ));
        }
        if !["on", "off"].contains(&self.phi_seed_from_volume.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter phiSeedFromVolume".into(),
            ));
        }
        if !["on", "off"].contains(&self.phi_agreement.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter phiAgreement".into(),
            ));
        }
        if !self.phi_agreement_gain.is_finite()
            || !((0_f32)..=(1_f32)).contains(&self.phi_agreement_gain)
        {
            return Err(ValidationError(
                "Invalid uniform parameter phiAgreementGain".into(),
            ));
        }
        if !self.phi_agreement_clamp.is_finite()
            || !((0_f32)..=(0.5_f32)).contains(&self.phi_agreement_clamp)
        {
            return Err(ValidationError(
                "Invalid uniform parameter phiAgreementClamp".into(),
            ));
        }
        if !["off", "on"].contains(&self.total_surface_volume.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter totalSurfaceVolume".into(),
            ));
        }
        Ok(())
    }
}
