// Generated by tools/wasm/generate-uniform-geometric-contract.ts. Do not edit.
use crate::types::ValidationError;
use serde::{Deserialize, Serialize};

pub const UNIFORM_CM11A_COARSE_RESIDUAL_TOLERANCE: f32 = 0.0001_f32;
pub const UNIFORM_CM11A_COARSE_SWEEP_CAP: usize = 4096;
pub const UNIFORM_CM11A_DEFAULT_BUDGET_HEADROOM: usize = 1;
pub const UNIFORM_CM11A_FULL_CYCLES: usize = 3;
pub const UNIFORM_CM11A_MINIMUM_CYCLE_BUDGET: usize = 1;
pub const UNIFORM_CM11A_PHI_PRESERVATION_LEVELS: usize = 2;
pub const UNIFORM_CM11A_POST_SWEEPS: usize = 6;
pub const UNIFORM_CM11A_PRE_SWEEPS: usize = 6;
pub const UNIFORM_CM11A_RECOVERY_BATCHES: usize = 8;
pub const UNIFORM_CM11A_RECOVERY_REDUCTION: f32 = 0.1_f32;
pub const UNIFORM_CM11A_RECOVERY_SWEEPS: usize = 8;
pub const UNIFORM_CM11A_V_CYCLES: usize = 4;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct UniformGeometricOptions {
    #[serde(rename = "densitySharpening")]
    pub density_sharpening: String,
    #[serde(rename = "rigidCoupling")]
    pub rigid_coupling: String,
    #[serde(rename = "timeStep")]
    pub time_step: String,
    #[serde(rename = "pressureResidualTolerance")]
    pub pressure_residual_tolerance: f32,
    #[serde(rename = "extensionFrontSweeps")]
    pub extension_front_sweeps: f32,
    #[serde(rename = "pressureFullCycles")]
    pub pressure_full_cycles: f32,
    #[serde(rename = "pressureVCycles")]
    pub pressure_v_cycles: f32,
    #[serde(rename = "pressureSweeps")]
    pub pressure_sweeps: f32,
    #[serde(rename = "volumeDustThreshold")]
    pub volume_dust_threshold: f32,
    #[serde(rename = "phiCubicAdvection")]
    pub phi_cubic_advection: String,
    #[serde(rename = "phiDrain")]
    pub phi_drain: String,
    #[serde(rename = "totalSurfaceVolume")]
    pub total_surface_volume: String,
    #[serde(rename = "surfaceDeficitBalancing")]
    pub surface_deficit_balancing: String,
}
impl Default for UniformGeometricOptions {
    fn default() -> Self {
        Self {
            density_sharpening: "on".into(),
            rigid_coupling: "on".into(),
            time_step: "paper".into(),
            pressure_residual_tolerance: 5_f32,
            extension_front_sweeps: 2_f32,
            pressure_full_cycles: 3_f32,
            pressure_v_cycles: 4_f32,
            pressure_sweeps: 6_f32,
            volume_dust_threshold: 0.001_f32,
            phi_cubic_advection: "on".into(),
            phi_drain: "on".into(),
            total_surface_volume: "on".into(),
            surface_deficit_balancing: "on".into(),
        }
    }
}
impl UniformGeometricOptions {
    pub fn validate(&self) -> Result<(), ValidationError> {
        if !["on", "off"].contains(&self.density_sharpening.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter densitySharpening".into(),
            ));
        }
        if !["on", "off"].contains(&self.rigid_coupling.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter rigidCoupling".into(),
            ));
        }
        if !["paper", "scene"].contains(&self.time_step.as_str()) {
            return Err(ValidationError("Invalid uniform parameter timeStep".into()));
        }
        if !self.pressure_residual_tolerance.is_finite()
            || !((0_f32)..=(100_f32)).contains(&self.pressure_residual_tolerance)
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureResidualTolerance".into(),
            ));
        }
        if !self.extension_front_sweeps.is_finite()
            || !((1_f32)..=(16_f32)).contains(&self.extension_front_sweeps)
            || self.extension_front_sweeps.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter extensionFrontSweeps".into(),
            ));
        }
        if !self.pressure_full_cycles.is_finite()
            || !((0_f32)..=(5_f32)).contains(&self.pressure_full_cycles)
            || self.pressure_full_cycles.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureFullCycles".into(),
            ));
        }
        if !self.pressure_v_cycles.is_finite()
            || !((0_f32)..=(8_f32)).contains(&self.pressure_v_cycles)
            || self.pressure_v_cycles.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureVCycles".into(),
            ));
        }
        if !self.pressure_sweeps.is_finite()
            || !((1_f32)..=(8_f32)).contains(&self.pressure_sweeps)
            || self.pressure_sweeps.fract() != 0.0
        {
            return Err(ValidationError(
                "Invalid uniform parameter pressureSweeps".into(),
            ));
        }
        if !self.volume_dust_threshold.is_finite()
            || !((0_f32)..=(0.001_f32)).contains(&self.volume_dust_threshold)
        {
            return Err(ValidationError(
                "Invalid uniform parameter volumeDustThreshold".into(),
            ));
        }
        if !["on", "off"].contains(&self.phi_cubic_advection.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter phiCubicAdvection".into(),
            ));
        }
        if !["on", "off"].contains(&self.phi_drain.as_str()) {
            return Err(ValidationError("Invalid uniform parameter phiDrain".into()));
        }
        if !["off", "on"].contains(&self.total_surface_volume.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter totalSurfaceVolume".into(),
            ));
        }
        if !["on", "off"].contains(&self.surface_deficit_balancing.as_str()) {
            return Err(ValidationError(
                "Invalid uniform parameter surfaceDeficitBalancing".into(),
            ));
        }
        Ok(())
    }
}
