/**
 * A *lens*: the visualization of one resident solver stage, declared beside it.
 *
 * The catalog next door answers "what can the app draw of the *state*". This
 * answers a different question — "what did this *stage* do" — and the two are
 * not the same picture. A field view samples whatever survived to the end of
 * the frame; a stage ran in the middle of it, consumed one thing, produced
 * another, and the interesting quantity is usually the difference. Nothing in
 * the field vocabulary can show a subtraction, because by the time the frame
 * ends only the result is left.
 *
 * So a lens carries four things a field view does not:
 *
 * - **Phases.** An ordered reading of the stage, scrubbed left to right. A
 *   phase is a *viewpoint on the stage*, never a re-execution of it: nothing
 *   here can make the solver run a kernel again, so a phase can only choose
 *   which of the stage's own facts to draw.
 * - **Taps.** The stage's encoder copies declared publications aside at named
 *   points, but only while the lens is armed. That is the only way an
 *   intermediate reaches the screen at all, and it is why "grey minus red
 *   equals blue" can be *captured* rather than simulated.
 * - **Counters.** The stage's own header words, by name, read back each frame.
 * - **Evidence.** Per layer and per counter, where the number came from. A
 *   derived quantity draws dashed, exactly as a derived decoration does.
 *
 * Everything here is method-agnostic. A lens names its publications, taps and
 * header words by *key*; the method's `StageLensSource` resolves those keys to
 * buffers. Core never learns what a CM12 row record is.
 *
 * ## Why the types are this heavy
 *
 * The standing requirement is that **drift is a TypeScript error**. A stage
 * whose shader evolves must break its lens at `tsc`, not paint a wrong picture.
 * Every generic parameter below exists to make one class of drift unspellable:
 *
 * | The stage changes | The lens says | Breaks at |
 * |---|---|---|
 * | a header word renamed | `counters: [{ word: "workCount" }]` | `keyof Header` |
 * | a publication renamed | `bindings[].resource` | `LensResourceKey` |
 * | a tap renamed | `capture(encoder, "beforeExecute")` | `StageTapSink<keyof Taps>` |
 * | a program renamed | `layers: [{ program: "rows" }]` | `keyof Programs` |
 * | a stage id added | the method's exhaustive `Record<StageId, Lens \| null>` | the record |
 *
 * Runtime magenta is the backstop for what types cannot reach — a tap that was
 * never encoded, a header whose magic does not match — never the primary guard.
 */
import type {
  VisualizationBinding,
  VisualizationProgram,
} from "./visualization-bindings";
import { visualizationProgramProblems } from "./visualization-bindings";
import type { VisualizationLegendEntry } from "./visualization-registry";

/**
 * A buffer a stage exposes to its lens, by key.
 *
 * `kind` and `wgslType` are the same vocabulary a field program's bindings use,
 * because a lens program's preamble is generated by the same emitter. A
 * publication is always read-only from the lens's side: a visualization that
 * could write to the solver's arena is not a visualization.
 */
export interface StagePublication {
  readonly kind: "uniform" | "read-only-storage";
  /** WGSL type of the bound variable. `array<u32>`, `Params`. */
  readonly wgslType: string;
  /**
   * The struct declaration `wgslType` names, when it names one.
   *
   * Emitted ahead of the binding preamble and de-duplicated across a program's
   * bindings. A method's uniform block has to be declared somewhere, and the
   * publication that carries its type is the one place that cannot fall out of
   * step with it.
   */
  readonly wgslStruct?: string;
  /** One phrase, for the legend and for the "unbound" magenta message. */
  readonly label?: string;
}

export type StagePublications = Readonly<Record<string, StagePublication>>;

/** Tap name → the publications snapshotted at that point, by key. */
export type StageTaps<Publications extends StagePublications> =
  Readonly<Record<string, readonly (keyof Publications & string)[]>>;

/**
 * What a lens program may bind: a live publication, or one publication of one
 * tap's snapshot.
 *
 * A template-literal union rather than a string, so `tap:beforeExcute:state`
 * is a compile error and `tap:beforeExecute:pressure` is too when that tap does
 * not snapshot `pressure`. This is the whole reason `Taps` is a generic
 * parameter and not a `string[]`.
 */
export type LensResourceKey<
  Publications extends StagePublications,
  Taps extends StageTaps<Publications>,
> =
  | (keyof Publications & string)
  | {
      [Tap in keyof Taps & string]: `tap:${Tap}:${Taps[Tap][number] & string}`;
    }[keyof Taps & string];

/**
 * The four things a lens can draw.
 *
 * Deliberately a closed set. Each is one instanced render program whose
 * geometry, slice test and camera the framework owns; the lens supplies only a
 * classifier. A fifth kind is a framework change, which is the point — it
 * forces the question "is this really a new *shape*, or a new colour rule for
 * an existing one" to be asked once rather than answered ad hoc per stage.
 *
 * - `row-glyph` — one instance per row (face). A segment along the face, plus
 *   up to three arrows along the face axis: the pre / delta / post triplet.
 * - `cell-tile` — one instance per template cell. A quad filling the cell on
 *   the slice, coloured from a scalar on a *fixed* reference scale.
 * - `cell-glyph` — one instance per template cell. An arrow, ring, dot or
 *   cross at the cell centre.
 * - `brick-frame` — one instance per resident brick. Its outline on the slice.
 */
export type LensLayerKind = "row-glyph" | "cell-tile" | "cell-glyph" | "brick-frame";

/**
 * Where a drawn quantity came from.
 *
 * The same distinction `VisualizationNote.evidence` carries, with two more
 * cases a stage needs. Never add two of these into one total, and never draw
 * `derived` solid.
 *
 * - `live` — a buffer that survived to the end of the frame, read as it is.
 * - `captured` — a tap: the value as it was *at that point inside the stage*.
 * - `derived` — arithmetic over the above. Drawn dashed.
 * - `scheduled` — what the command graph intended. May have been cut short.
 */
export type LensEvidence = "live" | "captured" | "derived" | "scheduled";

/**
 * One instanced draw, and the WGSL that classifies its instances.
 *
 * `wgsl()` returns *only* the classifier — the framework prepends the binding
 * preamble, the method's shared accessor snippets and the layer-kind template.
 * A program that emitted its own `@group(0) @binding(n)` would be the exact
 * hand-maintained agreement `visualization-bindings` exists to delete.
 */
export interface LensProgram<Resource extends string = string> {
  readonly kind: LensLayerKind;
  readonly label: string;
  readonly bindings: readonly VisualizationBinding<Resource>[];
  /**
   * Class index → colour, at most `LENS_PALETTE_SIZE` entries.
   *
   * A palette rather than shader branches so the colours are data the legend
   * can be built from, and so a phase cannot be drawn in a colour no legend row
   * names. Index 0 is what an unclassified instance gets.
   */
  readonly palette: readonly string[];
  /**
   * The reference scale for a `cell-tile`'s scalar, in the scalar's own units.
   *
   * Fixed, never per-frame normalised: a ramp that renormalises every frame
   * makes "before" and "after" look identical, which is precisely the
   * comparison a projection lens exists to show.
   */
  readonly scale?: number;
  readonly wgsl: () => string;
}

export interface LensPhaseLayer<ProgramKey extends string> {
  readonly program: ProgramKey;
  readonly evidence: LensEvidence;
}

export interface LensPhaseCounter<HeaderKey extends string> {
  readonly word: HeaderKey;
  /** Lit in this phase — the phase is where the number is *produced*. */
  readonly lit?: boolean;
}

/** One position of the scrubber. */
export interface LensPhase<ProgramKey extends string, HeaderKey extends string> {
  readonly id: string;
  /** One or two words. The scrubber tick is the only text the lens shows. */
  readonly label: string;
  readonly layers: readonly LensPhaseLayer<ProgramKey>[];
  readonly counters: readonly LensPhaseCounter<HeaderKey>[];
}

/**
 * The stage header a lens reads its counters from.
 *
 * The lens owns the *word table* — the names and their offsets within the
 * header — and the method's source owns *where the header sits*. That split is
 * deliberate: only the resident knows the arena layout, and only the stage's
 * ABI module knows what word 7 means. Neither can drift into the other's
 * business, and a renamed word breaks every `counters` entry that named it.
 */
export interface StageLensHeader<Header extends Readonly<Record<string, number>>> {
  /** Publication the header lives in. */
  readonly resource: string;
  /** Word name → offset from the header base, from the stage's frozen table. */
  readonly words: Header;
  /** Words the readback copies. Usually the stage's whole header. */
  readonly wordCount: number;
  /**
   * Magic the shader compares before trusting the header, when the stage
   * stamps one. A mismatch paints every dependent layer magenta.
   */
  readonly magic?: { readonly word: number; readonly value: number };
}

export interface StageLens<
  StageId extends string = string,
  Publications extends StagePublications = StagePublications,
  Taps extends StageTaps<Publications> = StageTaps<StagePublications>,
  Header extends Readonly<Record<string, number>> = Readonly<Record<string, number>>,
  Programs extends Readonly<
    Record<string, LensProgram<LensResourceKey<Publications, Taps>>>
  > = Readonly<Record<string, LensProgram<string>>>,
> {
  /** The stage this is a lens on. Exhaustively checked by the method's roster. */
  readonly stage: StageId;
  /** Globally unique overlay mode id, `stage-lens/<stage>`. */
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly publications: Publications;
  readonly taps: Taps;
  readonly header: StageLensHeader<Header>;
  readonly programs: Programs;
  readonly phases: readonly LensPhase<keyof Programs & string, keyof Header & string>[];
  readonly legend: readonly VisualizationLegendEntry[];
}

/**
 * A lens with its parameters erased, which is what the renderer and the catalog
 * hold.
 *
 * Written out structurally rather than as `StageLens<string, …>`, because
 * `Header`, `Publications` and `Programs` each appear under a `keyof` and are
 * therefore *invariant*: an instantiation with the widest arguments is not a
 * supertype of a concrete lens, it is an unrelated type. Erasing member by
 * member says what was actually meant — every concrete lens is assignable to
 * this, and reading one back gives strings rather than the literal unions the
 * declaration site had.
 */
export interface AnyStageLens {
  readonly stage: string;
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly publications: StagePublications;
  readonly taps: Readonly<Record<string, readonly string[]>>;
  readonly header: StageLensHeader<Readonly<Record<string, number>>>;
  readonly programs: Readonly<Record<string, LensProgram<string>>>;
  readonly phases: readonly LensPhase<string, string>[];
  readonly legend: readonly VisualizationLegendEntry[];
}

/** At most this many classes in one program's palette. */
export const LENS_PALETTE_SIZE = 8;

/**
 * Declare a lens, inferring every parameter from the object literal.
 *
 * Written as an identity function for the same reason `fieldVisualization` is:
 * the inference has to happen at the declaration site, because that is where
 * the literal types of the tap names, program names and header words exist. A
 * plain `const lens: StageLens = {…}` would widen all of them to `string` and
 * every guarantee in the module comment would evaporate.
 */
export function stageLens<
  StageId extends string,
  Publications extends StagePublications,
  const Taps extends StageTaps<Publications>,
  Header extends Readonly<Record<string, number>>,
  Programs extends Readonly<
    Record<string, LensProgram<LensResourceKey<Publications, Taps>>>
  >,
>(
  lens: StageLens<StageId, Publications, Taps, Header, Programs>,
): StageLens<StageId, Publications, Taps, Header, Programs> {
  return lens;
}

/**
 * How a tap's snapshot of one publication is named in a binding.
 *
 * One function so the string is built in exactly one place; the *type* of the
 * result is checked by `LensResourceKey` at the declaration site.
 */
export function lensTapResource(tap: string, publication: string): string {
  return `tap:${tap}:${publication}`;
}

/** The tap and publication a `tap:…` resource key names, or nothing. */
export function parseLensTapResource(
  resource: string,
): { readonly tap: string; readonly publication: string } | undefined {
  if (!resource.startsWith("tap:")) return undefined;
  const rest = resource.slice(4);
  const split = rest.indexOf(":");
  if (split <= 0 || split === rest.length - 1) return undefined;
  return { tap: rest.slice(0, split), publication: rest.slice(split + 1) };
}

/**
 * Resource key of the framework's own uniform block.
 *
 * Reserved rather than declarable: every layer template reads the camera, the
 * slice and the palette from it, so a lens that could forget to bind it would
 * be a lens that compiles and draws nothing. It is prepended to every program,
 * which is also why it is `@binding(0)` in every generated preamble.
 */
export const STAGE_LENS_UNIFORM_RESOURCE = "stage-lens/uniform";

/** WGSL identifier the layer templates read the framework uniform through. */
export const STAGE_LENS_UNIFORM_NAME = "lens";

/** WGSL type name of the framework uniform block. */
export const STAGE_LENS_UNIFORM_TYPE = "StageLensUniforms";

/**
 * A lens program as the binding emitter sees it: the framework's uniform, then
 * everything the lens declared.
 *
 * The lens vocabulary and the field vocabulary agree on what a binding is, so
 * the preamble generator, the budget arithmetic and the bind-group builder are
 * shared rather than reimplemented. Prepending here rather than asking the lens
 * to declare slot 0 is what keeps slot numbers out of every lens: the emitter
 * still decides them, and it decides them for one longer list.
 */
export function lensBindingProgram(
  lens: AnyStageLens,
  program: string,
): VisualizationProgram {
  const declared = lens.programs[program];
  return {
    id: `${lens.id}#${program}`,
    label: declared?.label ?? program,
    bindings: [
      {
        name: STAGE_LENS_UNIFORM_NAME,
        kind: "uniform",
        type: STAGE_LENS_UNIFORM_TYPE,
        resource: STAGE_LENS_UNIFORM_RESOURCE,
      },
      ...(declared?.bindings ?? []),
    ],
  };
}

/**
 * Every reason a lens cannot be built, or nothing.
 *
 * Returned rather than thrown so one test can report a whole catalog's problems
 * at once, in the shape `visualizationProgramProblems` already established.
 * Everything here *except* the resource-existence checks is also a `tsc` error
 * at a well-typed declaration site; the runtime form exists because the catalog
 * is assembled from erased lenses and a hand-written cast would slip past.
 */
export function stageLensProblems(lens: AnyStageLens): readonly string[] {
  const problems: string[] = [];
  const publications = new Set(Object.keys(lens.publications));
  const programs = new Set(Object.keys(lens.programs));
  const words = new Set(Object.keys(lens.header.words));

  if (!publications.has(lens.header.resource)) {
    problems.push(`${lens.id}: header reads "${lens.header.resource}", which is not a publication`);
  }
  for (const [tap, snapshotted] of Object.entries(lens.taps)) {
    for (const publication of snapshotted) {
      if (!publications.has(publication)) {
        problems.push(`${lens.id}: tap "${tap}" snapshots "${publication}", which is not a publication`);
      }
    }
  }
  for (const [name, program] of Object.entries(lens.programs)) {
    problems.push(...visualizationProgramProblems(lensBindingProgram(lens, name)));
    if (program.palette.length === 0) {
      problems.push(`${lens.id}#${name}: no palette; class 0 has no colour`);
    }
    if (program.palette.length > LENS_PALETTE_SIZE) {
      problems.push(
        `${lens.id}#${name}: ${program.palette.length} palette entries, `
        + `${LENS_PALETTE_SIZE} is the uniform's capacity`);
    }
    for (const binding of program.bindings) {
      const tapped = parseLensTapResource(binding.resource);
      if (!tapped) {
        if (!publications.has(binding.resource)) {
          problems.push(`${lens.id}#${name}: binds "${binding.resource}", which is not a publication`);
        }
        continue;
      }
      const declared = lens.taps[tapped.tap];
      if (!declared) {
        problems.push(`${lens.id}#${name}: binds tap "${tapped.tap}", which the lens does not declare`);
      } else if (!declared.includes(tapped.publication)) {
        problems.push(
          `${lens.id}#${name}: binds "${tapped.publication}" of tap "${tapped.tap}", `
          + `which that tap does not snapshot`);
      }
    }
  }
  if (lens.phases.length === 0) problems.push(`${lens.id}: no phases; the scrubber would have nothing to sit on`);
  const phaseIds = new Set<string>();
  for (const phase of lens.phases) {
    if (phaseIds.has(phase.id)) problems.push(`${lens.id}: duplicate phase id "${phase.id}"`);
    phaseIds.add(phase.id);
    for (const layer of phase.layers) {
      if (!programs.has(layer.program)) {
        problems.push(`${lens.id}: phase "${phase.id}" draws program "${layer.program}", which does not exist`);
      }
    }
    for (const counter of phase.counters) {
      if (!words.has(counter.word)) {
        problems.push(`${lens.id}: phase "${phase.id}" lights word "${counter.word}", which the header does not name`);
      }
    }
  }
  return problems;
}

/**
 * The receipt one armed lens publishes each frame.
 *
 * `capturedTaps < expectedTaps` is the case types cannot reach: a tap the lens
 * declared whose `capture()` the stage never ran, because the branch it sits in
 * did not execute this frame. The dependent phases paint magenta and the
 * scrubber shows the shortfall — absence is drawn, never silent.
 */
export interface StageLensReceipt {
  readonly lensId: string;
  readonly armed: boolean;
  /** Taps the lens declares. */
  readonly expectedTaps: number;
  /** Taps whose `capture()` actually encoded this frame. */
  readonly capturedTaps: number;
  /** Whether the header's magic and version matched. */
  readonly headerValid: boolean;
  /** Header words by name, decoded with the lens's own table. */
  readonly counters: Readonly<Record<string, number>>;
  /**
   * Advances the method had encoded when these counters were read.
   *
   * Its only job is to date the receipt: a panel showing a step older than the
   * frame on screen is showing a readback that has not landed yet, which is
   * ordinary and worth being able to see.
   */
  readonly step: number;
}

/**
 * What a method hands the renderer so its lenses can draw.
 *
 * The method owns every buffer and every offset; core owns the pipelines and
 * the phases. `arm` is the whole cost model: nothing is copied, read back or
 * even compiled until someone opens a lens, and disarming frees the snapshots.
 */
export interface StageLensSource {
  readonly lenses: readonly AnyStageLens[];
  /** Live buffer for a publication key. */
  publication(key: string): GPUBufferBinding | undefined;
  /** Snapshot buffer for one publication of one tap, once armed and captured. */
  snapshot(lensId: string, tap: string, publication: string): GPUBufferBinding | undefined;
  /**
   * Arm one lens, or none. Returns false for an id the source does not know.
   *
   * Idempotent: arming the lens that is already armed does nothing, which is
   * what makes it safe to call unconditionally every frame from the renderer.
   */
  arm(lensId: string | undefined): boolean;
  /** The lens that is armed, if any. Read by the perf probe: must be undefined. */
  readonly armed: string | undefined;
  receipt(lensId: string): StageLensReceipt | undefined;
  /** Lattice the layer templates map instances into. */
  readonly space: {
    readonly dimensions: readonly [number, number, number];
    readonly origin_m: readonly [number, number, number];
    readonly extent_m: readonly [number, number, number];
  };
  /** Instance counts, by what the layer kind iterates. */
  readonly capacities: {
    readonly rows: number;
    readonly cells: number;
    readonly bricks: number;
  };
}

/**
 * A lens's id, which is also its overlay mode.
 *
 * One string rather than two so nothing has to map between "the mode the URL
 * carries" and "the lens the source knows". The prefix is what lets the URL
 * parser recognise a lens it has never heard of — a mode for a stage that only
 * one method declares still round-trips through a link.
 */
export type StageLensOverlayMode = `stage-lens/${string}`;

/** The overlay mode for a stage id. The only place the prefix is written. */
export function stageLensOverlayMode(stage: string): StageLensOverlayMode {
  return `stage-lens/${stage}`;
}

/**
 * Whether a mode string names a lens.
 *
 * Exported for the URL parser's guard chain, whose default silently rewrites an
 * unrecognised mode to `structure`. A lens mode that is not in that chain is a
 * link that quietly opens the wrong view on reload.
 */
export function isStageLensOverlayMode(value: string): value is StageLensOverlayMode {
  return value.startsWith("stage-lens/") && value.length > "stage-lens/".length;
}

/** The stage a lens mode names, or nothing. */
export function stageLensOverlayStage(value: string): string | undefined {
  return isStageLensOverlayMode(value) ? value.slice("stage-lens/".length) : undefined;
}

/**
 * What a stage's encode body calls to snapshot its taps.
 *
 * `Tap` is the lens's own tap names, so a stage that renames a seam breaks its
 * capture call at `tsc` rather than encoding nothing and painting magenta. A
 * stage with no lens gets `StageTapSink<never>`, which accepts no argument at
 * all — the roster is exhaustive, so "this stage has no lens yet" is spelled
 * the same way as "this stage has a lens with no taps".
 */
export interface StageTapSink<Tap extends string> {
  capture(tap: Tap): void;
}
