import type { SceneDescription } from "./model";
import { bakePondVesselTerrain, pondVesselHeightAt, pondVesselPlanCurve, type PondVesselSpec } from "./voxel-scenery/pond-vessel";

/**
 * Analytic terrain heightfield shared by every solver, the renderer and the
 * rigid-body contact solver. The tall-cell paper models the ground as a
 * per-column height H_{i,k}; here the scene carries a compact analytic spec
 * (a base ground level plus smooth elliptical basins and mounds) and each
 * consumer evaluates or bakes the same closed-form height, so the CPU seed,
 * the GPU kernels and the rendered grass always agree exactly.
 *
 * Heights are metres above the container floor (y = 0). A scene without a
 * `terrain` block behaves exactly as before: a flat solid floor at y = 0.
 */

export interface TerrainFeature {
  kind: "basin" | "mound";
  /** Footprint centre in world metres (container-centred x/z, like bodies). */
  center_m: { x: number; z: number };
  /** Elliptical footprint semi-axes in metres. */
  radius_m: { x: number; z: number };
  /** Basin depth or mound height in metres (always positive). */
  amount_m: number;
  /** Footprint rotation about +Y in radians. */
  rotation_rad?: number;
  /** Fraction of the radius that is a flat plateau/floor, in [0, 1). */
  flat?: number;
}

/**
 * Sampled ground heights on a regular lattice, for brush sculpting that the
 * 8-feature analytic form cannot express.
 *
 * Heights sit at node positions `origin_m + (i, j) * spacing_m`, row-major
 * `i + nx * j` — the same layout `terrainColumnHeights` bakes, so solvers need
 * no kernel change: they already consume terrain as baked column heights.
 */
export interface TerrainGrid {
  kind: "grid";
  /** World position of sample (0, 0), container-centred like features. */
  origin_m: { x: number; z: number };
  spacing_m: number;
  size: { nx: number; nz: number };
  /** Row-major heights in metres above the container floor. */
  heights_m: number[];
}

/** Bound on an authored grid, keeping documents loadable and JSON sane. */
export const MAX_TERRAIN_GRID_SAMPLES = 262_144;
export const MIN_TERRAIN_GRID_SIZE = 2;

/**
 * Bound on a grid nothing serializes.
 *
 * `MAX_TERRAIN_GRID_SAMPLES` is a *document* budget: a `number[]` of authored
 * heights is JSON, it round-trips through `cloneScene`, it is structured-cloned
 * into the render worker on every scene revision, and at a quarter of a million
 * samples that is already 4.3 MB and 18.5 ms of a frame. A grid that is derived
 * on demand from a description pays none of that — it is built once per lattice
 * and shared by identity — so the only thing left to bound is host memory, and
 * this is set where the grid is still comfortably smaller than the octree it is
 * feeding (16.8 M samples is 134 MB of `number[]`, against the 9.99 GB staging
 * buffer the tree itself asks for two rungs down).
 */
export const MAX_TERRAIN_DERIVED_GRID_SAMPLES = 16_777_216;

/**
 * Ground the document *describes* instead of carrying.
 *
 * The hero pond was the case that forced this. Its vessel is generated by a
 * closed-form function of (x, z) — `pondVesselHeightAt` — and the document was
 * shipping a quarter of a million baked samples of it, which cost 4.32 MB of a
 * 4.34 MB scene and 18.5 ms of its 18.6 ms `structuredClone`. Worse, the
 * document budget above coarsened the bake to 3.125 mm *whatever lattice the
 * picture was drawn at*, so at a 0.78 mm leaf the ground sat up to 2.75 leaves
 * from the surface that was authored: smaller boxes wrapped around coarser
 * geometry, and 37 148 coverage holes at the first refinement rung.
 *
 * So the document carries the parameters and the grid is derived at the lattice
 * in use. Nothing downstream learns a new sampling path — `terrainSampleGrid`
 * hands every consumer the same `TerrainGrid` a bake would have produced, the
 * WGSL mirror still bilinearly samples one heightfield, and the derived grid is
 * memoized by content so the derivation happens once per (description, lattice)
 * rather than once per publication.
 */
export interface TerrainProceduralPondVessel {
  readonly kind: "pond-vessel";
  readonly spec: PondVesselSpec;
  /** The footprint the grid spans; heights clamp to its height. */
  readonly container: { readonly width_m: number; readonly height_m: number; readonly depth_m: number };
  /**
   * Node pitch of the lattice every height query is answered on.
   *
   * This is the one number that used to be decided by the document budget and
   * is now decided by the picture: half the detail cell, so every finest column
   * centre lands exactly on a node and the ground the voxeliser sees is the
   * ground that was generated. See `heroGardenTerrainSample_m`.
   */
  readonly spacing_m: number;
}

export type TerrainProcedural = TerrainProceduralPondVessel;

export interface TerrainDescription {
  /** Ground level in metres above the container floor before features. */
  baseHeight_m: number;
  features: TerrainFeature[];
  /**
   * Sculpted heights. When present this *supersedes* `baseHeight_m` and
   * `features` for every height query — the analytic fields are retained only
   * as provenance for the bake that produced the grid.
   */
  grid?: TerrainGrid;
  /**
   * A generated ground, described rather than baked. Supersedes `baseHeight_m`
   * and `features` exactly as `grid` does, and is superseded *by* `grid` — a
   * brush stroke bakes the description down and the description stops being
   * consulted, because from that moment the samples are the authority.
   */
  procedural?: TerrainProcedural;
}

/**
 * The grid every consumer samples, derived if the document only described one.
 *
 * Two caches, because the scene crosses a realm boundary. Inside one realm the
 * description object is stable across calls, so a `WeakMap` answers in a few
 * nanoseconds and `terrainHeightAt` stays cheap enough for the millions of
 * evaluations a CPU ray march makes. Across the render-worker boundary the
 * scene is structured-cloned every revision and *every* object identity is new,
 * so the `WeakMap` can never hit there — which is exactly the trap that made
 * repeated authoring-grid derivation expensive. The content key is
 * what actually survives the clone, and it is cheap to compute because the
 * description is a few dozen numbers rather than a few hundred thousand.
 */
const derivedGridByDescription = new WeakMap<TerrainProcedural, TerrainGrid>();
const derivedGridByContent = new Map<string, TerrainGrid>();
/** One lattice in use, one being switched to, one being switched back from. */
const MAX_DERIVED_GRID_CACHE_ENTRIES = 3;

/** Serializable identity of a procedural ground; the derived cache's key. */
export function terrainProceduralKey(procedural: TerrainProcedural): string {
  return JSON.stringify(procedural);
}

function bakeProceduralTerrain(procedural: TerrainProcedural): TerrainGrid {
  if (procedural.kind !== "pond-vessel") {
    throw new RangeError(`Unsupported procedural terrain kind ${String((procedural as { kind?: unknown }).kind)}`);
  }
  return bakePondVesselTerrain(procedural.spec, procedural.container, procedural.spacing_m,
    MAX_TERRAIN_DERIVED_GRID_SAMPLES);
}

/**
 * A point query answers from the *nodes it needs*, never from a whole grid.
 *
 * "The ground follows the lattice" is what a 4609x3073 derivation looks like at
 * a 0.78 mm leaf — 14.2 M samples and 35 s — and there is no way around paying
 * that for a consumer that genuinely wants every sample (the GPU heightfield).
 * But most consumers do not: `check:scenery` seats a few hundred props,
 * `terrainColumnHeightsForLattice` wants one height per column, and a CPU ray
 * march wants a few thousand along a ray. Building 14.2 M samples to answer a
 * few hundred questions turned the shared scenery lane from 6 s into 37 s.
 *
 * So the four nodes a bilinear fetch needs are evaluated on demand, in the same
 * expression order `sampleTerrainGrid` uses. That is not "close enough" — it is
 * the identical arithmetic on identical inputs, so a point query and the derived
 * grid return the same f64 bit pattern, and a lane that materializes the grid
 * later cannot disagree with one that did not. Zero-weight corners are skipped,
 * which is also exact (`a * 1 + b * 0` is `a` for finite `b`), so a query that
 * lands on a node — every column centre, by the alignment rule — costs exactly
 * one evaluation of the generator.
 */
const proceduralCurveCache = new WeakMap<TerrainProcedural, readonly (readonly [number, number])[]>();

function proceduralPlanCurve(procedural: TerrainProcedural): readonly (readonly [number, number])[] {
  let curve = proceduralCurveCache.get(procedural);
  if (!curve) proceduralCurveCache.set(procedural, curve = pondVesselPlanCurve(procedural.spec));
  return curve;
}

export function sampleProceduralTerrain(procedural: TerrainProcedural, x: number, z: number): number {
  // A materialized grid is cheaper than four generator evaluations, and by
  // construction carries the same numbers, so prefer it whenever it exists.
  const materialized = derivedGridByDescription.get(procedural);
  if (materialized) return sampleTerrainGrid(materialized, x, z);
  if (procedural.kind !== "pond-vessel") {
    throw new RangeError(`Unsupported procedural terrain kind ${String((procedural as { kind?: unknown }).kind)}`);
  }
  const { spec, container, spacing_m } = procedural;
  const curve = proceduralPlanCurve(procedural);
  const nx = Math.max(MIN_TERRAIN_GRID_SIZE, Math.ceil(container.width_m / spacing_m) + 1);
  const nz = Math.max(MIN_TERRAIN_GRID_SIZE, Math.ceil(container.depth_m / spacing_m) + 1);
  const originX = -.5 * container.width_m, originZ = -.5 * container.depth_m;
  // Exactly `bakePondVesselTerrain`'s stored sample, including its clamp.
  const at = (i: number, j: number): number => Math.min(container.height_m,
    Math.max(0, pondVesselHeightAt(spec, curve, originX + i * spacing_m, originZ + j * spacing_m)));
  const fx = Math.min(nx - 1, Math.max(0, (x - originX) / spacing_m));
  const fz = Math.min(nz - 1, Math.max(0, (z - originZ) / spacing_m));
  const x0 = Math.min(nx - 2, Math.floor(fx)), z0 = Math.min(nz - 2, Math.floor(fz));
  const tx = fx - x0, tz = fz - z0;
  const row = (j: number) => tx === 0 ? at(x0, j) : at(x0, j) * (1 - tx) + at(x0 + 1, j) * tx;
  const lower = row(z0);
  return Math.max(0, tz === 0 ? lower : lower * (1 - tz) + row(z0 + 1) * tz);
}

export function terrainSampleGrid(terrain: TerrainDescription | undefined): TerrainGrid | undefined {
  if (!terrain) return undefined;
  if (terrain.grid) return terrain.grid;
  const procedural = terrain.procedural;
  if (!procedural) return undefined;
  const memoized = derivedGridByDescription.get(procedural);
  if (memoized) return memoized;
  const key = terrainProceduralKey(procedural);
  let grid = derivedGridByContent.get(key);
  if (!grid) {
    grid = bakeProceduralTerrain(procedural);
    derivedGridByContent.set(key, grid);
    while (derivedGridByContent.size > MAX_DERIVED_GRID_CACHE_ENTRIES) {
      const oldest = derivedGridByContent.keys().next().value;
      if (oldest === undefined) break;
      derivedGridByContent.delete(oldest);
    }
  }
  derivedGridByDescription.set(procedural, grid);
  return grid;
}

/**
 * Pitch and node count of the sampling lattice, without building it.
 *
 * Every diagnostic that reports "terrain baked at N mm (nx x nz)" wants exactly
 * this and nothing else, and forcing a derivation to print a line would be a
 * multi-second stall in a status string.
 */
export interface TerrainSampleShape {
  spacing_m: number;
  nx: number;
  nz: number;
  /** True when the samples are described rather than carried by the document. */
  derived: boolean;
}

export function terrainSampleShape(terrain: TerrainDescription | undefined): TerrainSampleShape | undefined {
  if (terrain?.grid) {
    return { spacing_m: terrain.grid.spacing_m, nx: terrain.grid.size.nx, nz: terrain.grid.size.nz, derived: false };
  }
  const procedural = terrain?.procedural;
  if (!procedural) return undefined;
  const { container, spacing_m } = procedural;
  return {
    spacing_m,
    nx: Math.max(MIN_TERRAIN_GRID_SIZE, Math.ceil(container.width_m / spacing_m) + 1),
    nz: Math.max(MIN_TERRAIN_GRID_SIZE, Math.ceil(container.depth_m / spacing_m) + 1),
    derived: true,
  };
}

/**
 * Serializable identity for every authored value that can change the ground.
 *
 * Object identity is useful inside one realm, but it is deliberately not part
 * of the structured-clone contract used by the render worker. Two independent
 * 32-bit streams keep this compact while avoiding JSON serialization of grids
 * containing hundreds of thousands of samples. Grid samples are folded as
 * f32 words because that is the precision ultimately uploaded to WebGPU.
 */
export function terrainContentStamp(terrain: TerrainDescription | undefined): string {
  if (!terrain) return "terrain-v1:none";
  let low = 0x811c_9dc5, high = 0x9e37_79b9;
  const fold = (word: number) => {
    low = Math.imul(low ^ word, 0x0100_0193) >>> 0;
    high = Math.imul(high ^ (word >>> 16 | word << 16), 0x85eb_ca6b) >>> 0;
  };
  const descriptor = JSON.stringify({
    baseHeight_m: terrain.baseHeight_m,
    features: terrain.features.map((feature) => ({
      kind: feature.kind,
      center_m: feature.center_m,
      radius_m: feature.radius_m,
      amount_m: feature.amount_m,
      rotation_rad: feature.rotation_rad ?? null,
      flat: feature.flat ?? null,
    })),
    grid: terrain.grid ? {
      kind: terrain.grid.kind,
      origin_m: terrain.grid.origin_m,
      spacing_m: terrain.grid.spacing_m,
      size: terrain.grid.size,
    } : null,
    // A described ground folds its *description*. The samples are a pure
    // function of it, so folding them as well would only be a slower way of
    // reaching the same answer — and it would force a derivation on a path
    // (the worker hand-off) whose whole point is not to touch the heights.
    procedural: terrain.procedural ?? null,
  });
  for (let index = 0; index < descriptor.length; index += 1) fold(descriptor.charCodeAt(index));
  if (terrain.grid) {
    const sample = new Float32Array(1);
    const word = new Uint32Array(sample.buffer);
    for (const height of terrain.grid.heights_m) {
      sample[0] = height;
      fold(word[0]);
    }
  }
  return `terrain-v1:${high.toString(16).padStart(8, "0")}${low.toString(16).padStart(8, "0")}`;
}

/** Bilinear sample with clamped edges; the exact form the WGSL mirror must use. */
export function sampleTerrainGrid(grid: TerrainGrid, x: number, z: number): number {
  const { nx, nz } = grid.size;
  const fx = Math.min(nx - 1, Math.max(0, (x - grid.origin_m.x) / grid.spacing_m));
  const fz = Math.min(nz - 1, Math.max(0, (z - grid.origin_m.z) / grid.spacing_m));
  const x0 = Math.min(nx - 2, Math.floor(fx)), z0 = Math.min(nz - 2, Math.floor(fz));
  const tx = fx - x0, tz = fz - z0;
  const at = (i: number, j: number) => grid.heights_m[i + nx * j] ?? 0;
  const lower = at(x0, z0) * (1 - tx) + at(x0 + 1, z0) * tx;
  const upper = at(x0, z0 + 1) * (1 - tx) + at(x0 + 1, z0 + 1) * tx;
  return Math.max(0, lower * (1 - tz) + upper * tz);
}

/** Uniform-buffer capacity shared with the WGSL evaluators. */
export const MAX_TERRAIN_FEATURES = 8;
/**
 * Overlapping basins merge through a p-norm smooth maximum of their carve
 * depths: exact for a single basin and in the far field (no equality bias),
 * smooth in overlaps with a bounded 2^(1/p) deepening where basins coincide.
 */
export const TERRAIN_UNION_EXPONENT = 8;
export const TERRAIN_DEFAULT_FLAT = 0.45;

function featureWeight(feature: TerrainFeature, x: number, z: number): number {
  const rotation = feature.rotation_rad ?? 0;
  const cos = Math.cos(rotation);
  const sin = Math.sin(rotation);
  const dx = x - feature.center_m.x;
  const dz = z - feature.center_m.z;
  const localX = (cos * dx + sin * dz) / feature.radius_m.x;
  const localZ = (-sin * dx + cos * dz) / feature.radius_m.z;
  const distance = Math.hypot(localX, localZ);
  const flat = feature.flat ?? TERRAIN_DEFAULT_FLAT;
  if (distance <= flat) return 1;
  if (distance >= 1) return 0;
  const s = 1 - (distance - flat) / (1 - flat);
  return s * s * (3 - 2 * s);
}

/** Ground height in metres above the container floor at world (x, z). */
export function terrainHeightAt(terrain: TerrainDescription | undefined, x: number, z: number): number {
  if (!terrain) return 0;
  if (terrain.grid) return sampleTerrainGrid(terrain.grid, x, z);
  // Deliberately not `terrainSampleGrid`: a point query must never be the thing
  // that materializes a fourteen-million-sample ground. See
  // `sampleProceduralTerrain`, which answers with the same bits.
  if (terrain.procedural) return sampleProceduralTerrain(terrain.procedural, x, z);
  return describedTerrainHeightAt(terrain, x, z);
}

/** The eight-feature closed form alone, for callers that already resolved the grid. */
function describedTerrainHeightAt(terrain: TerrainDescription, x: number, z: number): number {
  let mounds = 0;
  let carvePower = 0;
  for (const feature of terrain.features) {
    const weight = featureWeight(feature, x, z);
    if (feature.kind === "mound") mounds += feature.amount_m * weight;
    else carvePower += (feature.amount_m * weight) ** TERRAIN_UNION_EXPONENT;
  }
  const carve = carvePower > 0 ? carvePower ** (1 / TERRAIN_UNION_EXPONENT) : 0;
  return Math.max(0, terrain.baseHeight_m + mounds - carve);
}

/** Outward terrain surface normal at world (x, z), by central differences. */
export function terrainNormalAt(terrain: TerrainDescription | undefined, x: number, z: number, epsilon_m = 0.02) {
  const gradientX = (terrainHeightAt(terrain, x + epsilon_m, z) - terrainHeightAt(terrain, x - epsilon_m, z)) / (2 * epsilon_m);
  const gradientZ = (terrainHeightAt(terrain, x, z + epsilon_m) - terrainHeightAt(terrain, x, z - epsilon_m)) / (2 * epsilon_m);
  const inverseLength = 1 / Math.hypot(gradientX, 1, gradientZ);
  return { x: -gradientX * inverseLength, y: inverseLength, z: -gradientZ * inverseLength };
}

export function sceneHasTerrain(scene: Pick<SceneDescription, "terrain">): boolean {
  const terrain = scene.terrain;
  return !!terrain
    && (terrain.baseHeight_m > 0 || terrain.features.length > 0 || !!terrain.grid || !!terrain.procedural);
}

/** True when the ground is a heightfield rather than the eight-feature closed form. */
export function terrainIsSculpted(terrain: TerrainDescription | undefined): boolean {
  return !!terrain?.grid || !!terrain?.procedural;
}

/**
 * Clearance every ray marcher leaves above the tallest ground sample before it
 * starts looking for the surface. Small enough that the bracket is not mostly
 * empty sky, large enough that a ray entering exactly at the crest still starts
 * outside the solid.
 */
export const TERRAIN_CEILING_MARGIN_M = 0.05;

export interface TerrainGridExtent {
  /** Lowest and highest sample, and therefore of the bilinear surface itself. */
  minimum_m: number;
  maximum_m: number;
  /**
   * Lipschitz bound on |grad h|, in metres of rise per metre of run.
   *
   * Bilinear interpolation is a convex combination along each axis, so the
   * surface's slope inside a cell never exceeds the largest slope along that
   * cell's edges, and the largest edge slope in the whole grid therefore bounds
   * the whole surface. That is what makes a ray march over sculpted ground
   * *provably* unable to step over a feature: the field y - h(p(t)) changes by
   * at most |rd.y| + slopeBound * |rd.xz| per metre of ray, so a step of
   * |field| divided by that quantity cannot cross a root.
   */
  slopeBound: number;
}

/**
 * One pass over a sculpted grid, cached on the grid object.
 *
 * `bakePondVesselTerrain` produces ~56k samples for the hero pond and the
 * ceiling is wanted per frame by the renderer and per publication by the voxel
 * planner, so this is memoized the same way `sectionModulation` memoizes the
 * pond's per-lobe modulation: keyed on identity in a `WeakMap`, because the
 * grid is immutable once baked and a brush stroke returns a new one.
 */
const gridExtentCache = new WeakMap<TerrainGrid, TerrainGridExtent>();
export function terrainGridExtent(grid: TerrainGrid): TerrainGridExtent {
  const cached = gridExtentCache.get(grid);
  if (cached) return cached;
  const { nx, nz } = grid.size;
  let minimum_m = Infinity, maximum_m = -Infinity, largestRise = 0;
  for (let j = 0; j < nz; j += 1) for (let i = 0; i < nx; i += 1) {
    const height = grid.heights_m[i + nx * j] ?? 0;
    if (height < minimum_m) minimum_m = height;
    if (height > maximum_m) maximum_m = height;
    if (i + 1 < nx) largestRise = Math.max(largestRise, Math.abs((grid.heights_m[i + 1 + nx * j] ?? 0) - height));
    if (j + 1 < nz) largestRise = Math.max(largestRise, Math.abs((grid.heights_m[i + nx * (j + 1)] ?? 0) - height));
  }
  // Both axes can be that steep at once, so the gradient magnitude bound is the
  // diagonal of the per-axis bound rather than the bound itself.
  const extent: TerrainGridExtent = {
    minimum_m: Number.isFinite(minimum_m) ? minimum_m : 0,
    maximum_m: Number.isFinite(maximum_m) ? maximum_m : 0,
    slopeBound: Math.SQRT2 * largestRise / grid.spacing_m,
  };
  gridExtentCache.set(grid, extent);
  return extent;
}

/**
 * Upper bound on the ground, plus the bracket margin. The one definition every
 * consumer uses, which is the whole point of it existing.
 *
 * Both ray-marching mirrors used to compute this as `baseHeight_m` plus the sum
 * of the analytic mound amounts. For a sculpted terrain that sum is zero — the
 * analytic fields are only provenance once a grid is present — so the bracket
 * began 5 cm above the *base* ground and clipped away every sculpted feature
 * taller than that. The hero pond's coping is 5.5 cm, so the bug removed
 * precisely the thing the vessel exists to draw. The voxelization candidate
 * bounds had the same hole and stopped a brick short of the crest.
 */
export function terrainCeiling(terrain: TerrainDescription | undefined): number {
  if (!terrain) return TERRAIN_CEILING_MARGIN_M;
  const grid = terrainSampleGrid(terrain);
  if (grid) return terrainGridExtent(grid).maximum_m + TERRAIN_CEILING_MARGIN_M;
  const mounds = terrain.features.reduce((sum, feature) => sum + (feature.kind === "mound" ? feature.amount_m : 0), 0);
  return terrain.baseHeight_m + mounds + TERRAIN_CEILING_MARGIN_M;
}

/** An arbitrary column lattice to bake ground heights onto. */
export interface TerrainColumnLattice {
  /** World position of the lattice's minimum corner, not of its first sample. */
  originX_m: number;
  originZ_m: number;
  cellX_m: number;
  cellZ_m: number;
  nx: number;
  nz: number;
  /** Heights are clamped here, as every solver's column texture assumes. */
  maximumHeight_m: number;
}

/**
 * Bake per-column ground heights (metres) at the centres of any cell lattice.
 * Row-major, index x + nx * z — the layout every solver's column texture uses.
 *
 * Extracted from {@link terrainColumnHeights} because the ground has two
 * consumers with two different lattices and exactly one definition. The solver
 * wants the container footprint; the render octree wants its own domain, which
 * is wider than the container wherever scenery stands outside it — and a bake
 * that stopped at the container would leave that ground out of the opacity
 * pyramid while the analytic marcher kept drawing it, which is the same
 * mismatch (ground drawn, ground not occluding) this bake exists to remove.
 *
 * Outside an authored grid the height clamps to the edge sample, exactly as
 * `sampleTerrainGrid` does, so the wider lattice extends the ground rather than
 * inventing one.
 */
/**
 * The description's own grid, when a bulk sweep of `columns` queries pays for it.
 *
 * `sampleProceduralTerrain` deliberately never materializes on a *point* query,
 * and that stays true — a status line asking for one height must not stall for
 * seconds. A lattice sweep is the opposite situation: it already knows how many
 * queries it is about to make, so it can compare that against the derivation
 * and pick the cheaper one. One derivation is `nx * nz` generator evaluations;
 * `columns` point queries are `4 * columns` of them, so the derivation is ahead
 * as soon as the sweep asks for more than a quarter of the grid's own nodes.
 *
 * `undefined` when there is nothing to derive, when the sweep is too small, or
 * when the grid would exceed the host budget the derivation is bounded by —
 * every one of which leaves the caller on the unchanged point-query path.
 */
function terrainDerivedGridForBulkSampling(
  terrain: TerrainDescription,
  columns: number,
): TerrainGrid | undefined {
  if (!terrain.procedural) return undefined;
  const shape = terrainSampleShape(terrain);
  if (!shape) return undefined;
  const nodes = shape.nx * shape.nz;
  if (nodes > MAX_TERRAIN_DERIVED_GRID_SAMPLES) return undefined;
  if (columns * 4 < nodes) return undefined;
  return terrainSampleGrid(terrain);
}

export function terrainColumnHeightsForLattice(
  terrain: TerrainDescription | undefined,
  lattice: TerrainColumnLattice,
): Float32Array<ArrayBuffer> {
  const steps = terrainColumnHeightsForLatticeSteps(terrain, lattice);
  for (;;) { const step = steps.next(); if (step.done) return step.value; }
}

/**
 * The same bake, offered a row at a time.
 *
 * One of the long unyielding blocks a scene build used to be made of: on
 * `hero-garden-hose` it is 3.5 M columns and 752 ms at environment refinement
 * depth 3, against 190 ms at depth 2 and 51 ms at depth 1 — measured directly,
 * with no GPU involved. Held on one thread, that is 752 ms in which the render
 * worker cannot answer a frame or notice that the request it is serving has
 * been superseded, which on a control whose whole purpose is to be moved is
 * the difference between a slider and a stall. Offered a few rows at a time it
 * is 1 ms of granularity instead.
 *
 * A row rather than a column: rows are contiguous in the row-major layout every
 * consumer reads, so a suspended bake is always a whole prefix of the output
 * and never a partially written row. Nothing but this function's own array
 * exists at a yield, so an abandoned bake is collected rather than released —
 * and it is never memoized by this iterator.
 *
 * What is *not* sliced is the derivation above the loop: the first build of a
 * procedural ground pays one `bakeProceduralTerrain`, measured at 282 ms on
 * this scene, and every build after it hits the content-keyed cache. That is a
 * startup cost rather than a rebuild cost, which is why it is left whole.
 */
export function* terrainColumnHeightsForLatticeSteps(
  terrain: TerrainDescription | undefined,
  lattice: TerrainColumnLattice,
): Generator<unknown, Float32Array<ArrayBuffer>, undefined> {
  const { originX_m, originZ_m, cellX_m, cellZ_m, nx, nz, maximumHeight_m } = lattice;
  const heights = new Float32Array(new ArrayBuffer(nx * nz * Float32Array.BYTES_PER_ELEMENT));
  if (!terrain) return heights;
  // The dispatch is resolved once rather than per column: this runs over every
  // finest column of the render domain — 221k of them at the shipping leaf and
  // four times that a rung down.
  //
  // A *described* ground resolves one step further, and this is the difference
  // between a bake that costs 0.3 s and one that costs 7 s. An unmaterialized
  // `sampleProceduralTerrain` bilinearly interpolates four live generator
  // evaluations per query — 5.1 us on the hero pond, against 0.25 us once the
  // description's own grid exists. Bulk is exactly the case where materializing
  // is right: the generator's lattice is fixed by `spacing_m` and does not grow
  // with the render domain, so past the crossover this bake would otherwise
  // evaluate the generator many times *per stored node of a grid it could have
  // built once*. Measured on `hero-garden-hose` at environment refinement depth
  // 2: 1.40 M columns, 6.99 s before and 0.35 s after, and 22.7 % of the whole
  // scene build.
  //
  // Below the crossover the point-query path still wins, and it is still the
  // only path for a lattice too small to amortize a derivation — which is why
  // this asks `terrainSampleShape` for the node count rather than building the
  // grid to find out how big it would have been.
  const grid = terrain.grid ?? terrainDerivedGridForBulkSampling(terrain, nx * nz);
  const procedural = terrain.procedural;
  const heightAt = grid ? (x: number, z: number) => sampleTerrainGrid(grid, x, z)
    : procedural ? (x: number, z: number) => sampleProceduralTerrain(procedural, x, z)
      : (x: number, z: number) => describedTerrainHeightAt(terrain, x, z);
  // Rows per yield offer, chosen so a batch is well inside a frame even on the
  // widest domain this bake sees: 1536 columns a row at depth 3, at about
  // 0.2 us a column.
  const rowsPerOffer = Math.max(1, Math.ceil(4096 / Math.max(1, nx)));
  for (let z = 0; z < nz; z += 1) {
    for (let x = 0; x < nx; x += 1) {
      const worldX = originX_m + (x + 0.5) * cellX_m;
      const worldZ = originZ_m + (z + 0.5) * cellZ_m;
      heights[x + nx * z] = Math.min(maximumHeight_m, heightAt(worldX, worldZ));
    }
    if ((z + 1) % rowsPerOffer === 0) yield;
  }
  return heights;
}

/**
 * Bake per-column ground heights (metres) at cell centres of an nx-by-nz
 * lattice spanning the container footprint. Row-major, index x + nx * z —
 * the layout every solver's column texture uses.
 */
export function terrainColumnHeights(
  scene: { terrain?: TerrainDescription; container: { width_m: number; height_m: number; depth_m: number } },
  nx: number,
  nz: number
): Float32Array {
  const c = scene.container;
  if (!sceneHasTerrain(scene)) return new Float32Array(nx * nz);
  return terrainColumnHeightsForLattice(scene.terrain, {
    originX_m: -0.5 * c.width_m, originZ_m: -0.5 * c.depth_m,
    cellX_m: c.width_m / nx, cellZ_m: c.depth_m / nz,
    nx, nz, maximumHeight_m: c.height_m,
  });
}

/** Solid fraction of a grid cell cut by the terrain column height. */
export function terrainCellSolidFraction(columnHeight_m: number, cellBottom_m: number, cellSize_m: number): number {
  if (cellSize_m <= 0) return 0;
  return Math.max(0, Math.min(1, (columnHeight_m - cellBottom_m) / cellSize_m));
}

/**
 * One-way bake of the analytic form onto a lattice, so the first brush stroke
 * on an authored preset starts from exactly the ground that was being drawn.
 * The lattice spans the container footprint with a one-sample margin on each
 * side, so edge columns are sampled rather than extrapolated.
 */
export function bakeTerrainGrid(
  terrain: TerrainDescription | undefined,
  container: Pick<SceneDescription["container"], "width_m" | "height_m" | "depth_m">,
  spacing_m: number,
): TerrainGrid {
  if (!(spacing_m > 0)) throw new RangeError("Terrain grid spacing must be positive");
  const nx = Math.max(MIN_TERRAIN_GRID_SIZE, Math.ceil(container.width_m / spacing_m) + 1);
  const nz = Math.max(MIN_TERRAIN_GRID_SIZE, Math.ceil(container.depth_m / spacing_m) + 1);
  if (nx * nz > MAX_TERRAIN_GRID_SAMPLES) throw new RangeError(`Terrain grid ${nx}x${nz} exceeds ${MAX_TERRAIN_GRID_SAMPLES} samples`);
  const origin_m = { x: -0.5 * container.width_m, z: -0.5 * container.depth_m };
  const heights_m = new Array<number>(nx * nz);
  for (let j = 0; j < nz; j += 1) for (let i = 0; i < nx; i += 1) {
    const height = terrainHeightAt(terrain, origin_m.x + i * spacing_m, origin_m.z + j * spacing_m);
    heights_m[i + nx * j] = Math.min(container.height_m, Math.max(0, height));
  }
  return { kind: "grid", origin_m, spacing_m, size: { nx, nz }, heights_m };
}

/**
 * Radial brush stroke. The falloff is the same smoothstep the analytic
 * features use, so a sculpted rim reads like an authored one. Heights stay in
 * [0, container height] — the range every solver's column texture assumes.
 */
export function applyTerrainBrush(
  grid: TerrainGrid,
  centerX_m: number,
  centerZ_m: number,
  radius_m: number,
  delta_m: number,
  maximumHeight_m: number,
): TerrainGrid {
  if (!(radius_m > 0)) return grid;
  const { nx, nz } = grid.size;
  const heights_m = grid.heights_m.slice();
  const first = (value: number, origin: number) => Math.max(0, Math.floor((value - radius_m - origin) / grid.spacing_m));
  const last = (value: number, origin: number, count: number) => Math.min(count - 1, Math.ceil((value + radius_m - origin) / grid.spacing_m));
  for (let j = first(centerZ_m, grid.origin_m.z); j <= last(centerZ_m, grid.origin_m.z, nz); j += 1) {
    for (let i = first(centerX_m, grid.origin_m.x); i <= last(centerX_m, grid.origin_m.x, nx); i += 1) {
      const dx = grid.origin_m.x + i * grid.spacing_m - centerX_m;
      const dz = grid.origin_m.z + j * grid.spacing_m - centerZ_m;
      const distance = Math.hypot(dx, dz) / radius_m;
      if (distance >= 1) continue;
      const s = 1 - distance;
      const weight = s * s * (3 - 2 * s);
      const index = i + nx * j;
      heights_m[index] = Math.min(maximumHeight_m, Math.max(0, heights_m[index] + delta_m * weight));
    }
  }
  return { ...grid, heights_m };
}

function validateTerrainGrid(
  grid: TerrainGrid,
  container: Pick<SceneDescription["container"], "width_m" | "height_m" | "depth_m">,
): string[] {
  const errors: string[] = [];
  if (grid.kind !== "grid") errors.push("Terrain grid kind must be \"grid\"");
  if (!Number.isFinite(grid.origin_m?.x) || !Number.isFinite(grid.origin_m?.z)) errors.push("Terrain grid origin must be finite");
  if (!(grid.spacing_m > 0) || !Number.isFinite(grid.spacing_m)) errors.push("Terrain grid spacing must be positive and finite");
  const nx = grid.size?.nx, nz = grid.size?.nz;
  if (!Number.isInteger(nx) || !Number.isInteger(nz) || nx < MIN_TERRAIN_GRID_SIZE || nz < MIN_TERRAIN_GRID_SIZE) {
    errors.push(`Terrain grid size must be at least ${MIN_TERRAIN_GRID_SIZE} samples per axis`);
    return errors;
  }
  if (nx * nz > MAX_TERRAIN_GRID_SAMPLES) errors.push(`Terrain grid exceeds ${MAX_TERRAIN_GRID_SAMPLES} samples`);
  if (!Array.isArray(grid.heights_m) || grid.heights_m.length !== nx * nz) {
    errors.push("Terrain grid heights must be a row-major array of nx * nz samples");
    return errors;
  }
  if (!grid.heights_m.every((height) => Number.isFinite(height) && height >= 0 && height <= container.height_m)) {
    errors.push("Terrain grid heights must be finite and inside [0, container height]");
  }
  return errors;
}

/**
 * Everything about a described ground that can be checked without deriving it.
 *
 * The lattice is checked here rather than left to `bakePondVesselTerrain`
 * because a spacing that overruns the derived budget is a document error the
 * loader can report, while the same mistake discovered inside a derivation is a
 * throw from the middle of a publication.
 */
function validateTerrainProcedural(procedural: TerrainProcedural): string[] {
  const errors: string[] = [];
  if (procedural.kind !== "pond-vessel") {
    errors.push(`Unsupported procedural terrain kind ${String((procedural as { kind?: unknown }).kind)}`);
    return errors;
  }
  if (!(procedural.spacing_m > 0) || !Number.isFinite(procedural.spacing_m)) {
    errors.push("Procedural terrain spacing must be positive and finite");
    return errors;
  }
  const { width_m, height_m, depth_m } = procedural.container ?? {};
  if (!(width_m > 0) || !(height_m > 0) || !(depth_m > 0)) {
    errors.push("Procedural terrain container extents must be positive");
    return errors;
  }
  const shape = terrainSampleShape({ baseHeight_m: 0, features: [], procedural });
  if (shape && shape.nx * shape.nz > MAX_TERRAIN_DERIVED_GRID_SAMPLES) {
    errors.push(`Procedural terrain ${shape.nx}x${shape.nz} exceeds ${MAX_TERRAIN_DERIVED_GRID_SAMPLES} derived samples`);
  }
  if (!procedural.spec) errors.push("Procedural terrain needs a generator spec");
  return errors;
}

const TERRAIN_AUTHORING_RAY_FAST_MIN_VERTICAL = 0.35;
const TERRAIN_AUTHORING_RAY_FAST_BRACKET_STEPS = 2;
const TERRAIN_AUTHORING_RAY_FAST_REFINEMENTS = 5;
const TERRAIN_AUTHORING_RAY_FALLBACK_STEPS = 20;
const TERRAIN_AUTHORING_RAY_FALLBACK_REFINEMENTS = 8;
const TERRAIN_AUTHORING_RAY_GRID_MARCH_STEPS = 64;
const TERRAIN_AUTHORING_RAY_GRID_REFINEMENTS = 8;
const TERRAIN_AUTHORING_RAY_GRID_EPSILON_SAMPLES = 0.25;

/** CPU-only hit used by editor picking against authored terrain metadata. */
export interface TerrainAuthoringRayHit {
  t_m: number;
  position_m: { x: number; y: number; z: number };
  normal: { x: number; y: number; z: number };
  solver: "fast" | "fallback" | "sculpted";
  heightEvaluations: number;
}

function marchAuthoredTerrainGrid(
  terrain: TerrainDescription,
  grid: TerrainGrid,
  origin_m: { x: number; y: number; z: number },
  rd: { x: number; y: number; z: number },
  ceiling: number,
  sceneScale_m: number,
  normalEpsilon_m: number,
): TerrainAuthoringRayHit | undefined {
  const extent = terrainGridExtent(grid);
  let t0 = 0.005;
  if (origin_m.y > ceiling) {
    if (rd.y >= -0.0005) return undefined;
    t0 = (ceiling - origin_m.y) / rd.y;
  }
  const span = t0 + 10 * sceneScale_m;
  let t1 = span;
  let bracketed = false;
  if (rd.y < -0.0005) {
    const lowestT = (extent.minimum_m - origin_m.y) / rd.y;
    if (lowestT > t0 && lowestT <= span) { t1 = lowestT; bracketed = true; }
  } else if (rd.y > 0.0005) {
    t1 = Math.min(t1, Math.max(t0, (ceiling - origin_m.y) / rd.y));
  }
  if (!(t1 > t0)) return undefined;

  const pointAt = (t: number) => ({ x: origin_m.x + rd.x * t, y: origin_m.y + rd.y * t, z: origin_m.z + rd.z * t });
  let heightEvaluations = 0;
  const fieldAt = (t: number) => {
    const point = pointAt(t);
    heightEvaluations += 1;
    return point.y - terrainHeightAt(terrain, point.x, point.z);
  };
  const surfaceHit = (t_m: number): TerrainAuthoringRayHit => {
    const position_m = pointAt(t_m);
    heightEvaluations += 4;
    return { t_m, position_m, normal: terrainNormalAt(terrain, position_m.x, position_m.z, normalEpsilon_m), solver: "sculpted", heightEvaluations };
  };

  const rate = Math.max(1e-4, Math.abs(rd.y) + extent.slopeBound * Math.hypot(rd.x, rd.z));
  const epsilon = Math.max(1e-6, TERRAIN_AUTHORING_RAY_GRID_EPSILON_SAMPLES * grid.spacing_m);
  let t = t0, lastOutside = t0, lastOutsideField = 0;
  for (let step = 0; step < TERRAIN_AUTHORING_RAY_GRID_MARCH_STEPS && t <= t1; step += 1) {
    const field = fieldAt(t);
    if (Math.abs(field) <= epsilon) {
      if (!(t > lastOutside)) return surfaceHit(t);
      const slope = (field - lastOutsideField) / (t - lastOutside);
      if (!(Math.abs(slope) > 1e-6)) return surfaceHit(t);
      const corrected = Math.min(t1, Math.max(t0, t - field / slope));
      return Math.abs(fieldAt(corrected)) < Math.abs(field) ? surfaceHit(corrected) : surfaceHit(t);
    }
    lastOutside = t;
    lastOutsideField = field;
    t += Math.abs(field) / rate;
  }
  if (!bracketed || !(lastOutsideField > 0)) return undefined;
  let a = lastOutside, b = t1;
  for (let refinement = 0; refinement < TERRAIN_AUTHORING_RAY_GRID_REFINEMENTS; refinement += 1) {
    const middle = 0.5 * (a + b);
    if (fieldAt(middle) > 0) a = middle; else b = middle;
  }
  return surfaceHit(0.5 * (a + b));
}

/**
 * CPU-only intersection for editor hover and vessel-rim picking.
 * Terrain descriptions remain authoring metadata; render publication consumes
 * their voxelized SolidWorld result instead of this analytic query.
 */
export function intersectAuthoredTerrain(
  terrain: TerrainDescription | undefined,
  origin_m: { x: number; y: number; z: number },
  direction: { x: number; y: number; z: number },
  sceneScale_m: number,
  normalEpsilon_m = 0.02,
): TerrainAuthoringRayHit | undefined {
  if (!terrain) return undefined;
  const directionLength = Math.hypot(direction.x, direction.y, direction.z);
  if (!(directionLength > 1e-9) || !(sceneScale_m > 0) || !Number.isFinite(sceneScale_m)) return undefined;
  const rd = { x: direction.x / directionLength, y: direction.y / directionLength, z: direction.z / directionLength };
  const ceiling = terrainCeiling(terrain);
  const grid = terrainSampleGrid(terrain);
  if (grid) return marchAuthoredTerrainGrid(terrain, grid, origin_m, rd, ceiling, sceneScale_m, normalEpsilon_m);
  let t0 = 0.005;
  if (origin_m.y > ceiling) {
    if (rd.y >= -0.0005) return undefined;
    t0 = (ceiling - origin_m.y) / rd.y;
  }
  let t1 = t0 + 10 * sceneScale_m;
  if (rd.y < -0.0005) t1 = Math.min(t1, (-0.02 - origin_m.y) / rd.y);
  else if (rd.y > 0.0005) t1 = Math.min(t1, Math.max(t0, (ceiling - origin_m.y) / rd.y));
  if (!(t1 > t0)) return undefined;
  const pointAt = (t: number) => ({ x: origin_m.x + rd.x * t, y: origin_m.y + rd.y * t, z: origin_m.z + rd.z * t });
  let heightEvaluations = 0;
  const fieldAt = (t: number) => {
    const point = pointAt(t);
    heightEvaluations += 1;
    return point.y - terrainHeightAt(terrain, point.x, point.z);
  };
  const surfaceHit = (t_m: number, solver: TerrainAuthoringRayHit["solver"]): TerrainAuthoringRayHit => {
    const position_m = pointAt(t_m);
    heightEvaluations += 4;
    return { t_m, position_m, normal: terrainNormalAt(terrain, position_m.x, position_m.z, normalEpsilon_m), solver, heightEvaluations };
  };
  const initialField = fieldAt(t0);
  const ordinaryRay = Math.abs(rd.y) >= TERRAIN_AUTHORING_RAY_FAST_MIN_VERTICAL;
  if (Math.abs(initialField) <= 1e-4) return surfaceHit(t0, ordinaryRay ? "fast" : "fallback");

  if (ordinaryRay) {
    let previousT = t0, previousField = initialField;
    for (let bracket = 1; bracket <= TERRAIN_AUTHORING_RAY_FAST_BRACKET_STEPS; bracket += 1) {
      const candidateT = t0 + (t1 - t0) * bracket / TERRAIN_AUTHORING_RAY_FAST_BRACKET_STEPS;
      const candidateField = fieldAt(candidateT);
      if (Math.abs(candidateField) <= 1e-4) return surfaceHit(candidateT, "fast");
      if ((previousField < 0) !== (candidateField < 0)) {
        let a = previousT, b = candidateT, fieldA = previousField, fieldB = candidateField;
        let bestT = Math.abs(fieldA) < Math.abs(fieldB) ? a : b;
        let bestAbsoluteField = Math.min(Math.abs(fieldA), Math.abs(fieldB));
        for (let refinement = 0; refinement < TERRAIN_AUTHORING_RAY_FAST_REFINEMENTS; refinement += 1) {
          const span = b - a;
          const secant = b - fieldB * span / (fieldB - fieldA);
          const t = Math.max(a + span * 0.05, Math.min(b - span * 0.05, Number.isFinite(secant) ? secant : 0.5 * (a + b)));
          const field = fieldAt(t), absoluteField = Math.abs(field);
          if (absoluteField < bestAbsoluteField) { bestAbsoluteField = absoluteField; bestT = t; }
          if (absoluteField <= 1e-4) return surfaceHit(t, "fast");
          if ((fieldA < 0) === (field < 0)) { a = t; fieldA = field; }
          else { b = t; fieldB = field; }
        }
        if (bestAbsoluteField <= 1e-4) return surfaceHit(bestT, "fast");
        break;
      }
      previousT = candidateT;
      previousField = candidateField;
    }
  }

  let previousT = t0;
  let previousField = initialField;
  let closestT = t0;
  let closestAbsoluteField = Math.abs(initialField);
  for (let iteration = 1; iteration <= TERRAIN_AUTHORING_RAY_FALLBACK_STEPS; iteration += 1) {
    const t = t0 + (t1 - t0) * (iteration / TERRAIN_AUTHORING_RAY_FALLBACK_STEPS) ** 1.4;
    const field = fieldAt(t);
    const absoluteField = Math.abs(field);
    if (absoluteField < closestAbsoluteField) { closestAbsoluteField = absoluteField; closestT = t; }
    if ((previousField < 0) !== (field < 0)) {
      let a = previousT, b = t, fieldA = previousField;
      for (let refinement = 0; refinement < TERRAIN_AUTHORING_RAY_FALLBACK_REFINEMENTS; refinement += 1) {
        const middle = 0.5 * (a + b), middleField = fieldAt(middle);
        if ((fieldA < 0) === (middleField < 0)) { a = middle; fieldA = middleField; }
        else b = middle;
      }
      return surfaceHit(0.5 * (a + b), "fallback");
    }
    if (absoluteField <= 1e-4) return surfaceHit(t, "fallback");
    previousT = t;
    previousField = field;
  }
  return closestAbsoluteField <= 5e-4 ? surfaceHit(closestT, "fallback") : undefined;
}

export function validateTerrain(
  terrain: TerrainDescription,
  container: Pick<SceneDescription["container"], "width_m" | "height_m" | "depth_m">
): string[] {
  const errors: string[] = [];
  if (!(terrain.baseHeight_m >= 0) || terrain.baseHeight_m >= container.height_m) {
    errors.push("Terrain base height must be inside [0, container height)");
  }
  if (terrain.grid) errors.push(...validateTerrainGrid(terrain.grid, container));
  if (terrain.procedural) errors.push(...validateTerrainProcedural(terrain.procedural));
  if (!Array.isArray(terrain.features)) {
    errors.push("Terrain features must be an array");
    return errors;
  }
  if (terrain.features.length > MAX_TERRAIN_FEATURES) errors.push(`Terrain supports at most ${MAX_TERRAIN_FEATURES} features`);
  for (const feature of terrain.features) {
    if (feature.kind !== "basin" && feature.kind !== "mound") errors.push(`Unsupported terrain feature kind ${String((feature as { kind?: unknown }).kind)}`);
    if (!(feature.amount_m > 0)) errors.push("Terrain feature amount must be positive");
    if (!(feature.radius_m?.x > 0) || !(feature.radius_m?.z > 0)) errors.push("Terrain feature radii must be positive");
    if (feature.flat !== undefined && !(feature.flat >= 0 && feature.flat < 1)) errors.push("Terrain feature flat fraction must be in [0, 1)");
    if (feature.rotation_rad !== undefined && !Number.isFinite(feature.rotation_rad)) errors.push("Terrain feature rotation must be finite");
    if (feature.kind === "basin" && feature.amount_m > terrain.baseHeight_m + 1e-9) {
      errors.push("Terrain basin depth cannot exceed the base ground height");
    }
  }
  return errors;
}
